site_name: "QWGraph Documentation v1.0"

nav:
  - Home: 'index.md'
  - QWSearch: 'qwsearch.md'
  - Coins: 'coins.md'
  - Demo: 'demo.md'

theme:
  name: material
  navigation_depth: 5
    


plugins:
- search
- mkdocstrings
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js