"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 28, 1, '', 'google/cloud/documentai/v1beta3/document_processor_service.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.documentai.v1beta3 import document_pb2 as google_dot_cloud_dot_documentai_dot_v1beta3_dot_document__pb2
from .....google.cloud.documentai.v1beta3 import document_io_pb2 as google_dot_cloud_dot_documentai_dot_v1beta3_dot_document__io__pb2
from .....google.cloud.documentai.v1beta3 import document_schema_pb2 as google_dot_cloud_dot_documentai_dot_v1beta3_dot_document__schema__pb2
from .....google.cloud.documentai.v1beta3 import evaluation_pb2 as google_dot_cloud_dot_documentai_dot_v1beta3_dot_evaluation__pb2
from .....google.cloud.documentai.v1beta3 import operation_metadata_pb2 as google_dot_cloud_dot_documentai_dot_v1beta3_dot_operation__metadata__pb2
from .....google.cloud.documentai.v1beta3 import processor_pb2 as google_dot_cloud_dot_documentai_dot_v1beta3_dot_processor__pb2
from .....google.cloud.documentai.v1beta3 import processor_type_pb2 as google_dot_cloud_dot_documentai_dot_v1beta3_dot_processor__type__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .....google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@google/cloud/documentai/v1beta3/document_processor_service.proto\x12\x1fgoogle.cloud.documentai.v1beta3\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a.google/cloud/documentai/v1beta3/document.proto\x1a1google/cloud/documentai/v1beta3/document_io.proto\x1a5google/cloud/documentai/v1beta3/document_schema.proto\x1a0google/cloud/documentai/v1beta3/evaluation.proto\x1a8google/cloud/documentai/v1beta3/operation_metadata.proto\x1a/google/cloud/documentai/v1beta3/processor.proto\x1a4google/cloud/documentai/v1beta3/processor_type.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto"\xf4\x05\n\x0eProcessOptions\x12j\n\x18individual_page_selector\x18\x05 \x01(\x0b2F.google.cloud.documentai.v1beta3.ProcessOptions.IndividualPageSelectorH\x00\x12\x14\n\nfrom_start\x18\x06 \x01(\x05H\x00\x12\x12\n\x08from_end\x18\x07 \x01(\x05H\x00\x12>\n\nocr_config\x18\x01 \x01(\x0b2*.google.cloud.documentai.v1beta3.OcrConfig\x12X\n\rlayout_config\x18\t \x01(\x0b2<.google.cloud.documentai.v1beta3.ProcessOptions.LayoutConfigB\x03\xe0A\x01\x12M\n\x0fschema_override\x18\x08 \x01(\x0b2/.google.cloud.documentai.v1beta3.DocumentSchemaB\x03\xe0A\x01\x1a\xa6\x02\n\x0cLayoutConfig\x12i\n\x0fchunking_config\x18\x01 \x01(\x0b2K.google.cloud.documentai.v1beta3.ProcessOptions.LayoutConfig.ChunkingConfigB\x03\xe0A\x01\x1a\xaa\x01\n\x0eChunkingConfig\x12\x17\n\nchunk_size\x18\x01 \x01(\x05B\x03\xe0A\x01\x12&\n\x19include_ancestor_headings\x18\x02 \x01(\x08B\x03\xe0A\x01\x12)\n\x1csemantic_chunking_group_size\x18\x03 \x01(\x08B\x03\xe0A\x01\x12,\n\x1fbreakpoint_percentile_threshold\x18\x04 \x01(\x05B\x03\xe0A\x01\x1a,\n\x16IndividualPageSelector\x12\x12\n\x05pages\x18\x01 \x03(\x05B\x03\xe0A\x01B\x0c\n\npage_range"\xf9\x04\n\x0eProcessRequest\x12D\n\x0finline_document\x18\x04 \x01(\x0b2).google.cloud.documentai.v1beta3.DocumentH\x00\x12D\n\x0craw_document\x18\x05 \x01(\x0b2,.google.cloud.documentai.v1beta3.RawDocumentH\x00\x12D\n\x0cgcs_document\x18\x08 \x01(\x0b2,.google.cloud.documentai.v1beta3.GcsDocumentH\x00\x12\x17\n\x04name\x18\x01 \x01(\tB\t\xe0A\x02\xfaA\x03\n\x01*\x12?\n\x08document\x18\x02 \x01(\x0b2).google.cloud.documentai.v1beta3.DocumentB\x02\x18\x01\x12\x19\n\x11skip_human_review\x18\x03 \x01(\x08\x12.\n\nfield_mask\x18\x06 \x01(\x0b2\x1a.google.protobuf.FieldMask\x12H\n\x0fprocess_options\x18\x07 \x01(\x0b2/.google.cloud.documentai.v1beta3.ProcessOptions\x12P\n\x06labels\x18\n \x03(\x0b2;.google.cloud.documentai.v1beta3.ProcessRequest.LabelsEntryB\x03\xe0A\x01\x12\x1b\n\x0eimageless_mode\x18\x0b \x01(\x08B\x03\xe0A\x01\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01B\x08\n\x06source"\xf3\x01\n\x11HumanReviewStatus\x12G\n\x05state\x18\x01 \x01(\x0e28.google.cloud.documentai.v1beta3.HumanReviewStatus.State\x12\x15\n\rstate_message\x18\x02 \x01(\t\x12\x1e\n\x16human_review_operation\x18\x03 \x01(\t"^\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07SKIPPED\x10\x01\x12\x15\n\x11VALIDATION_PASSED\x10\x02\x12\x0f\n\x0bIN_PROGRESS\x10\x03\x12\t\n\x05ERROR\x10\x04"\xc3\x01\n\x0fProcessResponse\x12;\n\x08document\x18\x01 \x01(\x0b2).google.cloud.documentai.v1beta3.Document\x12"\n\x16human_review_operation\x18\x02 \x01(\tB\x02\x18\x01\x12O\n\x13human_review_status\x18\x03 \x01(\x0b22.google.cloud.documentai.v1beta3.HumanReviewStatus"\xfb\x05\n\x13BatchProcessRequest\x12\x17\n\x04name\x18\x01 \x01(\tB\t\xe0A\x02\xfaA\x03\n\x01*\x12`\n\rinput_configs\x18\x02 \x03(\x0b2E.google.cloud.documentai.v1beta3.BatchProcessRequest.BatchInputConfigB\x02\x18\x01\x12a\n\routput_config\x18\x03 \x01(\x0b2F.google.cloud.documentai.v1beta3.BatchProcessRequest.BatchOutputConfigB\x02\x18\x01\x12S\n\x0finput_documents\x18\x05 \x01(\x0b2:.google.cloud.documentai.v1beta3.BatchDocumentsInputConfig\x12U\n\x16document_output_config\x18\x06 \x01(\x0b25.google.cloud.documentai.v1beta3.DocumentOutputConfig\x12\x19\n\x11skip_human_review\x18\x04 \x01(\x08\x12H\n\x0fprocess_options\x18\x07 \x01(\x0b2/.google.cloud.documentai.v1beta3.ProcessOptions\x12U\n\x06labels\x18\t \x03(\x0b2@.google.cloud.documentai.v1beta3.BatchProcessRequest.LabelsEntryB\x03\xe0A\x01\x1a=\n\x10BatchInputConfig\x12\x12\n\ngcs_source\x18\x01 \x01(\t\x12\x11\n\tmime_type\x18\x02 \x01(\t:\x02\x18\x01\x1a0\n\x11BatchOutputConfig\x12\x17\n\x0fgcs_destination\x18\x01 \x01(\t:\x02\x18\x01\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"\x16\n\x14BatchProcessResponse"\xb2\x05\n\x14BatchProcessMetadata\x12J\n\x05state\x18\x01 \x01(\x0e2;.google.cloud.documentai.v1beta3.BatchProcessMetadata.State\x12\x15\n\rstate_message\x18\x02 \x01(\t\x12/\n\x0bcreate_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bupdate_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12r\n\x1bindividual_process_statuses\x18\x05 \x03(\x0b2M.google.cloud.documentai.v1beta3.BatchProcessMetadata.IndividualProcessStatus\x1a\xec\x01\n\x17IndividualProcessStatus\x12\x18\n\x10input_gcs_source\x18\x01 \x01(\t\x12"\n\x06status\x18\x02 \x01(\x0b2\x12.google.rpc.Status\x12\x1e\n\x16output_gcs_destination\x18\x03 \x01(\t\x12"\n\x16human_review_operation\x18\x04 \x01(\tB\x02\x18\x01\x12O\n\x13human_review_status\x18\x05 \x01(\x0b22.google.cloud.documentai.v1beta3.HumanReviewStatus"r\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07WAITING\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\r\n\tSUCCEEDED\x10\x03\x12\x0e\n\nCANCELLING\x10\x04\x12\r\n\tCANCELLED\x10\x05\x12\n\n\x06FAILED\x10\x06"]\n\x1aFetchProcessorTypesRequest\x12?\n\x06parent\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\x12\'documentai.googleapis.com/ProcessorType"f\n\x1bFetchProcessorTypesResponse\x12G\n\x0fprocessor_types\x18\x01 \x03(\x0b2..google.cloud.documentai.v1beta3.ProcessorType"\x83\x01\n\x19ListProcessorTypesRequest\x12?\n\x06parent\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\x12\'documentai.googleapis.com/ProcessorType\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"~\n\x1aListProcessorTypesResponse\x12G\n\x0fprocessor_types\x18\x01 \x03(\x0b2..google.cloud.documentai.v1beta3.ProcessorType\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"{\n\x15ListProcessorsRequest\x12;\n\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\x12#documentai.googleapis.com/Processor\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"q\n\x16ListProcessorsResponse\x12>\n\nprocessors\x18\x01 \x03(\x0b2*.google.cloud.documentai.v1beta3.Processor\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"X\n\x17GetProcessorTypeRequest\x12=\n\x04name\x18\x01 \x01(\tB/\xe0A\x02\xfaA)\n\'documentai.googleapis.com/ProcessorType"P\n\x13GetProcessorRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor"^\n\x1aGetProcessorVersionRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion"\x89\x01\n\x1cListProcessorVersionsRequest\x12B\n\x06parent\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\x12*documentai.googleapis.com/ProcessorVersion\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"\x87\x01\n\x1dListProcessorVersionsResponse\x12M\n\x12processor_versions\x18\x01 \x03(\x0b21.google.cloud.documentai.v1beta3.ProcessorVersion\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"a\n\x1dDeleteProcessorVersionRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion"s\n\x1eDeleteProcessorVersionMetadata\x12Q\n\x0fcommon_metadata\x18\x01 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata"a\n\x1dDeployProcessorVersionRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion" \n\x1eDeployProcessorVersionResponse"s\n\x1eDeployProcessorVersionMetadata\x12Q\n\x0fcommon_metadata\x18\x01 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata"c\n\x1fUndeployProcessorVersionRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion""\n UndeployProcessorVersionResponse"u\n UndeployProcessorVersionMetadata\x12Q\n\x0fcommon_metadata\x18\x01 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata"\x99\x01\n\x16CreateProcessorRequest\x12;\n\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\x12#documentai.googleapis.com/Processor\x12B\n\tprocessor\x18\x02 \x01(\x0b2*.google.cloud.documentai.v1beta3.ProcessorB\x03\xe0A\x02"S\n\x16DeleteProcessorRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor"l\n\x17DeleteProcessorMetadata\x12Q\n\x0fcommon_metadata\x18\x05 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata"S\n\x16EnableProcessorRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor"\x19\n\x17EnableProcessorResponse"l\n\x17EnableProcessorMetadata\x12Q\n\x0fcommon_metadata\x18\x05 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata"T\n\x17DisableProcessorRequest\x129\n\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor"\x1a\n\x18DisableProcessorResponse"m\n\x18DisableProcessorMetadata\x12Q\n\x0fcommon_metadata\x18\x05 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata"\xba\x01\n!SetDefaultProcessorVersionRequest\x12>\n\tprocessor\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor\x12U\n\x19default_processor_version\x18\x02 \x01(\tB2\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion"$\n"SetDefaultProcessorVersionResponse"w\n"SetDefaultProcessorVersionMetadata\x12Q\n\x0fcommon_metadata\x18\x01 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata"\xcc\t\n\x1cTrainProcessorVersionRequest\x12\x8b\x01\n"custom_document_extraction_options\x18\x05 \x01(\x0b2].google.cloud.documentai.v1beta3.TrainProcessorVersionRequest.CustomDocumentExtractionOptionsH\x00\x12\x85\x01\n\x1ffoundation_model_tuning_options\x18\x0c \x01(\x0b2Z.google.cloud.documentai.v1beta3.TrainProcessorVersionRequest.FoundationModelTuningOptionsH\x00\x12;\n\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor\x12Q\n\x11processor_version\x18\x02 \x01(\x0b21.google.cloud.documentai.v1beta3.ProcessorVersionB\x03\xe0A\x02\x12M\n\x0fdocument_schema\x18\n \x01(\x0b2/.google.cloud.documentai.v1beta3.DocumentSchemaB\x03\xe0A\x01\x12`\n\ninput_data\x18\x04 \x01(\x0b2G.google.cloud.documentai.v1beta3.TrainProcessorVersionRequest.InputDataB\x03\xe0A\x01\x12#\n\x16base_processor_version\x18\x08 \x01(\tB\x03\xe0A\x01\x1a\xb7\x01\n\tInputData\x12V\n\x12training_documents\x18\x03 \x01(\x0b2:.google.cloud.documentai.v1beta3.BatchDocumentsInputConfig\x12R\n\x0etest_documents\x18\x04 \x01(\x0b2:.google.cloud.documentai.v1beta3.BatchDocumentsInputConfig\x1a\x81\x02\n\x1fCustomDocumentExtractionOptions\x12\x85\x01\n\x0ftraining_method\x18\x03 \x01(\x0e2l.google.cloud.documentai.v1beta3.TrainProcessorVersionRequest.CustomDocumentExtractionOptions.TrainingMethod"V\n\x0eTrainingMethod\x12\x1f\n\x1bTRAINING_METHOD_UNSPECIFIED\x10\x00\x12\x0f\n\x0bMODEL_BASED\x10\x01\x12\x12\n\x0eTEMPLATE_BASED\x10\x02\x1a_\n\x1cFoundationModelTuningOptions\x12\x18\n\x0btrain_steps\x18\x02 \x01(\x05B\x03\xe0A\x01\x12%\n\x18learning_rate_multiplier\x18\x03 \x01(\x02B\x03\xe0A\x01B\x11\n\x0fprocessor_flags":\n\x1dTrainProcessorVersionResponse\x12\x19\n\x11processor_version\x18\x01 \x01(\t"\x86\x04\n\x1dTrainProcessorVersionMetadata\x12Q\n\x0fcommon_metadata\x18\x01 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata\x12u\n\x1btraining_dataset_validation\x18\x02 \x01(\x0b2P.google.cloud.documentai.v1beta3.TrainProcessorVersionMetadata.DatasetValidation\x12q\n\x17test_dataset_validation\x18\x03 \x01(\x0b2P.google.cloud.documentai.v1beta3.TrainProcessorVersionMetadata.DatasetValidation\x1a\xa7\x01\n\x11DatasetValidation\x12\x1c\n\x14document_error_count\x18\x03 \x01(\x05\x12\x1b\n\x13dataset_error_count\x18\x04 \x01(\x05\x12+\n\x0fdocument_errors\x18\x01 \x03(\x0b2\x12.google.rpc.Status\x12*\n\x0edataset_errors\x18\x02 \x03(\x0b2\x12.google.rpc.Status"\xde\x03\n\x15ReviewDocumentRequest\x12D\n\x0finline_document\x18\x04 \x01(\x0b2).google.cloud.documentai.v1beta3.DocumentH\x00\x12P\n\x13human_review_config\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+documentai.googleapis.com/HumanReviewConfig\x12?\n\x08document\x18\x02 \x01(\x0b2).google.cloud.documentai.v1beta3.DocumentB\x02\x18\x01\x12 \n\x18enable_schema_validation\x18\x03 \x01(\x08\x12Q\n\x08priority\x18\x05 \x01(\x0e2?.google.cloud.documentai.v1beta3.ReviewDocumentRequest.Priority\x12H\n\x0fdocument_schema\x18\x06 \x01(\x0b2/.google.cloud.documentai.v1beta3.DocumentSchema"#\n\x08Priority\x12\x0b\n\x07DEFAULT\x10\x00\x12\n\n\x06URGENT\x10\x01B\x08\n\x06source"\xd6\x01\n\x16ReviewDocumentResponse\x12\x17\n\x0fgcs_destination\x18\x01 \x01(\t\x12L\n\x05state\x18\x02 \x01(\x0e2=.google.cloud.documentai.v1beta3.ReviewDocumentResponse.State\x12\x18\n\x10rejection_reason\x18\x03 \x01(\t";\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08REJECTED\x10\x01\x12\r\n\tSUCCEEDED\x10\x02"\xc0\x03\n\x1fReviewDocumentOperationMetadata\x12U\n\x05state\x18\x01 \x01(\x0e2F.google.cloud.documentai.v1beta3.ReviewDocumentOperationMetadata.State\x12\x15\n\rstate_message\x18\x02 \x01(\t\x12/\n\x0bcreate_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12/\n\x0bupdate_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12Q\n\x0fcommon_metadata\x18\x05 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata\x12\x13\n\x0bquestion_id\x18\x06 \x01(\t"e\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0e\n\nCANCELLING\x10\x02\x12\r\n\tSUCCEEDED\x10\x03\x12\n\n\x06FAILED\x10\x04\x12\r\n\tCANCELLED\x10\x05"\xcf\x01\n\x1fEvaluateProcessorVersionRequest\x12M\n\x11processor_version\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion\x12]\n\x14evaluation_documents\x18\x03 \x01(\x0b2:.google.cloud.documentai.v1beta3.BatchDocumentsInputConfigB\x03\xe0A\x01"u\n EvaluateProcessorVersionMetadata\x12Q\n\x0fcommon_metadata\x18\x01 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata"6\n EvaluateProcessorVersionResponse\x12\x12\n\nevaluation\x18\x02 \x01(\t"R\n\x14GetEvaluationRequest\x12:\n\x04name\x18\x01 \x01(\tB,\xe0A\x02\xfaA&\n$documentai.googleapis.com/Evaluation"\x83\x01\n\x16ListEvaluationsRequest\x12B\n\x06parent\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"t\n\x17ListEvaluationsResponse\x12@\n\x0bevaluations\x18\x01 \x03(\x0b2+.google.cloud.documentai.v1beta3.Evaluation\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xb0\x03\n\x1dImportProcessorVersionRequest\x12S\n\x18processor_version_source\x18\x02 \x01(\tB/\xfaA,\n*documentai.googleapis.com/ProcessorVersionH\x00\x12\x8a\x01\n!external_processor_version_source\x18\x03 \x01(\x0b2].google.cloud.documentai.v1beta3.ImportProcessorVersionRequest.ExternalProcessorVersionSourceH\x00\x12B\n\x06parent\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\x12*documentai.googleapis.com/ProcessorVersion\x1a_\n\x1eExternalProcessorVersionSource\x12\x1e\n\x11processor_version\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x1d\n\x10service_endpoint\x18\x02 \x01(\tB\x03\xe0A\x01B\x08\n\x06source"l\n\x1eImportProcessorVersionResponse\x12J\n\x11processor_version\x18\x01 \x01(\tB/\xfaA,\n*documentai.googleapis.com/ProcessorVersion"s\n\x1eImportProcessorVersionMetadata\x12Q\n\x0fcommon_metadata\x18\x01 \x01(\x0b28.google.cloud.documentai.v1beta3.CommonOperationMetadata2\xeb.\n\x18DocumentProcessorService\x12\x9b\x02\n\x0fProcessDocument\x12/.google.cloud.documentai.v1beta3.ProcessRequest\x1a0.google.cloud.documentai.v1beta3.ProcessResponse"\xa4\x01\xdaA\x04name\x82\xd3\xe4\x93\x02\x96\x01";/v1beta3/{name=projects/*/locations/*/processors/*}:process:\x01*ZT"O/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}:process:\x01*\x12\xcc\x02\n\x15BatchProcessDocuments\x124.google.cloud.documentai.v1beta3.BatchProcessRequest\x1a\x1d.google.longrunning.Operation"\xdd\x01\xcaA,\n\x14BatchProcessResponse\x12\x14BatchProcessMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02\xa0\x01"@/v1beta3/{name=projects/*/locations/*/processors/*}:batchProcess:\x01*ZY"T/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}:batchProcess:\x01*\x12\xdf\x01\n\x13FetchProcessorTypes\x12;.google.cloud.documentai.v1beta3.FetchProcessorTypesRequest\x1a<.google.cloud.documentai.v1beta3.FetchProcessorTypesResponse"M\xdaA\x06parent\x82\xd3\xe4\x93\x02>\x12</v1beta3/{parent=projects/*/locations/*}:fetchProcessorTypes\x12\xd7\x01\n\x12ListProcessorTypes\x12:.google.cloud.documentai.v1beta3.ListProcessorTypesRequest\x1a;.google.cloud.documentai.v1beta3.ListProcessorTypesResponse"H\xdaA\x06parent\x82\xd3\xe4\x93\x029\x127/v1beta3/{parent=projects/*/locations/*}/processorTypes\x12\xc4\x01\n\x10GetProcessorType\x128.google.cloud.documentai.v1beta3.GetProcessorTypeRequest\x1a..google.cloud.documentai.v1beta3.ProcessorType"F\xdaA\x04name\x82\xd3\xe4\x93\x029\x127/v1beta3/{name=projects/*/locations/*/processorTypes/*}\x12\xc7\x01\n\x0eListProcessors\x126.google.cloud.documentai.v1beta3.ListProcessorsRequest\x1a7.google.cloud.documentai.v1beta3.ListProcessorsResponse"D\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1beta3/{parent=projects/*/locations/*}/processors\x12\xb4\x01\n\x0cGetProcessor\x124.google.cloud.documentai.v1beta3.GetProcessorRequest\x1a*.google.cloud.documentai.v1beta3.Processor"B\xdaA\x04name\x82\xd3\xe4\x93\x025\x123/v1beta3/{name=projects/*/locations/*/processors/*}\x12\xac\x02\n\x15TrainProcessorVersion\x12=.google.cloud.documentai.v1beta3.TrainProcessorVersionRequest\x1a\x1d.google.longrunning.Operation"\xb4\x01\xcaA>\n\x1dTrainProcessorVersionResponse\x12\x1dTrainProcessorVersionMetadata\xdaA\x18parent,processor_version\x82\xd3\xe4\x93\x02R"M/v1beta3/{parent=projects/*/locations/*/processors/*}/processorVersions:train:\x01*\x12\xdd\x01\n\x13GetProcessorVersion\x12;.google.cloud.documentai.v1beta3.GetProcessorVersionRequest\x1a1.google.cloud.documentai.v1beta3.ProcessorVersion"V\xdaA\x04name\x82\xd3\xe4\x93\x02I\x12G/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}\x12\xf0\x01\n\x15ListProcessorVersions\x12=.google.cloud.documentai.v1beta3.ListProcessorVersionsRequest\x1a>.google.cloud.documentai.v1beta3.ListProcessorVersionsResponse"X\xdaA\x06parent\x82\xd3\xe4\x93\x02I\x12G/v1beta3/{parent=projects/*/locations/*/processors/*}/processorVersions\x12\x8a\x02\n\x16DeleteProcessorVersion\x12>.google.cloud.documentai.v1beta3.DeleteProcessorVersionRequest\x1a\x1d.google.longrunning.Operation"\x90\x01\xcaA7\n\x15google.protobuf.Empty\x12\x1eDeleteProcessorVersionMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02I*G/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}\x12\x9d\x02\n\x16DeployProcessorVersion\x12>.google.cloud.documentai.v1beta3.DeployProcessorVersionRequest\x1a\x1d.google.longrunning.Operation"\xa3\x01\xcaA@\n\x1eDeployProcessorVersionResponse\x12\x1eDeployProcessorVersionMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02S"N/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}:deploy:\x01*\x12\xa7\x02\n\x18UndeployProcessorVersion\x12@.google.cloud.documentai.v1beta3.UndeployProcessorVersionRequest\x1a\x1d.google.longrunning.Operation"\xa9\x01\xcaAD\n UndeployProcessorVersionResponse\x12 UndeployProcessorVersionMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02U"P/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}:undeploy:\x01*\x12\xd1\x01\n\x0fCreateProcessor\x127.google.cloud.documentai.v1beta3.CreateProcessorRequest\x1a*.google.cloud.documentai.v1beta3.Processor"Y\xdaA\x10parent,processor\x82\xd3\xe4\x93\x02@"3/v1beta3/{parent=projects/*/locations/*}/processors:\tprocessor\x12\xe0\x01\n\x0fDeleteProcessor\x127.google.cloud.documentai.v1beta3.DeleteProcessorRequest\x1a\x1d.google.longrunning.Operation"u\xcaA0\n\x15google.protobuf.Empty\x12\x17DeleteProcessorMetadata\xdaA\x04name\x82\xd3\xe4\x93\x025*3/v1beta3/{name=projects/*/locations/*/processors/*}\x12\xe5\x01\n\x0fEnableProcessor\x127.google.cloud.documentai.v1beta3.EnableProcessorRequest\x1a\x1d.google.longrunning.Operation"z\xcaA2\n\x17EnableProcessorResponse\x12\x17EnableProcessorMetadata\x82\xd3\xe4\x93\x02?":/v1beta3/{name=projects/*/locations/*/processors/*}:enable:\x01*\x12\xea\x01\n\x10DisableProcessor\x128.google.cloud.documentai.v1beta3.DisableProcessorRequest\x1a\x1d.google.longrunning.Operation"}\xcaA4\n\x18DisableProcessorResponse\x12\x18DisableProcessorMetadata\x82\xd3\xe4\x93\x02@";/v1beta3/{name=projects/*/locations/*/processors/*}:disable:\x01*\x12\xab\x02\n\x1aSetDefaultProcessorVersion\x12B.google.cloud.documentai.v1beta3.SetDefaultProcessorVersionRequest\x1a\x1d.google.longrunning.Operation"\xa9\x01\xcaAH\n"SetDefaultProcessorVersionResponse\x12"SetDefaultProcessorVersionMetadata\x82\xd3\xe4\x93\x02X"S/v1beta3/{processor=projects/*/locations/*/processors/*}:setDefaultProcessorVersion:\x01*\x12\xaa\x02\n\x0eReviewDocument\x126.google.cloud.documentai.v1beta3.ReviewDocumentRequest\x1a\x1d.google.longrunning.Operation"\xc0\x01\xcaA9\n\x16ReviewDocumentResponse\x12\x1fReviewDocumentOperationMetadata\xdaA\x13human_review_config\x82\xd3\xe4\x93\x02h"c/v1beta3/{human_review_config=projects/*/locations/*/processors/*/humanReviewConfig}:reviewDocument:\x01*\x12\xd1\x02\n\x18EvaluateProcessorVersion\x12@.google.cloud.documentai.v1beta3.EvaluateProcessorVersionRequest\x1a\x1d.google.longrunning.Operation"\xd3\x01\xcaAD\n EvaluateProcessorVersionResponse\x12 EvaluateProcessorVersionMetadata\xdaA\x11processor_version\x82\xd3\xe4\x93\x02r"m/v1beta3/{processor_version=projects/*/locations/*/processors/*/processorVersions/*}:evaluateProcessorVersion:\x01*\x12\xd9\x01\n\rGetEvaluation\x125.google.cloud.documentai.v1beta3.GetEvaluationRequest\x1a+.google.cloud.documentai.v1beta3.Evaluation"d\xdaA\x04name\x82\xd3\xe4\x93\x02W\x12U/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*/evaluations/*}\x12\xec\x01\n\x0fListEvaluations\x127.google.cloud.documentai.v1beta3.ListEvaluationsRequest\x1a8.google.cloud.documentai.v1beta3.ListEvaluationsResponse"f\xdaA\x06parent\x82\xd3\xe4\x93\x02W\x12U/v1beta3/{parent=projects/*/locations/*/processors/*/processorVersions/*}/evaluations\x12\xaf\x02\n\x16ImportProcessorVersion\x12>.google.cloud.documentai.v1beta3.ImportProcessorVersionRequest\x1a\x1d.google.longrunning.Operation"\xb5\x01\xcaA@\n\x1eImportProcessorVersionResponse\x12\x1eImportProcessorVersionMetadata\xdaA\x06parent\x82\xd3\xe4\x93\x02c"^/v1beta3/{parent=projects/*/locations/*/processors/*}/processorVersions:importProcessorVersion:\x01*\x1aM\xcaA\x19documentai.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xc3\x03\n#com.google.cloud.documentai.v1beta3B\x1aDocumentAiProcessorServiceP\x01ZCcloud.google.com/go/documentai/apiv1beta3/documentaipb;documentaipb\xaa\x02\x1fGoogle.Cloud.DocumentAI.V1Beta3\xca\x02\x1fGoogle\\Cloud\\DocumentAI\\V1beta3\xea\x02"Google::Cloud::DocumentAI::V1beta3\xeaA\x7f\n+documentai.googleapis.com/HumanReviewConfig\x12Pprojects/{project}/locations/{location}/processors/{processor}/humanReviewConfig\xeaAM\n"documentai.googleapis.com/Location\x12\'projects/{project}/locations/{location}b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.documentai.v1beta3.document_processor_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n#com.google.cloud.documentai.v1beta3B\x1aDocumentAiProcessorServiceP\x01ZCcloud.google.com/go/documentai/apiv1beta3/documentaipb;documentaipb\xaa\x02\x1fGoogle.Cloud.DocumentAI.V1Beta3\xca\x02\x1fGoogle\\Cloud\\DocumentAI\\V1beta3\xea\x02"Google::Cloud::DocumentAI::V1beta3\xeaA\x7f\n+documentai.googleapis.com/HumanReviewConfig\x12Pprojects/{project}/locations/{location}/processors/{processor}/humanReviewConfig\xeaAM\n"documentai.googleapis.com/Location\x12\'projects/{project}/locations/{location}'
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG_CHUNKINGCONFIG'].fields_by_name['chunk_size']._loaded_options = None
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG_CHUNKINGCONFIG'].fields_by_name['chunk_size']._serialized_options = b'\xe0A\x01'
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG_CHUNKINGCONFIG'].fields_by_name['include_ancestor_headings']._loaded_options = None
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG_CHUNKINGCONFIG'].fields_by_name['include_ancestor_headings']._serialized_options = b'\xe0A\x01'
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG_CHUNKINGCONFIG'].fields_by_name['semantic_chunking_group_size']._loaded_options = None
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG_CHUNKINGCONFIG'].fields_by_name['semantic_chunking_group_size']._serialized_options = b'\xe0A\x01'
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG_CHUNKINGCONFIG'].fields_by_name['breakpoint_percentile_threshold']._loaded_options = None
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG_CHUNKINGCONFIG'].fields_by_name['breakpoint_percentile_threshold']._serialized_options = b'\xe0A\x01'
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG'].fields_by_name['chunking_config']._loaded_options = None
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG'].fields_by_name['chunking_config']._serialized_options = b'\xe0A\x01'
    _globals['_PROCESSOPTIONS_INDIVIDUALPAGESELECTOR'].fields_by_name['pages']._loaded_options = None
    _globals['_PROCESSOPTIONS_INDIVIDUALPAGESELECTOR'].fields_by_name['pages']._serialized_options = b'\xe0A\x01'
    _globals['_PROCESSOPTIONS'].fields_by_name['layout_config']._loaded_options = None
    _globals['_PROCESSOPTIONS'].fields_by_name['layout_config']._serialized_options = b'\xe0A\x01'
    _globals['_PROCESSOPTIONS'].fields_by_name['schema_override']._loaded_options = None
    _globals['_PROCESSOPTIONS'].fields_by_name['schema_override']._serialized_options = b'\xe0A\x01'
    _globals['_PROCESSREQUEST_LABELSENTRY']._loaded_options = None
    _globals['_PROCESSREQUEST_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_PROCESSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_PROCESSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_PROCESSREQUEST'].fields_by_name['document']._loaded_options = None
    _globals['_PROCESSREQUEST'].fields_by_name['document']._serialized_options = b'\x18\x01'
    _globals['_PROCESSREQUEST'].fields_by_name['labels']._loaded_options = None
    _globals['_PROCESSREQUEST'].fields_by_name['labels']._serialized_options = b'\xe0A\x01'
    _globals['_PROCESSREQUEST'].fields_by_name['imageless_mode']._loaded_options = None
    _globals['_PROCESSREQUEST'].fields_by_name['imageless_mode']._serialized_options = b'\xe0A\x01'
    _globals['_PROCESSRESPONSE'].fields_by_name['human_review_operation']._loaded_options = None
    _globals['_PROCESSRESPONSE'].fields_by_name['human_review_operation']._serialized_options = b'\x18\x01'
    _globals['_BATCHPROCESSREQUEST_BATCHINPUTCONFIG']._loaded_options = None
    _globals['_BATCHPROCESSREQUEST_BATCHINPUTCONFIG']._serialized_options = b'\x18\x01'
    _globals['_BATCHPROCESSREQUEST_BATCHOUTPUTCONFIG']._loaded_options = None
    _globals['_BATCHPROCESSREQUEST_BATCHOUTPUTCONFIG']._serialized_options = b'\x18\x01'
    _globals['_BATCHPROCESSREQUEST_LABELSENTRY']._loaded_options = None
    _globals['_BATCHPROCESSREQUEST_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_BATCHPROCESSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_BATCHPROCESSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x03\n\x01*'
    _globals['_BATCHPROCESSREQUEST'].fields_by_name['input_configs']._loaded_options = None
    _globals['_BATCHPROCESSREQUEST'].fields_by_name['input_configs']._serialized_options = b'\x18\x01'
    _globals['_BATCHPROCESSREQUEST'].fields_by_name['output_config']._loaded_options = None
    _globals['_BATCHPROCESSREQUEST'].fields_by_name['output_config']._serialized_options = b'\x18\x01'
    _globals['_BATCHPROCESSREQUEST'].fields_by_name['labels']._loaded_options = None
    _globals['_BATCHPROCESSREQUEST'].fields_by_name['labels']._serialized_options = b'\xe0A\x01'
    _globals['_BATCHPROCESSMETADATA_INDIVIDUALPROCESSSTATUS'].fields_by_name['human_review_operation']._loaded_options = None
    _globals['_BATCHPROCESSMETADATA_INDIVIDUALPROCESSSTATUS'].fields_by_name['human_review_operation']._serialized_options = b'\x18\x01'
    _globals['_FETCHPROCESSORTYPESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_FETCHPROCESSORTYPESREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA)\x12'documentai.googleapis.com/ProcessorType"
    _globals['_LISTPROCESSORTYPESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTPROCESSORTYPESREQUEST'].fields_by_name['parent']._serialized_options = b"\xe0A\x02\xfaA)\x12'documentai.googleapis.com/ProcessorType"
    _globals['_LISTPROCESSORSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTPROCESSORSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\x12#documentai.googleapis.com/Processor'
    _globals['_GETPROCESSORTYPEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETPROCESSORTYPEREQUEST'].fields_by_name['name']._serialized_options = b"\xe0A\x02\xfaA)\n'documentai.googleapis.com/ProcessorType"
    _globals['_GETPROCESSORREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETPROCESSORREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor'
    _globals['_GETPROCESSORVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETPROCESSORVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion'
    _globals['_LISTPROCESSORVERSIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTPROCESSORVERSIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA,\x12*documentai.googleapis.com/ProcessorVersion'
    _globals['_DELETEPROCESSORVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEPROCESSORVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion'
    _globals['_DEPLOYPROCESSORVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DEPLOYPROCESSORVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion'
    _globals['_UNDEPLOYPROCESSORVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_UNDEPLOYPROCESSORVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion'
    _globals['_CREATEPROCESSORREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEPROCESSORREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\x12#documentai.googleapis.com/Processor'
    _globals['_CREATEPROCESSORREQUEST'].fields_by_name['processor']._loaded_options = None
    _globals['_CREATEPROCESSORREQUEST'].fields_by_name['processor']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEPROCESSORREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEPROCESSORREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor'
    _globals['_ENABLEPROCESSORREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_ENABLEPROCESSORREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor'
    _globals['_DISABLEPROCESSORREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DISABLEPROCESSORREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor'
    _globals['_SETDEFAULTPROCESSORVERSIONREQUEST'].fields_by_name['processor']._loaded_options = None
    _globals['_SETDEFAULTPROCESSORVERSIONREQUEST'].fields_by_name['processor']._serialized_options = b'\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor'
    _globals['_SETDEFAULTPROCESSORVERSIONREQUEST'].fields_by_name['default_processor_version']._loaded_options = None
    _globals['_SETDEFAULTPROCESSORVERSIONREQUEST'].fields_by_name['default_processor_version']._serialized_options = b'\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion'
    _globals['_TRAINPROCESSORVERSIONREQUEST_FOUNDATIONMODELTUNINGOPTIONS'].fields_by_name['train_steps']._loaded_options = None
    _globals['_TRAINPROCESSORVERSIONREQUEST_FOUNDATIONMODELTUNINGOPTIONS'].fields_by_name['train_steps']._serialized_options = b'\xe0A\x01'
    _globals['_TRAINPROCESSORVERSIONREQUEST_FOUNDATIONMODELTUNINGOPTIONS'].fields_by_name['learning_rate_multiplier']._loaded_options = None
    _globals['_TRAINPROCESSORVERSIONREQUEST_FOUNDATIONMODELTUNINGOPTIONS'].fields_by_name['learning_rate_multiplier']._serialized_options = b'\xe0A\x01'
    _globals['_TRAINPROCESSORVERSIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_TRAINPROCESSORVERSIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA%\n#documentai.googleapis.com/Processor'
    _globals['_TRAINPROCESSORVERSIONREQUEST'].fields_by_name['processor_version']._loaded_options = None
    _globals['_TRAINPROCESSORVERSIONREQUEST'].fields_by_name['processor_version']._serialized_options = b'\xe0A\x02'
    _globals['_TRAINPROCESSORVERSIONREQUEST'].fields_by_name['document_schema']._loaded_options = None
    _globals['_TRAINPROCESSORVERSIONREQUEST'].fields_by_name['document_schema']._serialized_options = b'\xe0A\x01'
    _globals['_TRAINPROCESSORVERSIONREQUEST'].fields_by_name['input_data']._loaded_options = None
    _globals['_TRAINPROCESSORVERSIONREQUEST'].fields_by_name['input_data']._serialized_options = b'\xe0A\x01'
    _globals['_TRAINPROCESSORVERSIONREQUEST'].fields_by_name['base_processor_version']._loaded_options = None
    _globals['_TRAINPROCESSORVERSIONREQUEST'].fields_by_name['base_processor_version']._serialized_options = b'\xe0A\x01'
    _globals['_REVIEWDOCUMENTREQUEST'].fields_by_name['human_review_config']._loaded_options = None
    _globals['_REVIEWDOCUMENTREQUEST'].fields_by_name['human_review_config']._serialized_options = b'\xe0A\x02\xfaA-\n+documentai.googleapis.com/HumanReviewConfig'
    _globals['_REVIEWDOCUMENTREQUEST'].fields_by_name['document']._loaded_options = None
    _globals['_REVIEWDOCUMENTREQUEST'].fields_by_name['document']._serialized_options = b'\x18\x01'
    _globals['_EVALUATEPROCESSORVERSIONREQUEST'].fields_by_name['processor_version']._loaded_options = None
    _globals['_EVALUATEPROCESSORVERSIONREQUEST'].fields_by_name['processor_version']._serialized_options = b'\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion'
    _globals['_EVALUATEPROCESSORVERSIONREQUEST'].fields_by_name['evaluation_documents']._loaded_options = None
    _globals['_EVALUATEPROCESSORVERSIONREQUEST'].fields_by_name['evaluation_documents']._serialized_options = b'\xe0A\x01'
    _globals['_GETEVALUATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETEVALUATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA&\n$documentai.googleapis.com/Evaluation'
    _globals['_LISTEVALUATIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTEVALUATIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA,\n*documentai.googleapis.com/ProcessorVersion'
    _globals['_IMPORTPROCESSORVERSIONREQUEST_EXTERNALPROCESSORVERSIONSOURCE'].fields_by_name['processor_version']._loaded_options = None
    _globals['_IMPORTPROCESSORVERSIONREQUEST_EXTERNALPROCESSORVERSIONSOURCE'].fields_by_name['processor_version']._serialized_options = b'\xe0A\x02'
    _globals['_IMPORTPROCESSORVERSIONREQUEST_EXTERNALPROCESSORVERSIONSOURCE'].fields_by_name['service_endpoint']._loaded_options = None
    _globals['_IMPORTPROCESSORVERSIONREQUEST_EXTERNALPROCESSORVERSIONSOURCE'].fields_by_name['service_endpoint']._serialized_options = b'\xe0A\x01'
    _globals['_IMPORTPROCESSORVERSIONREQUEST'].fields_by_name['processor_version_source']._loaded_options = None
    _globals['_IMPORTPROCESSORVERSIONREQUEST'].fields_by_name['processor_version_source']._serialized_options = b'\xfaA,\n*documentai.googleapis.com/ProcessorVersion'
    _globals['_IMPORTPROCESSORVERSIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_IMPORTPROCESSORVERSIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA,\x12*documentai.googleapis.com/ProcessorVersion'
    _globals['_IMPORTPROCESSORVERSIONRESPONSE'].fields_by_name['processor_version']._loaded_options = None
    _globals['_IMPORTPROCESSORVERSIONRESPONSE'].fields_by_name['processor_version']._serialized_options = b'\xfaA,\n*documentai.googleapis.com/ProcessorVersion'
    _globals['_DOCUMENTPROCESSORSERVICE']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE']._serialized_options = b'\xcaA\x19documentai.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ProcessDocument']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ProcessDocument']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02\x96\x01";/v1beta3/{name=projects/*/locations/*/processors/*}:process:\x01*ZT"O/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}:process:\x01*'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['BatchProcessDocuments']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['BatchProcessDocuments']._serialized_options = b'\xcaA,\n\x14BatchProcessResponse\x12\x14BatchProcessMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02\xa0\x01"@/v1beta3/{name=projects/*/locations/*/processors/*}:batchProcess:\x01*ZY"T/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}:batchProcess:\x01*'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['FetchProcessorTypes']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['FetchProcessorTypes']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02>\x12</v1beta3/{parent=projects/*/locations/*}:fetchProcessorTypes'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ListProcessorTypes']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ListProcessorTypes']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x029\x127/v1beta3/{parent=projects/*/locations/*}/processorTypes'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['GetProcessorType']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['GetProcessorType']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x029\x127/v1beta3/{name=projects/*/locations/*/processorTypes/*}'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ListProcessors']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ListProcessors']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x025\x123/v1beta3/{parent=projects/*/locations/*}/processors'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['GetProcessor']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['GetProcessor']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x025\x123/v1beta3/{name=projects/*/locations/*/processors/*}'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['TrainProcessorVersion']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['TrainProcessorVersion']._serialized_options = b'\xcaA>\n\x1dTrainProcessorVersionResponse\x12\x1dTrainProcessorVersionMetadata\xdaA\x18parent,processor_version\x82\xd3\xe4\x93\x02R"M/v1beta3/{parent=projects/*/locations/*/processors/*}/processorVersions:train:\x01*'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['GetProcessorVersion']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['GetProcessorVersion']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02I\x12G/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ListProcessorVersions']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ListProcessorVersions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02I\x12G/v1beta3/{parent=projects/*/locations/*/processors/*}/processorVersions'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['DeleteProcessorVersion']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['DeleteProcessorVersion']._serialized_options = b'\xcaA7\n\x15google.protobuf.Empty\x12\x1eDeleteProcessorVersionMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02I*G/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['DeployProcessorVersion']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['DeployProcessorVersion']._serialized_options = b'\xcaA@\n\x1eDeployProcessorVersionResponse\x12\x1eDeployProcessorVersionMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02S"N/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}:deploy:\x01*'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['UndeployProcessorVersion']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['UndeployProcessorVersion']._serialized_options = b'\xcaAD\n UndeployProcessorVersionResponse\x12 UndeployProcessorVersionMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02U"P/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*}:undeploy:\x01*'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['CreateProcessor']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['CreateProcessor']._serialized_options = b'\xdaA\x10parent,processor\x82\xd3\xe4\x93\x02@"3/v1beta3/{parent=projects/*/locations/*}/processors:\tprocessor'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['DeleteProcessor']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['DeleteProcessor']._serialized_options = b'\xcaA0\n\x15google.protobuf.Empty\x12\x17DeleteProcessorMetadata\xdaA\x04name\x82\xd3\xe4\x93\x025*3/v1beta3/{name=projects/*/locations/*/processors/*}'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['EnableProcessor']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['EnableProcessor']._serialized_options = b'\xcaA2\n\x17EnableProcessorResponse\x12\x17EnableProcessorMetadata\x82\xd3\xe4\x93\x02?":/v1beta3/{name=projects/*/locations/*/processors/*}:enable:\x01*'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['DisableProcessor']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['DisableProcessor']._serialized_options = b'\xcaA4\n\x18DisableProcessorResponse\x12\x18DisableProcessorMetadata\x82\xd3\xe4\x93\x02@";/v1beta3/{name=projects/*/locations/*/processors/*}:disable:\x01*'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['SetDefaultProcessorVersion']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['SetDefaultProcessorVersion']._serialized_options = b'\xcaAH\n"SetDefaultProcessorVersionResponse\x12"SetDefaultProcessorVersionMetadata\x82\xd3\xe4\x93\x02X"S/v1beta3/{processor=projects/*/locations/*/processors/*}:setDefaultProcessorVersion:\x01*'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ReviewDocument']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ReviewDocument']._serialized_options = b'\xcaA9\n\x16ReviewDocumentResponse\x12\x1fReviewDocumentOperationMetadata\xdaA\x13human_review_config\x82\xd3\xe4\x93\x02h"c/v1beta3/{human_review_config=projects/*/locations/*/processors/*/humanReviewConfig}:reviewDocument:\x01*'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['EvaluateProcessorVersion']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['EvaluateProcessorVersion']._serialized_options = b'\xcaAD\n EvaluateProcessorVersionResponse\x12 EvaluateProcessorVersionMetadata\xdaA\x11processor_version\x82\xd3\xe4\x93\x02r"m/v1beta3/{processor_version=projects/*/locations/*/processors/*/processorVersions/*}:evaluateProcessorVersion:\x01*'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['GetEvaluation']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['GetEvaluation']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02W\x12U/v1beta3/{name=projects/*/locations/*/processors/*/processorVersions/*/evaluations/*}'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ListEvaluations']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ListEvaluations']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02W\x12U/v1beta3/{parent=projects/*/locations/*/processors/*/processorVersions/*}/evaluations'
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ImportProcessorVersion']._loaded_options = None
    _globals['_DOCUMENTPROCESSORSERVICE'].methods_by_name['ImportProcessorVersion']._serialized_options = b'\xcaA@\n\x1eImportProcessorVersionResponse\x12\x1eImportProcessorVersionMetadata\xdaA\x06parent\x82\xd3\xe4\x93\x02c"^/v1beta3/{parent=projects/*/locations/*/processors/*}/processorVersions:importProcessorVersion:\x01*'
    _globals['_PROCESSOPTIONS']._serialized_start = 740
    _globals['_PROCESSOPTIONS']._serialized_end = 1496
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG']._serialized_start = 1142
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG']._serialized_end = 1436
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG_CHUNKINGCONFIG']._serialized_start = 1266
    _globals['_PROCESSOPTIONS_LAYOUTCONFIG_CHUNKINGCONFIG']._serialized_end = 1436
    _globals['_PROCESSOPTIONS_INDIVIDUALPAGESELECTOR']._serialized_start = 1438
    _globals['_PROCESSOPTIONS_INDIVIDUALPAGESELECTOR']._serialized_end = 1482
    _globals['_PROCESSREQUEST']._serialized_start = 1499
    _globals['_PROCESSREQUEST']._serialized_end = 2132
    _globals['_PROCESSREQUEST_LABELSENTRY']._serialized_start = 2077
    _globals['_PROCESSREQUEST_LABELSENTRY']._serialized_end = 2122
    _globals['_HUMANREVIEWSTATUS']._serialized_start = 2135
    _globals['_HUMANREVIEWSTATUS']._serialized_end = 2378
    _globals['_HUMANREVIEWSTATUS_STATE']._serialized_start = 2284
    _globals['_HUMANREVIEWSTATUS_STATE']._serialized_end = 2378
    _globals['_PROCESSRESPONSE']._serialized_start = 2381
    _globals['_PROCESSRESPONSE']._serialized_end = 2576
    _globals['_BATCHPROCESSREQUEST']._serialized_start = 2579
    _globals['_BATCHPROCESSREQUEST']._serialized_end = 3342
    _globals['_BATCHPROCESSREQUEST_BATCHINPUTCONFIG']._serialized_start = 3184
    _globals['_BATCHPROCESSREQUEST_BATCHINPUTCONFIG']._serialized_end = 3245
    _globals['_BATCHPROCESSREQUEST_BATCHOUTPUTCONFIG']._serialized_start = 3247
    _globals['_BATCHPROCESSREQUEST_BATCHOUTPUTCONFIG']._serialized_end = 3295
    _globals['_BATCHPROCESSREQUEST_LABELSENTRY']._serialized_start = 2077
    _globals['_BATCHPROCESSREQUEST_LABELSENTRY']._serialized_end = 2122
    _globals['_BATCHPROCESSRESPONSE']._serialized_start = 3344
    _globals['_BATCHPROCESSRESPONSE']._serialized_end = 3366
    _globals['_BATCHPROCESSMETADATA']._serialized_start = 3369
    _globals['_BATCHPROCESSMETADATA']._serialized_end = 4059
    _globals['_BATCHPROCESSMETADATA_INDIVIDUALPROCESSSTATUS']._serialized_start = 3707
    _globals['_BATCHPROCESSMETADATA_INDIVIDUALPROCESSSTATUS']._serialized_end = 3943
    _globals['_BATCHPROCESSMETADATA_STATE']._serialized_start = 3945
    _globals['_BATCHPROCESSMETADATA_STATE']._serialized_end = 4059
    _globals['_FETCHPROCESSORTYPESREQUEST']._serialized_start = 4061
    _globals['_FETCHPROCESSORTYPESREQUEST']._serialized_end = 4154
    _globals['_FETCHPROCESSORTYPESRESPONSE']._serialized_start = 4156
    _globals['_FETCHPROCESSORTYPESRESPONSE']._serialized_end = 4258
    _globals['_LISTPROCESSORTYPESREQUEST']._serialized_start = 4261
    _globals['_LISTPROCESSORTYPESREQUEST']._serialized_end = 4392
    _globals['_LISTPROCESSORTYPESRESPONSE']._serialized_start = 4394
    _globals['_LISTPROCESSORTYPESRESPONSE']._serialized_end = 4520
    _globals['_LISTPROCESSORSREQUEST']._serialized_start = 4522
    _globals['_LISTPROCESSORSREQUEST']._serialized_end = 4645
    _globals['_LISTPROCESSORSRESPONSE']._serialized_start = 4647
    _globals['_LISTPROCESSORSRESPONSE']._serialized_end = 4760
    _globals['_GETPROCESSORTYPEREQUEST']._serialized_start = 4762
    _globals['_GETPROCESSORTYPEREQUEST']._serialized_end = 4850
    _globals['_GETPROCESSORREQUEST']._serialized_start = 4852
    _globals['_GETPROCESSORREQUEST']._serialized_end = 4932
    _globals['_GETPROCESSORVERSIONREQUEST']._serialized_start = 4934
    _globals['_GETPROCESSORVERSIONREQUEST']._serialized_end = 5028
    _globals['_LISTPROCESSORVERSIONSREQUEST']._serialized_start = 5031
    _globals['_LISTPROCESSORVERSIONSREQUEST']._serialized_end = 5168
    _globals['_LISTPROCESSORVERSIONSRESPONSE']._serialized_start = 5171
    _globals['_LISTPROCESSORVERSIONSRESPONSE']._serialized_end = 5306
    _globals['_DELETEPROCESSORVERSIONREQUEST']._serialized_start = 5308
    _globals['_DELETEPROCESSORVERSIONREQUEST']._serialized_end = 5405
    _globals['_DELETEPROCESSORVERSIONMETADATA']._serialized_start = 5407
    _globals['_DELETEPROCESSORVERSIONMETADATA']._serialized_end = 5522
    _globals['_DEPLOYPROCESSORVERSIONREQUEST']._serialized_start = 5524
    _globals['_DEPLOYPROCESSORVERSIONREQUEST']._serialized_end = 5621
    _globals['_DEPLOYPROCESSORVERSIONRESPONSE']._serialized_start = 5623
    _globals['_DEPLOYPROCESSORVERSIONRESPONSE']._serialized_end = 5655
    _globals['_DEPLOYPROCESSORVERSIONMETADATA']._serialized_start = 5657
    _globals['_DEPLOYPROCESSORVERSIONMETADATA']._serialized_end = 5772
    _globals['_UNDEPLOYPROCESSORVERSIONREQUEST']._serialized_start = 5774
    _globals['_UNDEPLOYPROCESSORVERSIONREQUEST']._serialized_end = 5873
    _globals['_UNDEPLOYPROCESSORVERSIONRESPONSE']._serialized_start = 5875
    _globals['_UNDEPLOYPROCESSORVERSIONRESPONSE']._serialized_end = 5909
    _globals['_UNDEPLOYPROCESSORVERSIONMETADATA']._serialized_start = 5911
    _globals['_UNDEPLOYPROCESSORVERSIONMETADATA']._serialized_end = 6028
    _globals['_CREATEPROCESSORREQUEST']._serialized_start = 6031
    _globals['_CREATEPROCESSORREQUEST']._serialized_end = 6184
    _globals['_DELETEPROCESSORREQUEST']._serialized_start = 6186
    _globals['_DELETEPROCESSORREQUEST']._serialized_end = 6269
    _globals['_DELETEPROCESSORMETADATA']._serialized_start = 6271
    _globals['_DELETEPROCESSORMETADATA']._serialized_end = 6379
    _globals['_ENABLEPROCESSORREQUEST']._serialized_start = 6381
    _globals['_ENABLEPROCESSORREQUEST']._serialized_end = 6464
    _globals['_ENABLEPROCESSORRESPONSE']._serialized_start = 6466
    _globals['_ENABLEPROCESSORRESPONSE']._serialized_end = 6491
    _globals['_ENABLEPROCESSORMETADATA']._serialized_start = 6493
    _globals['_ENABLEPROCESSORMETADATA']._serialized_end = 6601
    _globals['_DISABLEPROCESSORREQUEST']._serialized_start = 6603
    _globals['_DISABLEPROCESSORREQUEST']._serialized_end = 6687
    _globals['_DISABLEPROCESSORRESPONSE']._serialized_start = 6689
    _globals['_DISABLEPROCESSORRESPONSE']._serialized_end = 6715
    _globals['_DISABLEPROCESSORMETADATA']._serialized_start = 6717
    _globals['_DISABLEPROCESSORMETADATA']._serialized_end = 6826
    _globals['_SETDEFAULTPROCESSORVERSIONREQUEST']._serialized_start = 6829
    _globals['_SETDEFAULTPROCESSORVERSIONREQUEST']._serialized_end = 7015
    _globals['_SETDEFAULTPROCESSORVERSIONRESPONSE']._serialized_start = 7017
    _globals['_SETDEFAULTPROCESSORVERSIONRESPONSE']._serialized_end = 7053
    _globals['_SETDEFAULTPROCESSORVERSIONMETADATA']._serialized_start = 7055
    _globals['_SETDEFAULTPROCESSORVERSIONMETADATA']._serialized_end = 7174
    _globals['_TRAINPROCESSORVERSIONREQUEST']._serialized_start = 7177
    _globals['_TRAINPROCESSORVERSIONREQUEST']._serialized_end = 8405
    _globals['_TRAINPROCESSORVERSIONREQUEST_INPUTDATA']._serialized_start = 7846
    _globals['_TRAINPROCESSORVERSIONREQUEST_INPUTDATA']._serialized_end = 8029
    _globals['_TRAINPROCESSORVERSIONREQUEST_CUSTOMDOCUMENTEXTRACTIONOPTIONS']._serialized_start = 8032
    _globals['_TRAINPROCESSORVERSIONREQUEST_CUSTOMDOCUMENTEXTRACTIONOPTIONS']._serialized_end = 8289
    _globals['_TRAINPROCESSORVERSIONREQUEST_CUSTOMDOCUMENTEXTRACTIONOPTIONS_TRAININGMETHOD']._serialized_start = 8203
    _globals['_TRAINPROCESSORVERSIONREQUEST_CUSTOMDOCUMENTEXTRACTIONOPTIONS_TRAININGMETHOD']._serialized_end = 8289
    _globals['_TRAINPROCESSORVERSIONREQUEST_FOUNDATIONMODELTUNINGOPTIONS']._serialized_start = 8291
    _globals['_TRAINPROCESSORVERSIONREQUEST_FOUNDATIONMODELTUNINGOPTIONS']._serialized_end = 8386
    _globals['_TRAINPROCESSORVERSIONRESPONSE']._serialized_start = 8407
    _globals['_TRAINPROCESSORVERSIONRESPONSE']._serialized_end = 8465
    _globals['_TRAINPROCESSORVERSIONMETADATA']._serialized_start = 8468
    _globals['_TRAINPROCESSORVERSIONMETADATA']._serialized_end = 8986
    _globals['_TRAINPROCESSORVERSIONMETADATA_DATASETVALIDATION']._serialized_start = 8819
    _globals['_TRAINPROCESSORVERSIONMETADATA_DATASETVALIDATION']._serialized_end = 8986
    _globals['_REVIEWDOCUMENTREQUEST']._serialized_start = 8989
    _globals['_REVIEWDOCUMENTREQUEST']._serialized_end = 9467
    _globals['_REVIEWDOCUMENTREQUEST_PRIORITY']._serialized_start = 9422
    _globals['_REVIEWDOCUMENTREQUEST_PRIORITY']._serialized_end = 9457
    _globals['_REVIEWDOCUMENTRESPONSE']._serialized_start = 9470
    _globals['_REVIEWDOCUMENTRESPONSE']._serialized_end = 9684
    _globals['_REVIEWDOCUMENTRESPONSE_STATE']._serialized_start = 9625
    _globals['_REVIEWDOCUMENTRESPONSE_STATE']._serialized_end = 9684
    _globals['_REVIEWDOCUMENTOPERATIONMETADATA']._serialized_start = 9687
    _globals['_REVIEWDOCUMENTOPERATIONMETADATA']._serialized_end = 10135
    _globals['_REVIEWDOCUMENTOPERATIONMETADATA_STATE']._serialized_start = 10034
    _globals['_REVIEWDOCUMENTOPERATIONMETADATA_STATE']._serialized_end = 10135
    _globals['_EVALUATEPROCESSORVERSIONREQUEST']._serialized_start = 10138
    _globals['_EVALUATEPROCESSORVERSIONREQUEST']._serialized_end = 10345
    _globals['_EVALUATEPROCESSORVERSIONMETADATA']._serialized_start = 10347
    _globals['_EVALUATEPROCESSORVERSIONMETADATA']._serialized_end = 10464
    _globals['_EVALUATEPROCESSORVERSIONRESPONSE']._serialized_start = 10466
    _globals['_EVALUATEPROCESSORVERSIONRESPONSE']._serialized_end = 10520
    _globals['_GETEVALUATIONREQUEST']._serialized_start = 10522
    _globals['_GETEVALUATIONREQUEST']._serialized_end = 10604
    _globals['_LISTEVALUATIONSREQUEST']._serialized_start = 10607
    _globals['_LISTEVALUATIONSREQUEST']._serialized_end = 10738
    _globals['_LISTEVALUATIONSRESPONSE']._serialized_start = 10740
    _globals['_LISTEVALUATIONSRESPONSE']._serialized_end = 10856
    _globals['_IMPORTPROCESSORVERSIONREQUEST']._serialized_start = 10859
    _globals['_IMPORTPROCESSORVERSIONREQUEST']._serialized_end = 11291
    _globals['_IMPORTPROCESSORVERSIONREQUEST_EXTERNALPROCESSORVERSIONSOURCE']._serialized_start = 11186
    _globals['_IMPORTPROCESSORVERSIONREQUEST_EXTERNALPROCESSORVERSIONSOURCE']._serialized_end = 11281
    _globals['_IMPORTPROCESSORVERSIONRESPONSE']._serialized_start = 11293
    _globals['_IMPORTPROCESSORVERSIONRESPONSE']._serialized_end = 11401
    _globals['_IMPORTPROCESSORVERSIONMETADATA']._serialized_start = 11403
    _globals['_IMPORTPROCESSORVERSIONMETADATA']._serialized_end = 11518
    _globals['_DOCUMENTPROCESSORSERVICE']._serialized_start = 11521
    _globals['_DOCUMENTPROCESSORSERVICE']._serialized_end = 17516