[project]
name = "fastapi_essentials"
version = "0.2.1"
description = "fastapi plugin to register common functionality"
authors = []
dependencies = [
    "fastapi>=0.111.1",
    "asgi-correlation-id>=4.3.1",
    "python-json-logger>=2.0.7",
    "pyttp>=0.1.2",
]
readme = "README.md"
requires-python = ">= 3.10"

[tool.rye]
managed = true
dev-dependencies = [
    "mypy>=1.10.1",
    "pytest-cov>=5.0.0",
    "ruff>=0.5.0",
    "pytest-mock>=3.14.0",
    "mkdocs>=1.6.0",
    "mkdocstrings[python]>=0.25.1",
    "mkdocs-material>=9.5.29",
    "httpx>=0.28.1",
]

[tool.rye.scripts]
test = { cmd = "pytest --cov=src/ tests/" }
test-ui = { cmd = "pytest --cov=src/ --cov-report=html tests/" }
fix = { chain = [
   "ruff check --fix --quiet",
   "format:ruff",
]}
"format:ruff" = "ruff format"

"lint" = "ruff check --fix"

"docs:serve" =  { cmd = "mkdocs serve -f mkdocs.yml" }

[build-system]
requires = ["hatchling==1.26.3", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.isort]
length-sort = true
length-sort-straight = true
combine-as-imports = true
known-first-party = ["fastapi_essentials", "tests"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.report]
fail_under = 90

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/fastapi_essentials"]
