[frame]
font.name = "Meiryo UI"
font.size = 9

[frame.index.name]
fill.color = "#ffffaa"
font.color = "#333300"
font.bold = true

[frame.index]
fill.color = "#ffffee"
font.color = "#111100"
font.bold = false

[frame.columns.name]
fill.color = "#88eeff"
font.color = "#002244"
font.bold = true

[frame.columns]
fill.color = "#ccffff"
font.color = "#004455"
font.bold = true

[frame.wide-columns.name]
fill.color = "#e0ffe0"
font.color = "#002244"
font.bold = true

[frame.wide-columns]
fill.color = "#f0fff0"
font.color = "#004455"
font.bold = false

[frame.gray]
fill.color = "#eeeeee"
font.color = "#aaaaaa"
border.color = "#aaaaaa"

[frame.values]
fill.color = "#ffffff"
font.color = "#001122"
font.bold = false

[stats]
soa.color = "#5555FF"
soa.italic = true
min.color = "#7777FF"
mean.color = "#33aa33"
max.color = "#FF7777"
sum.color = "purple"
sum.italic = true
std.color = "#aaaaaa"
count.color = "gray"

[chart]
width = 200
height = 200
font.name = "Meiryo UI"

[chart.title]
font.size = 9
font.bold = true

[chart.legend]
font.size = 8

[chart.axis.title]
font.size = 9

[chart.axis.ticklabels]
font.size = 8
