[project]
name = "scattered"
version = "0.0.0"
description = "3D scatterplots are useless, but fun"
readme = "README.md"
authors = [
    { name = "David Kouril", email = "david.kouril@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
widget = "widget:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
