# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/ads/searchads360/v0/resources/ad_group_bid_modifier.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'google/ads/searchads360/v0/resources/ad_group_bid_modifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.ads.searchads360.v0.common import criteria_pb2 as google_dot_ads_dot_searchads360_dot_v0_dot_common_dot_criteria__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@google/ads/searchads360/v0/resources/ad_group_bid_modifier.proto\x12$google.ads.searchads360.v0.resources\x1a\x30google/ads/searchads360/v0/common/criteria.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xe1\x02\n\x12\x41\x64GroupBidModifier\x12M\n\rresource_name\x18\x01 \x01(\tB6\xe0\x41\x05\xfa\x41\x30\n.searchads360.googleapis.com/AdGroupBidModifier\x12\x19\n\x0c\x62id_modifier\x18\x0f \x01(\x01H\x01\x88\x01\x01\x12\x44\n\x06\x64\x65vice\x18\x0b \x01(\x0b\x32-.google.ads.searchads360.v0.common.DeviceInfoB\x03\xe0\x41\x05H\x00:}\xea\x41z\n.searchads360.googleapis.com/AdGroupBidModifier\x12Hcustomers/{customer_id}/adGroupBidModifiers/{ad_group_id}~{criterion_id}B\x0b\n\tcriterionB\x0f\n\r_bid_modifierB\x97\x02\n(com.google.ads.searchads360.v0.resourcesB\x17\x41\x64GroupBidModifierProtoP\x01ZMgoogle.golang.org/genproto/googleapis/ads/searchads360/v0/resources;resources\xa2\x02\x07GASA360\xaa\x02$Google.Ads.SearchAds360.V0.Resources\xca\x02$Google\\Ads\\SearchAds360\\V0\\Resources\xea\x02(Google::Ads::SearchAds360::V0::Resourcesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.ads.searchads360.v0.resources.ad_group_bid_modifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.google.ads.searchads360.v0.resourcesB\027AdGroupBidModifierProtoP\001ZMgoogle.golang.org/genproto/googleapis/ads/searchads360/v0/resources;resources\242\002\007GASA360\252\002$Google.Ads.SearchAds360.V0.Resources\312\002$Google\\Ads\\SearchAds360\\V0\\Resources\352\002(Google::Ads::SearchAds360::V0::Resources'
  _globals['_ADGROUPBIDMODIFIER'].fields_by_name['resource_name']._loaded_options = None
  _globals['_ADGROUPBIDMODIFIER'].fields_by_name['resource_name']._serialized_options = b'\340A\005\372A0\n.searchads360.googleapis.com/AdGroupBidModifier'
  _globals['_ADGROUPBIDMODIFIER'].fields_by_name['device']._loaded_options = None
  _globals['_ADGROUPBIDMODIFIER'].fields_by_name['device']._serialized_options = b'\340A\005'
  _globals['_ADGROUPBIDMODIFIER']._loaded_options = None
  _globals['_ADGROUPBIDMODIFIER']._serialized_options = b'\352Az\n.searchads360.googleapis.com/AdGroupBidModifier\022Hcustomers/{customer_id}/adGroupBidModifiers/{ad_group_id}~{criterion_id}'
  _globals['_ADGROUPBIDMODIFIER']._serialized_start=217
  _globals['_ADGROUPBIDMODIFIER']._serialized_end=570
# @@protoc_insertion_point(module_scope)
