"""
    ELEMENTS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elements_sdk
from elements_sdk.model.workspace_move_to_request import WorkspaceMoveToRequest


class TestWorkspaceMoveToRequest(unittest.TestCase):
    """WorkspaceMoveToRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceMoveToRequest(self):
        """Test WorkspaceMoveToRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspaceMoveToRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
