[project]
name = "lenlab"
dynamic = ["version", "description"]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: Apache Software License"]
authors = [{name = "Christoph Simon", email = "christoph.simon@kit.edu"}]
# 3.12 adds the type keyword and itertools.batched
requires-python = ">=3.12"
dependencies = [
    "attrs>=24.3.0",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "pyside6>=6.7",
]

[project.urls]
Home = "https://github.com/kalanzun/lenlab_mspm0"

[project.scripts]
lenlab = "lenlab.app.main:main"

[dependency-groups]
dev = [
    "pytest-repeat>=0.9.3",
    "pytest>=8.3.3",
    "coverage>=7.6.8",
    "notebook>=7.3.2",
]

[build-system]
requires = ["hatchling>=1.12.0,<2"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "workspace/lenlab_fw/version.h"
pattern = '#define VERSION "(?P<version>[^"]+)"'

[tool.uv]
cache-keys = [
    { file = "workspace/lenlab_fw/version.h" },
    { file = "pyproject.toml" },
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",  # isort
]

[tool.coverage.report]
omit = [
    "shibokensupport/*",
    "pyscript",
    "signature_bootstrap.py",
]
