[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "babbelfish"
description = "A framework for lightweight services"
authors = [
  { name = "Aljoscha Sander", email = "aljoscha@flucto.tech" },
  { name = "Felix Weiler-Detjen", email = "felix@flucto.tech" },
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "heisskleber>=1.1.0",
]

[tool.uv]
dev-dependencies = [
    "deptry>=0.20.0",
    "mypy>=1.11.2",
    "ruff>=0.6.8",
    "xdoctest>=1.2.0",
    "nox>=2024.4.15",
    "pytest>=8.3.3",
    "pytest-cov>=5.0.0",
    "coverage[toml]>=7.6.1",
    "pytest-asyncio>=0.24.0",
    "pre-commit>=4.0.1",
]
package = true

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_context = true
exclude = ["tests/*", "^test_*\\.py"]

[tool.ruff]
target-version = "py39"
line-length = 120
fix = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "E501",   # LineTooLong
  "E731",   # DoNotAssignLambda
  "A001",   #
  "D100",   # Missing module docstring
  "D104",   # Missing package docstring
  "D107",   # Missing __init__ docstring
  "ANN101", # Deprecated and stupid self annotation
  "ANN401", # Dynamically typed annotation
  "FA102",  # Missing from __future__ import annotations
  "FBT001", # boolean style argument in function definition
  "FBT002", # boolean style argument in function definition
  "ARG002", # Unused kwargs
  "TD002",
  "TD003",
  "FIX002",
  "COM812",
  "ISC001",
  "ARG001",
  "INP001"
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "D", "T201", "PLR2", "SLF001", "ANN"]
"bin/*" = [
    "ERA001", # Found commented-out code
]


[tool.hatch]
version.source = "vcs"
version.path = "src/babbelfish/__init__.py"

[tool.hatch.envs.default]
features = ["test"]
scripts.test = "pytest {args}"
