[project]
name = "xmrig-api"
version = "0.2.4"
authors = [
  { name="hreikin", email="hreikin@gmail.com" },
]
description = "Allows interacting with the XMRig API."
readme = "docs/README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "mkdocs-material",
    "mkdocstrings[python]",
    "requests",
    "SQLAlchemy",
]

[project.urls]
Homepage = "https://github.com/hreikin/xmrig-api"
Issues = "https://github.com/hreikin/xmrig-api/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["xmrig"]