[build-system]
requires = [
    'setuptools',
]
build-backend = 'setuptools.build_meta'

[project]
name = 'pyutil-cfg'
version = '0.1.0'
dependencies = [
    'tomli==2.2.1; python_version < "3.11"',
    'typing-extensions==4.12.2; python_version < "3.11"',
]
authors = [
    {name = 'Chuan-Heng Hsiao', email = 'hsiao.chuanheng@gmail.com'},
]
description = 'python util for cfg (configurations)'
readme = 'README.md'
license = {file = 'LICENSE'}
keywords = [
]
classifiers = [
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
]
requires-python = ">= 3.10"

[project.urls]
# Homepage      = ''
# Documentation = ''
# Repository    = ''
# 'Bug Tracker' = ''
# Changelog = ''

[project.scripts]

[tool.setuptools.packages.find]
exclude = [
    'tests*',
]

[tool.flake8]
max-line-length = 100
extend-ignore = [
    # See https://github.com/PyCQA/pycodestyle/issues/373
    'E203',
]
exclude = [
    '.git',
    '__pycache__',
    'pyutil_cfg/__init__.py',
    '.cc',
    '.github',
]
