[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seizyml"
version = "0.1.0"
description = "A CLI tool for seizure detection using interpretable ML"
authors = [{ name = "Pantelis Antonoudiou", email = "pantelis.antonoudiou@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9, <3.10"
dependencies = [
    "appdirs==1.4.4",
    "bottleneck==1.3.5",
    "certifi==2023.7.22",
    "cffi==1.15.1",
    "click==8.1.6",
    "colorama==0.4.6",
    "cryptography==41.0.2",
    "cycler==0.11.0",
    "exceptiongroup==1.0.4",
    "fonttools==4.25.0",
    "idna==3.4",
    "joblib==1.2.0",
    "kiwisolver==1.4.4",
    "matplotlib==3.5.0",
    "numba==0.57.0",
    "numexpr==2.8.4",
    "numpy==1.24.3",
    "packaging==23.0",
    "pandas==1.5.3",
    "pillow==9.4.0",
    "pluggy==1.0.0",
    "pooch==1.4.0",
    "pycparser==2.21",
    "pyopenssl==23.2.0",
    "pyparsing==3.0.9",
    "PyQt5==5.15.7",
    "pytest==7.4.0",
    "python-dateutil==2.8.2",
    "pytz==2022.7",
    "requests==2.31.0",
    "scikit-learn==1.2.1",
    "scipy==1.10.1",
    "setuptools==68.0.0",
    "six==1.16.0",
    "tables==3.8",
    "threadpoolctl==2.2.0",
    "toml==0.10.2",
    "tornado==6.3.2",
    "tqdm==4.65.0",
    "urllib3==1.26.16",
    "pick==2.2.0",
    "pyyaml==6.0.1",
    "windows-curses==2.3.1"
]

[project.urls]
Homepage = "https://github.com/neurosimata/seizy_ml"
Repository = "https://github.com/neurosimata/seizy_ml"

[project.scripts]
seizyml = "seizyml.cli:cli_entry_point"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
license-files = [] 