"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 28, 1, '', 'google/cloud/filestore/v1/cloud_filestore_service.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.common import operation_metadata_pb2 as google_dot_cloud_dot_common_dot_operation__metadata__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7google/cloud/filestore/v1/cloud_filestore_service.proto\x12\x19google.cloud.filestore.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a,google/cloud/common/operation_metadata.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto"\x80\x03\n\rNetworkConfig\x12\x0f\n\x07network\x18\x01 \x01(\t\x12C\n\x05modes\x18\x03 \x03(\x0e24.google.cloud.filestore.v1.NetworkConfig.AddressMode\x12\x19\n\x11reserved_ip_range\x18\x04 \x01(\t\x12\x19\n\x0cip_addresses\x18\x05 \x03(\tB\x03\xe0A\x03\x12J\n\x0cconnect_mode\x18\x06 \x01(\x0e24.google.cloud.filestore.v1.NetworkConfig.ConnectMode":\n\x0bAddressMode\x12\x1c\n\x18ADDRESS_MODE_UNSPECIFIED\x10\x00\x12\r\n\tMODE_IPV4\x10\x01"[\n\x0bConnectMode\x12\x1c\n\x18CONNECT_MODE_UNSPECIFIED\x10\x00\x12\x12\n\x0eDIRECT_PEERING\x10\x01\x12\x1a\n\x16PRIVATE_SERVICE_ACCESS\x10\x02"\xc1\x01\n\x0fFileShareConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bcapacity_gb\x18\x02 \x01(\x03\x128\n\rsource_backup\x18\x08 \x01(\tB\x1f\xfaA\x1c\n\x1afile.googleapis.com/BackupH\x00\x12G\n\x12nfs_export_options\x18\x07 \x03(\x0b2+.google.cloud.filestore.v1.NfsExportOptionsB\x08\n\x06source"\xfd\x02\n\x10NfsExportOptions\x12\x11\n\tip_ranges\x18\x01 \x03(\t\x12K\n\x0baccess_mode\x18\x02 \x01(\x0e26.google.cloud.filestore.v1.NfsExportOptions.AccessMode\x12K\n\x0bsquash_mode\x18\x03 \x01(\x0e26.google.cloud.filestore.v1.NfsExportOptions.SquashMode\x12\x10\n\x08anon_uid\x18\x04 \x01(\x03\x12\x10\n\x08anon_gid\x18\x05 \x01(\x03"H\n\nAccessMode\x12\x1b\n\x17ACCESS_MODE_UNSPECIFIED\x10\x00\x12\r\n\tREAD_ONLY\x10\x01\x12\x0e\n\nREAD_WRITE\x10\x02"N\n\nSquashMode\x12\x1b\n\x17SQUASH_MODE_UNSPECIFIED\x10\x00\x12\x12\n\x0eNO_ROOT_SQUASH\x10\x01\x12\x0f\n\x0bROOT_SQUASH\x10\x02"\xa5\t\n\x08Instance\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x13\n\x0bdescription\x18\x02 \x01(\t\x12=\n\x05state\x18\x05 \x01(\x0e2).google.cloud.filestore.v1.Instance.StateB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x06 \x01(\tB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x07 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x126\n\x04tier\x18\x08 \x01(\x0e2(.google.cloud.filestore.v1.Instance.Tier\x12?\n\x06labels\x18\t \x03(\x0b2/.google.cloud.filestore.v1.Instance.LabelsEntry\x12?\n\x0bfile_shares\x18\n \x03(\x0b2*.google.cloud.filestore.v1.FileShareConfig\x12:\n\x08networks\x18\x0b \x03(\x0b2(.google.cloud.filestore.v1.NetworkConfig\x12\x0c\n\x04etag\x18\x0c \x01(\t\x126\n\rsatisfies_pzs\x18\r \x01(\x0b2\x1a.google.protobuf.BoolValueB\x03\xe0A\x03\x12\x1a\n\rsatisfies_pzi\x18\x12 \x01(\x08B\x03\xe0A\x03\x12\x14\n\x0ckms_key_name\x18\x0e \x01(\t\x12U\n\x12suspension_reasons\x18\x0f \x03(\x0e24.google.cloud.filestore.v1.Instance.SuspensionReasonB\x03\xe0A\x03\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"\xaa\x01\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\t\n\x05READY\x10\x02\x12\r\n\tREPAIRING\x10\x03\x12\x0c\n\x08DELETING\x10\x04\x12\t\n\x05ERROR\x10\x06\x12\r\n\tRESTORING\x10\x07\x12\r\n\tSUSPENDED\x10\x08\x12\x0e\n\nSUSPENDING\x10\t\x12\x0c\n\x08RESUMING\x10\n\x12\r\n\tREVERTING\x10\x0c"\x92\x01\n\x04Tier\x12\x14\n\x10TIER_UNSPECIFIED\x10\x00\x12\x0c\n\x08STANDARD\x10\x01\x12\x0b\n\x07PREMIUM\x10\x02\x12\r\n\tBASIC_HDD\x10\x03\x12\r\n\tBASIC_SSD\x10\x04\x12\x12\n\x0eHIGH_SCALE_SSD\x10\x05\x12\x0e\n\nENTERPRISE\x10\x06\x12\t\n\x05ZONAL\x10\x07\x12\x0c\n\x08REGIONAL\x10\x08"H\n\x10SuspensionReason\x12!\n\x1dSUSPENSION_REASON_UNSPECIFIED\x10\x00\x12\x11\n\rKMS_KEY_ISSUE\x10\x01:_\xeaA\\\n\x1cfile.googleapis.com/Instance\x12<projects/{project}/locations/{location}/instances/{instance}"\xa8\x01\n\x15CreateInstanceRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x18\n\x0binstance_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12:\n\x08instance\x18\x03 \x01(\x0b2#.google.cloud.filestore.v1.InstanceB\x03\xe0A\x02"H\n\x12GetInstanceRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance"\x7f\n\x15UpdateInstanceRequest\x12/\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMask\x125\n\x08instance\x18\x02 \x01(\x0b2#.google.cloud.filestore.v1.Instance"\xa9\x01\n\x16RestoreInstanceRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x17\n\nfile_share\x18\x02 \x01(\tB\x03\xe0A\x02\x128\n\rsource_backup\x18\x03 \x01(\tB\x1f\xfaA\x1c\n\x1afile.googleapis.com/BackupH\x00B\x08\n\x06source"l\n\x15RevertInstanceRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x1f\n\x12target_snapshot_id\x18\x02 \x01(\tB\x03\xe0A\x02"Z\n\x15DeleteInstanceRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\r\n\x05force\x18\x02 \x01(\x08"\x9a\x01\n\x14ListInstancesRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t"}\n\x15ListInstancesResponse\x126\n\tinstances\x18\x01 \x03(\x0b2#.google.cloud.filestore.v1.Instance\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xf8\x03\n\x08Snapshot\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x13\n\x0bdescription\x18\x02 \x01(\t\x12=\n\x05state\x18\x03 \x01(\x0e2).google.cloud.filestore.v1.Snapshot.StateB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12?\n\x06labels\x18\x05 \x03(\x0b2/.google.cloud.filestore.v1.Snapshot.LabelsEntry\x12"\n\x15filesystem_used_bytes\x18\x06 \x01(\x03B\x03\xe0A\x03\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"E\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0c\n\x08DELETING\x10\x03:t\xeaAq\n\x1cfile.googleapis.com/Snapshot\x12Qprojects/{project}/locations/{location}/instances/{instance}/snapshots/{snapshot}"\xa3\x01\n\x15CreateSnapshotRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x18\n\x0bsnapshot_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12:\n\x08snapshot\x18\x03 \x01(\x0b2#.google.cloud.filestore.v1.SnapshotB\x03\xe0A\x02"H\n\x12GetSnapshotRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Snapshot"K\n\x15DeleteSnapshotRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Snapshot"\x89\x01\n\x15UpdateSnapshotRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12:\n\x08snapshot\x18\x02 \x01(\x0b2#.google.cloud.filestore.v1.SnapshotB\x03\xe0A\x02"\x95\x01\n\x14ListSnapshotsRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t"h\n\x15ListSnapshotsResponse\x126\n\tsnapshots\x18\x01 \x03(\x0b2#.google.cloud.filestore.v1.Snapshot\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xb1\x06\n\x06Backup\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x13\n\x0bdescription\x18\x02 \x01(\t\x12;\n\x05state\x18\x03 \x01(\x0e2\'.google.cloud.filestore.v1.Backup.StateB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12=\n\x06labels\x18\x05 \x03(\x0b2-.google.cloud.filestore.v1.Backup.LabelsEntry\x12\x18\n\x0bcapacity_gb\x18\x06 \x01(\x03B\x03\xe0A\x03\x12\x1a\n\rstorage_bytes\x18\x07 \x01(\x03B\x03\xe0A\x03\x12:\n\x0fsource_instance\x18\x08 \x01(\tB!\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x19\n\x11source_file_share\x18\t \x01(\t\x12K\n\x14source_instance_tier\x18\n \x01(\x0e2(.google.cloud.filestore.v1.Instance.TierB\x03\xe0A\x03\x12\x1b\n\x0edownload_bytes\x18\x0b \x01(\x03B\x03\xe0A\x03\x126\n\rsatisfies_pzs\x18\x0c \x01(\x0b2\x1a.google.protobuf.BoolValueB\x03\xe0A\x03\x12\x1a\n\rsatisfies_pzi\x18\x0e \x01(\x08B\x03\xe0A\x03\x12\x14\n\x07kms_key\x18\r \x01(\tB\x03\xe0A\x05\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"b\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\x0e\n\nFINALIZING\x10\x02\x12\t\n\x05READY\x10\x03\x12\x0c\n\x08DELETING\x10\x04\x12\x0b\n\x07INVALID\x10\x05:Y\xeaAV\n\x1afile.googleapis.com/Backup\x128projects/{project}/locations/{location}/backups/{backup}"\xa0\x01\n\x13CreateBackupRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x126\n\x06backup\x18\x02 \x01(\x0b2!.google.cloud.filestore.v1.BackupB\x03\xe0A\x02\x12\x16\n\tbackup_id\x18\x03 \x01(\tB\x03\xe0A\x02"G\n\x13DeleteBackupRequest\x120\n\x04name\x18\x01 \x01(\tB"\xe0A\x02\xfaA\x1c\n\x1afile.googleapis.com/Backup"\x83\x01\n\x13UpdateBackupRequest\x126\n\x06backup\x18\x01 \x01(\x0b2!.google.cloud.filestore.v1.BackupB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"D\n\x10GetBackupRequest\x120\n\x04name\x18\x01 \x01(\tB"\xe0A\x02\xfaA\x1c\n\x1afile.googleapis.com/Backup"\x98\x01\n\x12ListBackupsRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t"w\n\x13ListBackupsResponse\x122\n\x07backups\x18\x01 \x03(\x0b2!.google.cloud.filestore.v1.Backup\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t2\xa4\x1d\n\x15CloudFilestoreManager\x12\xb2\x01\n\rListInstances\x12/.google.cloud.filestore.v1.ListInstancesRequest\x1a0.google.cloud.filestore.v1.ListInstancesResponse">\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1/{parent=projects/*/locations/*}/instances\x12\x9f\x01\n\x0bGetInstance\x12-.google.cloud.filestore.v1.GetInstanceRequest\x1a#.google.cloud.filestore.v1.Instance"<\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1/{name=projects/*/locations/*/instances/*}\x12\xf5\x01\n\x0eCreateInstance\x120.google.cloud.filestore.v1.CreateInstanceRequest\x1a\x1d.google.longrunning.Operation"\x91\x01\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\xdaA\x1bparent,instance,instance_id\x82\xd3\xe4\x93\x029"-/v1/{parent=projects/*/locations/*}/instances:\x08instance\x12\xf7\x01\n\x0eUpdateInstance\x120.google.cloud.filestore.v1.UpdateInstanceRequest\x1a\x1d.google.longrunning.Operation"\x93\x01\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\xdaA\x14instance,update_mask\x82\xd3\xe4\x93\x02B26/v1/{instance.name=projects/*/locations/*/instances/*}:\x08instance\x12\xd9\x01\n\x0fRestoreInstance\x121.google.cloud.filestore.v1.RestoreInstanceRequest\x1a\x1d.google.longrunning.Operation"t\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\x82\xd3\xe4\x93\x02:"5/v1/{name=projects/*/locations/*/instances/*}:restore:\x01*\x12\xd6\x01\n\x0eRevertInstance\x120.google.cloud.filestore.v1.RevertInstanceRequest\x1a\x1d.google.longrunning.Operation"s\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\x82\xd3\xe4\x93\x029"4/v1/{name=projects/*/locations/*/instances/*}:revert:\x01*\x12\xe0\x01\n\x0eDeleteInstance\x120.google.cloud.filestore.v1.DeleteInstanceRequest\x1a\x1d.google.longrunning.Operation"}\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v1/{name=projects/*/locations/*/instances/*}\x12\xbe\x01\n\rListSnapshots\x12/.google.cloud.filestore.v1.ListSnapshotsRequest\x1a0.google.cloud.filestore.v1.ListSnapshotsResponse"J\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v1/{parent=projects/*/locations/*/instances/*}/snapshots\x12\xab\x01\n\x0bGetSnapshot\x12-.google.cloud.filestore.v1.GetSnapshotRequest\x1a#.google.cloud.filestore.v1.Snapshot"H\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v1/{name=projects/*/locations/*/instances/*/snapshots/*}\x12\x81\x02\n\x0eCreateSnapshot\x120.google.cloud.filestore.v1.CreateSnapshotRequest\x1a\x1d.google.longrunning.Operation"\x9d\x01\xcaA1\n\x08Snapshot\x12%google.cloud.common.OperationMetadata\xdaA\x1bparent,snapshot,snapshot_id\x82\xd3\xe4\x93\x02E"9/v1/{parent=projects/*/locations/*/instances/*}/snapshots:\x08snapshot\x12\xed\x01\n\x0eDeleteSnapshot\x120.google.cloud.filestore.v1.DeleteSnapshotRequest\x1a\x1d.google.longrunning.Operation"\x89\x01\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02;*9/v1/{name=projects/*/locations/*/instances/*/snapshots/*}\x12\x83\x02\n\x0eUpdateSnapshot\x120.google.cloud.filestore.v1.UpdateSnapshotRequest\x1a\x1d.google.longrunning.Operation"\x9f\x01\xcaA1\n\x08Snapshot\x12%google.cloud.common.OperationMetadata\xdaA\x14snapshot,update_mask\x82\xd3\xe4\x93\x02N2B/v1/{snapshot.name=projects/*/locations/*/instances/*/snapshots/*}:\x08snapshot\x12\xaa\x01\n\x0bListBackups\x12-.google.cloud.filestore.v1.ListBackupsRequest\x1a..google.cloud.filestore.v1.ListBackupsResponse"<\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/v1/{parent=projects/*/locations/*}/backups\x12\x97\x01\n\tGetBackup\x12+.google.cloud.filestore.v1.GetBackupRequest\x1a!.google.cloud.filestore.v1.Backup":\xdaA\x04name\x82\xd3\xe4\x93\x02-\x12+/v1/{name=projects/*/locations/*/backups/*}\x12\xe7\x01\n\x0cCreateBackup\x12..google.cloud.filestore.v1.CreateBackupRequest\x1a\x1d.google.longrunning.Operation"\x87\x01\xcaA/\n\x06Backup\x12%google.cloud.common.OperationMetadata\xdaA\x17parent,backup,backup_id\x82\xd3\xe4\x93\x025"+/v1/{parent=projects/*/locations/*}/backups:\x06backup\x12\xda\x01\n\x0cDeleteBackup\x12..google.cloud.filestore.v1.DeleteBackupRequest\x1a\x1d.google.longrunning.Operation"{\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02-*+/v1/{name=projects/*/locations/*/backups/*}\x12\xe9\x01\n\x0cUpdateBackup\x12..google.cloud.filestore.v1.UpdateBackupRequest\x1a\x1d.google.longrunning.Operation"\x89\x01\xcaA/\n\x06Backup\x12%google.cloud.common.OperationMetadata\xdaA\x12backup,update_mask\x82\xd3\xe4\x93\x02<22/v1/{backup.name=projects/*/locations/*/backups/*}:\x06backup\x1aG\xcaA\x13file.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xb2\x01\n\x1dcom.google.cloud.filestore.v1B\x1aCloudFilestoreServiceProtoP\x01Z;cloud.google.com/go/filestore/apiv1/filestorepb;filestorepb\xaa\x02\x19Google.Cloud.Filestore.V1\xca\x02\x19Google\\Cloud\\Filestore\\V1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.filestore.v1.cloud_filestore_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1dcom.google.cloud.filestore.v1B\x1aCloudFilestoreServiceProtoP\x01Z;cloud.google.com/go/filestore/apiv1/filestorepb;filestorepb\xaa\x02\x19Google.Cloud.Filestore.V1\xca\x02\x19Google\\Cloud\\Filestore\\V1'
    _globals['_NETWORKCONFIG'].fields_by_name['ip_addresses']._loaded_options = None
    _globals['_NETWORKCONFIG'].fields_by_name['ip_addresses']._serialized_options = b'\xe0A\x03'
    _globals['_FILESHARECONFIG'].fields_by_name['source_backup']._loaded_options = None
    _globals['_FILESHARECONFIG'].fields_by_name['source_backup']._serialized_options = b'\xfaA\x1c\n\x1afile.googleapis.com/Backup'
    _globals['_INSTANCE_LABELSENTRY']._loaded_options = None
    _globals['_INSTANCE_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_INSTANCE'].fields_by_name['name']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['state']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['status_message']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['create_time']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['satisfies_pzs']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['satisfies_pzs']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['satisfies_pzi']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['satisfies_pzi']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['suspension_reasons']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['suspension_reasons']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE']._loaded_options = None
    _globals['_INSTANCE']._serialized_options = b'\xeaA\\\n\x1cfile.googleapis.com/Instance\x12<projects/{project}/locations/{location}/instances/{instance}'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x02'
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['file_share']._loaded_options = None
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['file_share']._serialized_options = b'\xe0A\x02'
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['source_backup']._loaded_options = None
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['source_backup']._serialized_options = b'\xfaA\x1c\n\x1afile.googleapis.com/Backup'
    _globals['_REVERTINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_REVERTINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_REVERTINSTANCEREQUEST'].fields_by_name['target_snapshot_id']._loaded_options = None
    _globals['_REVERTINSTANCEREQUEST'].fields_by_name['target_snapshot_id']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_SNAPSHOT_LABELSENTRY']._loaded_options = None
    _globals['_SNAPSHOT_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_SNAPSHOT'].fields_by_name['name']._loaded_options = None
    _globals['_SNAPSHOT'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_SNAPSHOT'].fields_by_name['state']._loaded_options = None
    _globals['_SNAPSHOT'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_SNAPSHOT'].fields_by_name['create_time']._loaded_options = None
    _globals['_SNAPSHOT'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_SNAPSHOT'].fields_by_name['filesystem_used_bytes']._loaded_options = None
    _globals['_SNAPSHOT'].fields_by_name['filesystem_used_bytes']._serialized_options = b'\xe0A\x03'
    _globals['_SNAPSHOT']._loaded_options = None
    _globals['_SNAPSHOT']._serialized_options = b'\xeaAq\n\x1cfile.googleapis.com/Snapshot\x12Qprojects/{project}/locations/{location}/instances/{instance}/snapshots/{snapshot}'
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['snapshot_id']._loaded_options = None
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['snapshot_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['snapshot']._loaded_options = None
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['snapshot']._serialized_options = b'\xe0A\x02'
    _globals['_GETSNAPSHOTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSNAPSHOTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Snapshot'
    _globals['_DELETESNAPSHOTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESNAPSHOTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Snapshot'
    _globals['_UPDATESNAPSHOTREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATESNAPSHOTREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESNAPSHOTREQUEST'].fields_by_name['snapshot']._loaded_options = None
    _globals['_UPDATESNAPSHOTREQUEST'].fields_by_name['snapshot']._serialized_options = b'\xe0A\x02'
    _globals['_LISTSNAPSHOTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSNAPSHOTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_BACKUP_LABELSENTRY']._loaded_options = None
    _globals['_BACKUP_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_BACKUP'].fields_by_name['name']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['state']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['create_time']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['capacity_gb']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['capacity_gb']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['storage_bytes']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['storage_bytes']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['source_instance']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['source_instance']._serialized_options = b'\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_BACKUP'].fields_by_name['source_instance_tier']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['source_instance_tier']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['download_bytes']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['download_bytes']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['satisfies_pzs']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['satisfies_pzs']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['satisfies_pzi']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['satisfies_pzi']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['kms_key']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['kms_key']._serialized_options = b'\xe0A\x05'
    _globals['_BACKUP']._loaded_options = None
    _globals['_BACKUP']._serialized_options = b'\xeaAV\n\x1afile.googleapis.com/Backup\x128projects/{project}/locations/{location}/backups/{backup}'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup_id']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup_id']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1c\n\x1afile.googleapis.com/Backup'
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['backup']._loaded_options = None
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['backup']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_GETBACKUPREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETBACKUPREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1c\n\x1afile.googleapis.com/Backup'
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CLOUDFILESTOREMANAGER']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER']._serialized_options = b'\xcaA\x13file.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListInstances']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListInstances']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1/{parent=projects/*/locations/*}/instances'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetInstance']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1/{name=projects/*/locations/*/instances/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateInstance']._serialized_options = b'\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\xdaA\x1bparent,instance,instance_id\x82\xd3\xe4\x93\x029"-/v1/{parent=projects/*/locations/*}/instances:\x08instance'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateInstance']._serialized_options = b'\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\xdaA\x14instance,update_mask\x82\xd3\xe4\x93\x02B26/v1/{instance.name=projects/*/locations/*/instances/*}:\x08instance'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['RestoreInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['RestoreInstance']._serialized_options = b'\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\x82\xd3\xe4\x93\x02:"5/v1/{name=projects/*/locations/*/instances/*}:restore:\x01*'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['RevertInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['RevertInstance']._serialized_options = b'\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\x82\xd3\xe4\x93\x029"4/v1/{name=projects/*/locations/*/instances/*}:revert:\x01*'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteInstance']._serialized_options = b'\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v1/{name=projects/*/locations/*/instances/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListSnapshots']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListSnapshots']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v1/{parent=projects/*/locations/*/instances/*}/snapshots'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetSnapshot']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetSnapshot']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v1/{name=projects/*/locations/*/instances/*/snapshots/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateSnapshot']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateSnapshot']._serialized_options = b'\xcaA1\n\x08Snapshot\x12%google.cloud.common.OperationMetadata\xdaA\x1bparent,snapshot,snapshot_id\x82\xd3\xe4\x93\x02E"9/v1/{parent=projects/*/locations/*/instances/*}/snapshots:\x08snapshot'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteSnapshot']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteSnapshot']._serialized_options = b'\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02;*9/v1/{name=projects/*/locations/*/instances/*/snapshots/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateSnapshot']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateSnapshot']._serialized_options = b'\xcaA1\n\x08Snapshot\x12%google.cloud.common.OperationMetadata\xdaA\x14snapshot,update_mask\x82\xd3\xe4\x93\x02N2B/v1/{snapshot.name=projects/*/locations/*/instances/*/snapshots/*}:\x08snapshot'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListBackups']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListBackups']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02-\x12+/v1/{parent=projects/*/locations/*}/backups'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetBackup']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetBackup']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02-\x12+/v1/{name=projects/*/locations/*/backups/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateBackup']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateBackup']._serialized_options = b'\xcaA/\n\x06Backup\x12%google.cloud.common.OperationMetadata\xdaA\x17parent,backup,backup_id\x82\xd3\xe4\x93\x025"+/v1/{parent=projects/*/locations/*}/backups:\x06backup'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteBackup']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteBackup']._serialized_options = b'\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02-*+/v1/{name=projects/*/locations/*/backups/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateBackup']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateBackup']._serialized_options = b'\xcaA/\n\x06Backup\x12%google.cloud.common.OperationMetadata\xdaA\x12backup,update_mask\x82\xd3\xe4\x93\x02<22/v1/{backup.name=projects/*/locations/*/backups/*}:\x06backup'
    _globals['_NETWORKCONFIG']._serialized_start = 413
    _globals['_NETWORKCONFIG']._serialized_end = 797
    _globals['_NETWORKCONFIG_ADDRESSMODE']._serialized_start = 646
    _globals['_NETWORKCONFIG_ADDRESSMODE']._serialized_end = 704
    _globals['_NETWORKCONFIG_CONNECTMODE']._serialized_start = 706
    _globals['_NETWORKCONFIG_CONNECTMODE']._serialized_end = 797
    _globals['_FILESHARECONFIG']._serialized_start = 800
    _globals['_FILESHARECONFIG']._serialized_end = 993
    _globals['_NFSEXPORTOPTIONS']._serialized_start = 996
    _globals['_NFSEXPORTOPTIONS']._serialized_end = 1377
    _globals['_NFSEXPORTOPTIONS_ACCESSMODE']._serialized_start = 1225
    _globals['_NFSEXPORTOPTIONS_ACCESSMODE']._serialized_end = 1297
    _globals['_NFSEXPORTOPTIONS_SQUASHMODE']._serialized_start = 1299
    _globals['_NFSEXPORTOPTIONS_SQUASHMODE']._serialized_end = 1377
    _globals['_INSTANCE']._serialized_start = 1380
    _globals['_INSTANCE']._serialized_end = 2569
    _globals['_INSTANCE_LABELSENTRY']._serialized_start = 2031
    _globals['_INSTANCE_LABELSENTRY']._serialized_end = 2076
    _globals['_INSTANCE_STATE']._serialized_start = 2079
    _globals['_INSTANCE_STATE']._serialized_end = 2249
    _globals['_INSTANCE_TIER']._serialized_start = 2252
    _globals['_INSTANCE_TIER']._serialized_end = 2398
    _globals['_INSTANCE_SUSPENSIONREASON']._serialized_start = 2400
    _globals['_INSTANCE_SUSPENSIONREASON']._serialized_end = 2472
    _globals['_CREATEINSTANCEREQUEST']._serialized_start = 2572
    _globals['_CREATEINSTANCEREQUEST']._serialized_end = 2740
    _globals['_GETINSTANCEREQUEST']._serialized_start = 2742
    _globals['_GETINSTANCEREQUEST']._serialized_end = 2814
    _globals['_UPDATEINSTANCEREQUEST']._serialized_start = 2816
    _globals['_UPDATEINSTANCEREQUEST']._serialized_end = 2943
    _globals['_RESTOREINSTANCEREQUEST']._serialized_start = 2946
    _globals['_RESTOREINSTANCEREQUEST']._serialized_end = 3115
    _globals['_REVERTINSTANCEREQUEST']._serialized_start = 3117
    _globals['_REVERTINSTANCEREQUEST']._serialized_end = 3225
    _globals['_DELETEINSTANCEREQUEST']._serialized_start = 3227
    _globals['_DELETEINSTANCEREQUEST']._serialized_end = 3317
    _globals['_LISTINSTANCESREQUEST']._serialized_start = 3320
    _globals['_LISTINSTANCESREQUEST']._serialized_end = 3474
    _globals['_LISTINSTANCESRESPONSE']._serialized_start = 3476
    _globals['_LISTINSTANCESRESPONSE']._serialized_end = 3601
    _globals['_SNAPSHOT']._serialized_start = 3604
    _globals['_SNAPSHOT']._serialized_end = 4108
    _globals['_SNAPSHOT_LABELSENTRY']._serialized_start = 2031
    _globals['_SNAPSHOT_LABELSENTRY']._serialized_end = 2076
    _globals['_SNAPSHOT_STATE']._serialized_start = 3921
    _globals['_SNAPSHOT_STATE']._serialized_end = 3990
    _globals['_CREATESNAPSHOTREQUEST']._serialized_start = 4111
    _globals['_CREATESNAPSHOTREQUEST']._serialized_end = 4274
    _globals['_GETSNAPSHOTREQUEST']._serialized_start = 4276
    _globals['_GETSNAPSHOTREQUEST']._serialized_end = 4348
    _globals['_DELETESNAPSHOTREQUEST']._serialized_start = 4350
    _globals['_DELETESNAPSHOTREQUEST']._serialized_end = 4425
    _globals['_UPDATESNAPSHOTREQUEST']._serialized_start = 4428
    _globals['_UPDATESNAPSHOTREQUEST']._serialized_end = 4565
    _globals['_LISTSNAPSHOTSREQUEST']._serialized_start = 4568
    _globals['_LISTSNAPSHOTSREQUEST']._serialized_end = 4717
    _globals['_LISTSNAPSHOTSRESPONSE']._serialized_start = 4719
    _globals['_LISTSNAPSHOTSRESPONSE']._serialized_end = 4823
    _globals['_BACKUP']._serialized_start = 4826
    _globals['_BACKUP']._serialized_end = 5643
    _globals['_BACKUP_LABELSENTRY']._serialized_start = 2031
    _globals['_BACKUP_LABELSENTRY']._serialized_end = 2076
    _globals['_BACKUP_STATE']._serialized_start = 5454
    _globals['_BACKUP_STATE']._serialized_end = 5552
    _globals['_CREATEBACKUPREQUEST']._serialized_start = 5646
    _globals['_CREATEBACKUPREQUEST']._serialized_end = 5806
    _globals['_DELETEBACKUPREQUEST']._serialized_start = 5808
    _globals['_DELETEBACKUPREQUEST']._serialized_end = 5879
    _globals['_UPDATEBACKUPREQUEST']._serialized_start = 5882
    _globals['_UPDATEBACKUPREQUEST']._serialized_end = 6013
    _globals['_GETBACKUPREQUEST']._serialized_start = 6015
    _globals['_GETBACKUPREQUEST']._serialized_end = 6083
    _globals['_LISTBACKUPSREQUEST']._serialized_start = 6086
    _globals['_LISTBACKUPSREQUEST']._serialized_end = 6238
    _globals['_LISTBACKUPSRESPONSE']._serialized_start = 6240
    _globals['_LISTBACKUPSRESPONSE']._serialized_end = 6359
    _globals['_CLOUDFILESTOREMANAGER']._serialized_start = 6362
    _globals['_CLOUDFILESTOREMANAGER']._serialized_end = 10110