[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "dagster-db"
version = "0.1.10"
description = "Dagster IO managers and type handlers for databases"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [ "dagster>=1.9.11", "dagster-duckdb>=0.25.11", "dagster-gcp>=0.25.11", "dagster-pandas>=0.25.11", "dagster-polars>=0.25.11",]
classifiers = [ "Development Status :: 3 - Alpha", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.13",]
[[project.authors]]
name = "James Blackwell"
email = "33688964+j-blackwell@users.noreply.github.com"

[project.license]
file = "LICENSE"

[project.urls]
Source = "https://github.com/j-blackwell/dagster-db"

[project.scripts]
bump = "version:bump"

[tool.hatch.build.targets.wheel]
packages = [ "dagster_db",]
