[project]
name = "jinafetch"
version = "0.3.0"
description = "CLI tool to fetch and save web content as Markdown files using Jina Reader API. Handles authentication and provides rich terminal output."
readme = "README.md"

classifiers = [
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.12"
dependencies = [
    "appdirs>=1.4.4,<2.0",
    "httpx>=0.28.1",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
    "typer>=0.15.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.5",
]

[project.urls]
repository = "https://github.com/engwerda/jinafetch"
homepage = "https://github.com/engwerda/jinafetch"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "C4"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[project.scripts]
jinafetch = "main:app"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv]
dev-dependencies = [
    "ruff"
]
