# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  PACKAGE_NAME: dagster_db

permissions:
  contents: 'write'
  id-token: 'write'


jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Get version
        run: |-
          git fetch --tags --force
          echo "VERSION=$(uvx --from=dunamai dunamai from any --no-metadata --style pep440)" >> "$GITHUB_ENV"

      - name: Set version
        run: |-
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version ${{env.VERSION}}
          git add pyproject.toml
          git commit -m "update version to tag ${{env.VERSION}}"
          git push

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish ./dist/${{env.PACKAGE_NAME}}-${{env.VERSION}}* --token ${{secrets.UV_PUBLISH_TOKEN}}
