[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sowing"
version = "0.1.0"
authors = [
    { name="Mattéo Delabre", email="git.matteo@delab.re" },
]
description = "sowing"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
]
dependencies = [
    "immutables",
]

[project.scripts]
sowing = "sowing.cli.__main__:run"

[project.urls]
"Homepage" = "https://github.com/UdeM-LBIT/sowing"
"Bug Tracker" = "https://github.com/UdeM-LBIT/sowing/issues"

[tool.hatch.build]
sources = ["src"]
only-include = ["src"]

[tool.hatch.envs.dev]
dependencies = [
    "pytest",
    "black",
    "ruff",
]

[tool.hatch.envs.dev.scripts]
test = "pytest --exitfirst"
test-verbose = "pytest --exitfirst -vv"
format = "black ."
format-check = "black --check ."
lint = "ruff check ."

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
