[project]
name = "{{folder_name}}"
version = "0.4.0"
description = "Power up your cropios with {{folder_name}}"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "cropioai[tools]>=0.2.0"
]

[tool.cropioai]
type = "tool"
