[tool.poetry]
name = "pnorm"
version = "0.0.1"
description = "(Postgres) Not an ORM"
authors = ["Alex Rudolph <alex3rudolph@gmail.com>"]
readme = "README.md"
repository = "https://github.com/alrudolph/pnorm"

[tool.poetry.dependencies]
python = "^3.11"
rcheck = "^0.0.10"
pydantic = "^2.5.2"
psycopg = {version = "^3.2.1", extras = ["binary"]}
opentelemetry-sdk = "^1.29.0"

[tool.poetry.group.dev.dependencies]
isort = "^5.13.0"
black = "^24.3.0"
python-dotenv = "^1.0.0"
mypy = "^1.8.0"
types-psycopg2 = "^2.9.21.20240118"
pytest = "^8.3.4"
pytest-asyncio = "^0.25.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
