[project]
name = "tibber-pulse-sml-debugger"
version = "1.0.3"
description = "A tiny python based CLI application to see the data, that was recorded and send by your Tibber Pulse IR to your Tibber Pulse Bridge."
authors = [
    { name = "wh0ami", email = "wh0ami@noreply.codeberg.org" }
]
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
repository = "https://codeberg.org/wh0ami/tibber-pulse-sml-debugger"
keywords = [
    "SML",
    "Tibber",
    "energy",
    "electric",
    "pulse",
    "debug"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "requests>=2.32.3",
    "smllib>=1.5",
]

[project.scripts]
tibber-pulse-sml-debugger = "tibber_pulse_sml_debugger.main:main"
tpsd = "tibber_pulse_sml_debugger.main:main"

[project.urls]
Homepage = "https://codeberg.org/wh0ami/tibber-pulse-sml-debugger"
Documentation = "https://codeberg.org/wh0ami/tibber-pulse-sml-debugger/src/branch/master/README.md"
Repository = "https://codeberg.org/wh0ami/tibber-pulse-sml-debugger"
Issues = "https://codeberg.org/wh0ami/tibber-pulse-sml-debugger/issues"

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.9.5",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "ALL",
]
ignore = [
    "EM", # flake8-errmsg
    "EXE", # flake8-executable
    "ANN", # flake8-annotations
    "FBT", # flake8-boolean-trap
    "FA", # future-required-type-annotation
    "TD", # flake8-todos
    # tryceratops
    "TRY003", # Avoid specifying long messages outside the exception class
    # Pylint-Refactor
    "PLR2004", # Magic value used in comparison, consider replacing {value} with a constant variable
    # pydocstyle
    "D100", # Missing docstring in public module
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring summary should start at the first line
    # Perflint
    "PERF203", # We must run the construct like that in this application
]
