[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["promptpal"]

[project]
name = "promptpal"
version = "1.3.10"
description = "Python based tool for improved LLM interations using the OpenAI API package."
readme = "README.md"
authors = [
    {name = "Matt Jenior", email = "mattjenior@gmail.com"}
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "openai >= 1.59.0"

]
