[tool.poetry]
name = "tesla-client"
version = "4.0.2"
description = ""
authors = ["Jimming Cheng <jimming@gmail.com>"]
readme = "README.md"
packages = [{include = "tesla_client"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
types-mock = "^5.1.0.20240106"
types-requests = "^2.31.0.20240125"
types-setuptools = "^69.0.0.20240125"
mypy = "^1.8.0"
mock = "^5.1.0"
requests-mock = "^1.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
