[project]
name = "tono"
version = "0.1.3"
description = "A framework for building autonomous AI agents"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "docstring-parser>=0.16",
    "httpx>=0.27.2",
    "python-dotenv>=1.0.1",
    "rich>=13.9.2",
    "typer>=0.12.5",
]

[tool.uv]
package = true
override-dependencies = ["greenlet==3.1.0"]
dev-dependencies = ["mypy>=1.13.0", "pytest>=8.3.3"]

[tool.pytest.ini_options]
minversion = "8.0"

[project.scripts]
tono = "tono.cli:app"

[project.optional-dependencies]
openai = ["openai>=1.52.0"]
anthropic = ["anthropic>=0.37.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/tono"]
exclude = ["src/tono/tests", "docs"]

[tool.mypy]
disable_error_code = "import-untyped"

[[tool.mypy.overrides]]
module = [
    "openai.*",
    "anthropic.*",
    "rich.*",
    "typer.*",
    "httpx.*",
    "docstring_parser.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["tests.*"]
ignore_errors = true
