[tool.poetry]
name = "colorex-py"
version = "0.1.4"
description = "colorex-py is a simple and flexible Python Module that provides an easy way to style your terminal output with color and text formatting. With support for both RGB and HEX color codes, as well as text styles like bold, italic, underline, strikethrough, and more, it makes your terminal applications visually more appealing and readable."
authors = ["LunaStev <lunastev@gurmstudios.com>"]
packages = [{ include = "colorex" }]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.5,<4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
