"""
biosim-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from biosim_client.api.biosim.models.omex_verify_workflow_input import OmexVerifyWorkflowInput


class TestOmexVerifyWorkflowInput(unittest.TestCase):
    """OmexVerifyWorkflowInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OmexVerifyWorkflowInput:
        """Test OmexVerifyWorkflowInput
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OmexVerifyWorkflowInput`
        """
        model = OmexVerifyWorkflowInput()
        if include_optional:
            return OmexVerifyWorkflowInput(
                source_omex = biosim_client.api.biosim.models.source_omex.SourceOmex(
                    name = '',
                    omex_s3_file = '', ),
                user_description = '',
                requested_simulators = [
                    biosim_client.api.biosim.models.biosim_simulator_spec.BiosimSimulatorSpec(
                        simulator = '',
                        version = '', )
                    ],
                include_outputs = True,
                rel_tol = 1.337,
                abs_tol = 1.337,
                observables = [
                    ''
                    ]
            )
        else:
            return OmexVerifyWorkflowInput(
                source_omex = biosim_client.api.biosim.models.source_omex.SourceOmex(
                    name = '',
                    omex_s3_file = '', ),
                user_description = '',
                requested_simulators = [
                    biosim_client.api.biosim.models.biosim_simulator_spec.BiosimSimulatorSpec(
                        simulator = '',
                        version = '', )
                    ],
                include_outputs = True,
                rel_tol = 1.337,
                abs_tol = 1.337,
        )
        """

    def testOmexVerifyWorkflowInput(self):
        """Test OmexVerifyWorkflowInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
