[package]
name = "rnode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rnode"
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.36", features = ["full"] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
futures = "0.3"
async-trait = "0.1"
pyo3 = { version = "0.20.0", features = ["extension-module"] }
pyo3-macros = "0.20.0"
pyo3-macros-backend = "0.20.0"
parking_lot = "0.12"
url = "2.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
num_cpus = "1.13"
crossbeam-queue = "0.3"
crossbeam-channel = "0.5"
rayon = "1.5"
