[build-system]
requires = [
  "setuptools>=64"
]
build-backend = "setuptools.build_meta"

[project]
name = "nwy"
description = "Tools to create large language model pipelines to process text."
authors = [
    {name = "Ati Sharma", email = "ati+noteworthy@agalmic.ltd"},
]
dynamic = ["version", "readme"]
requires-python = ">=3.11"
keywords = ["hy", "hylang", "utilities", "llm", "openai"]
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Lisp",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities"
]
dependencies = [
    "hy",
    "hyrule",
    "hyjinx[llm]",
    "pymupdf"
]

[project.urls]
Repository = "https://github.com/atisharma/noteworthy"

[tool.setuptools.dynamic]
readme = {file = "README.md", content-type = "text/markdown"}
version = {attr = "noteworthy.__version__"}

[tool.setuptools.package-data]
"*" = ["*.hy", "*.toml"]

[project.scripts]
pdf2md = "noteworthy.cli:pdftomd"
pdf2latex = "noteworthy.cli:pdftolatex"

# ... other project metadata fields as listed in:
#     https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
