[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flexible-datetime"
version = "1.0.10"
description = "Flexible datetime handling for Python"
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "arrow>=1.3.0",
    "pydantic>=2.10.6",
]

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Build Tools",
]

[dependency-groups]
dev = [
    "beanie>=1.29.0",
    "black>=25.1.0",
    "pytest>=8.3.4",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
