
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-07T11:36:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "33720089908a984bbb1bd0f83c997a4c53942c07",
 "version": "2025.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
