"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 28, 1, '', 'google/cloud/dataform/v1alpha2/dataform.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from .....google.type import interval_pb2 as google_dot_type_dot_interval__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-google/cloud/dataform/v1alpha2/dataform.proto\x12\x1egoogle.cloud.dataform.v1alpha2\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1agoogle/type/interval.proto"\xca\x04\n\nRepository\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12^\n\x13git_remote_settings\x18\x02 \x01(\x0b2<.google.cloud.dataform.v1alpha2.Repository.GitRemoteSettingsB\x03\xe0A\x01\x1a\xdc\x02\n\x11GitRemoteSettings\x12\x10\n\x03url\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x1b\n\x0edefault_branch\x18\x02 \x01(\tB\x03\xe0A\x02\x12_\n#authentication_token_secret_version\x18\x03 \x01(\tB2\xe0A\x02\xfaA,\n*secretmanager.googleapis.com/SecretVersion\x12c\n\x0ctoken_status\x18\x04 \x01(\x0e2H.google.cloud.dataform.v1alpha2.Repository.GitRemoteSettings.TokenStatusB\x03\xe0A\x03"R\n\x0bTokenStatus\x12\x1c\n\x18TOKEN_STATUS_UNSPECIFIED\x10\x00\x12\r\n\tNOT_FOUND\x10\x01\x12\x0b\n\x07INVALID\x10\x02\x12\t\n\x05VALID\x10\x03:j\xeaAg\n"dataform.googleapis.com/Repository\x12Aprojects/{project}/locations/{location}/repositories/{repository}"\xb1\x01\n\x17ListRepositoriesRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01"\x8a\x01\n\x18ListRepositoriesResponse\x12@\n\x0crepositories\x18\x01 \x03(\x0b2*.google.cloud.dataform.v1alpha2.Repository\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"P\n\x14GetRepositoryRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository"\xb5\x01\n\x17CreateRepositoryRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12C\n\nrepository\x18\x02 \x01(\x0b2*.google.cloud.dataform.v1alpha2.RepositoryB\x03\xe0A\x02\x12\x1a\n\rrepository_id\x18\x03 \x01(\tB\x03\xe0A\x02"\x94\x01\n\x17UpdateRepositoryRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01\x12C\n\nrepository\x18\x02 \x01(\x0b2*.google.cloud.dataform.v1alpha2.RepositoryB\x03\xe0A\x02"b\n\x17DeleteRepositoryRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository\x12\r\n\x05force\x18\x02 \x01(\x08"V\n\x1aFetchRemoteBranchesRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository"/\n\x1bFetchRemoteBranchesResponse\x12\x10\n\x08branches\x18\x01 \x03(\t"\xa1\x01\n\tWorkspace\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03:\x80\x01\xeaA}\n!dataform.googleapis.com/Workspace\x12Xprojects/{project}/locations/{location}/repositories/{repository}/workspaces/{workspace}"\xb0\x01\n\x15ListWorkspacesRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08order_by\x18\x04 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x05 \x01(\tB\x03\xe0A\x01"\x85\x01\n\x16ListWorkspacesResponse\x12=\n\nworkspaces\x18\x01 \x03(\x0b2).google.cloud.dataform.v1alpha2.Workspace\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"N\n\x13GetWorkspaceRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace"\xb2\x01\n\x16CreateWorkspaceRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository\x12A\n\tworkspace\x18\x02 \x01(\x0b2).google.cloud.dataform.v1alpha2.WorkspaceB\x03\xe0A\x02\x12\x19\n\x0cworkspace_id\x18\x03 \x01(\tB\x03\xe0A\x02"Q\n\x16DeleteWorkspaceRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace"=\n\x0cCommitAuthor\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x02\x12\x1a\n\remail_address\x18\x02 \x01(\tB\x03\xe0A\x02"\xaf\x01\n\x15PullGitCommitsRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x1a\n\rremote_branch\x18\x02 \x01(\tB\x03\xe0A\x01\x12A\n\x06author\x18\x03 \x01(\x0b2,.google.cloud.dataform.v1alpha2.CommitAuthorB\x03\xe0A\x02"l\n\x15PushGitCommitsRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x1a\n\rremote_branch\x18\x02 \x01(\tB\x03\xe0A\x01"V\n\x1bFetchFileGitStatusesRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace"\xfe\x02\n\x1cFetchFileGitStatusesResponse\x12t\n\x18uncommitted_file_changes\x18\x01 \x03(\x0b2R.google.cloud.dataform.v1alpha2.FetchFileGitStatusesResponse.UncommittedFileChange\x1a\xe7\x01\n\x15UncommittedFileChange\x12\x0c\n\x04path\x18\x01 \x01(\t\x12g\n\x05state\x18\x02 \x01(\x0e2X.google.cloud.dataform.v1alpha2.FetchFileGitStatusesResponse.UncommittedFileChange.State"W\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\t\n\x05ADDED\x10\x01\x12\x0b\n\x07DELETED\x10\x02\x12\x0c\n\x08MODIFIED\x10\x03\x12\x11\n\rHAS_CONFLICTS\x10\x04"q\n\x1aFetchGitAheadBehindRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x1a\n\rremote_branch\x18\x02 \x01(\tB\x03\xe0A\x01"L\n\x1bFetchGitAheadBehindResponse\x12\x15\n\rcommits_ahead\x18\x01 \x01(\x05\x12\x16\n\x0ecommits_behind\x18\x02 \x01(\x05"\xcc\x01\n\x1dCommitWorkspaceChangesRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12A\n\x06author\x18\x04 \x01(\x0b2,.google.cloud.dataform.v1alpha2.CommitAuthorB\x03\xe0A\x02\x12\x1b\n\x0ecommit_message\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x12\n\x05paths\x18\x03 \x03(\tB\x03\xe0A\x01"\x7f\n\x1cResetWorkspaceChangesRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x12\n\x05paths\x18\x02 \x03(\tB\x03\xe0A\x01\x12\x12\n\x05clean\x18\x03 \x01(\x08B\x03\xe0A\x01"g\n\x14FetchFileDiffRequest\x12<\n\tworkspace\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x11\n\x04path\x18\x02 \x01(\tB\x03\xe0A\x02"/\n\x15FetchFileDiffResponse\x12\x16\n\x0eformatted_diff\x18\x01 \x01(\t"\xa1\x01\n\x1dQueryDirectoryContentsRequest\x12<\n\tworkspace\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x11\n\x04path\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x16\n\tpage_size\x18\x03 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x04 \x01(\tB\x03\xe0A\x01"\xe3\x01\n\x1eQueryDirectoryContentsResponse\x12h\n\x11directory_entries\x18\x01 \x03(\x0b2M.google.cloud.dataform.v1alpha2.QueryDirectoryContentsResponse.DirectoryEntry\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x1a>\n\x0eDirectoryEntry\x12\x0e\n\x04file\x18\x01 \x01(\tH\x00\x12\x13\n\tdirectory\x18\x02 \x01(\tH\x00B\x07\n\x05entry"g\n\x14MakeDirectoryRequest\x12<\n\tworkspace\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x11\n\x04path\x18\x02 \x01(\tB\x03\xe0A\x02"\x17\n\x15MakeDirectoryResponse"i\n\x16RemoveDirectoryRequest\x12<\n\tworkspace\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x11\n\x04path\x18\x02 \x01(\tB\x03\xe0A\x02"~\n\x14MoveDirectoryRequest\x12<\n\tworkspace\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x11\n\x04path\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x15\n\x08new_path\x18\x03 \x01(\tB\x03\xe0A\x02"\x17\n\x15MoveDirectoryResponse"b\n\x0fReadFileRequest\x12<\n\tworkspace\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x11\n\x04path\x18\x02 \x01(\tB\x03\xe0A\x02")\n\x10ReadFileResponse\x12\x15\n\rfile_contents\x18\x01 \x01(\x0c"d\n\x11RemoveFileRequest\x12<\n\tworkspace\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x11\n\x04path\x18\x02 \x01(\tB\x03\xe0A\x02"y\n\x0fMoveFileRequest\x12<\n\tworkspace\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x11\n\x04path\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x15\n\x08new_path\x18\x03 \x01(\tB\x03\xe0A\x02"\x12\n\x10MoveFileResponse"z\n\x10WriteFileRequest\x12<\n\tworkspace\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace\x12\x11\n\x04path\x18\x02 \x01(\tB\x03\xe0A\x02\x12\x15\n\x08contents\x18\x03 \x01(\x0cB\x03\xe0A\x02"\x13\n\x11WriteFileResponse"Y\n\x19InstallNpmPackagesRequest\x12<\n\tworkspace\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace"\x1c\n\x1aInstallNpmPackagesResponse"\xb5\x08\n\x11CompilationResult\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x1c\n\rgit_commitish\x18\x02 \x01(\tB\x03\xe0A\x05H\x00\x12>\n\tworkspace\x18\x03 \x01(\tB)\xe0A\x05\xfaA#\n!dataform.googleapis.com/WorkspaceH\x00\x12m\n\x17code_compilation_config\x18\x04 \x01(\x0b2G.google.cloud.dataform.v1alpha2.CompilationResult.CodeCompilationConfigB\x03\xe0A\x05\x12"\n\x15dataform_core_version\x18\x05 \x01(\tB\x03\xe0A\x03\x12c\n\x12compilation_errors\x18\x06 \x03(\x0b2B.google.cloud.dataform.v1alpha2.CompilationResult.CompilationErrorB\x03\xe0A\x03\x1a\xf9\x02\n\x15CodeCompilationConfig\x12\x1d\n\x10default_database\x18\x01 \x01(\tB\x03\xe0A\x01\x12\x1b\n\x0edefault_schema\x18\x02 \x01(\tB\x03\xe0A\x01\x12\x1d\n\x10default_location\x18\x08 \x01(\tB\x03\xe0A\x01\x12\x1d\n\x10assertion_schema\x18\x03 \x01(\tB\x03\xe0A\x01\x12d\n\x04vars\x18\x04 \x03(\x0b2Q.google.cloud.dataform.v1alpha2.CompilationResult.CodeCompilationConfig.VarsEntryB\x03\xe0A\x01\x12\x1c\n\x0fdatabase_suffix\x18\x05 \x01(\tB\x03\xe0A\x01\x12\x1a\n\rschema_suffix\x18\x06 \x01(\tB\x03\xe0A\x01\x12\x19\n\x0ctable_prefix\x18\x07 \x01(\tB\x03\xe0A\x01\x1a+\n\tVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01\x1a\x93\x01\n\x10CompilationError\x12\x14\n\x07message\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x12\n\x05stack\x18\x02 \x01(\tB\x03\xe0A\x03\x12\x11\n\x04path\x18\x03 \x01(\tB\x03\xe0A\x03\x12B\n\raction_target\x18\x04 \x01(\x0b2&.google.cloud.dataform.v1alpha2.TargetB\x03\xe0A\x03:\x9a\x01\xeaA\x96\x01\n)dataform.googleapis.com/CompilationResult\x12iprojects/{project}/locations/{location}/repositories/{repository}/compilationResults/{compilation_result}B\x08\n\x06source"\x8c\x01\n\x1dListCompilationResultsRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"\x9e\x01\n\x1eListCompilationResultsResponse\x12N\n\x13compilation_results\x18\x01 \x03(\x0b21.google.cloud.dataform.v1alpha2.CompilationResult\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"^\n\x1bGetCompilationResultRequest\x12?\n\x04name\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)dataform.googleapis.com/CompilationResult"\xb0\x01\n\x1eCreateCompilationResultRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository\x12R\n\x12compilation_result\x18\x02 \x01(\x0b21.google.cloud.dataform.v1alpha2.CompilationResultB\x03\xe0A\x02"8\n\x06Target\x12\x10\n\x08database\x18\x01 \x01(\t\x12\x0e\n\x06schema\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t"\xec\x02\n\x12RelationDescriptor\x12\x13\n\x0bdescription\x18\x01 \x01(\t\x12T\n\x07columns\x18\x02 \x03(\x0b2C.google.cloud.dataform.v1alpha2.RelationDescriptor.ColumnDescriptor\x12_\n\x0fbigquery_labels\x18\x03 \x03(\x0b2F.google.cloud.dataform.v1alpha2.RelationDescriptor.BigqueryLabelsEntry\x1aS\n\x10ColumnDescriptor\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x13\n\x0bdescription\x18\x02 \x01(\t\x12\x1c\n\x14bigquery_policy_tags\x18\x03 \x03(\t\x1a5\n\x13BigqueryLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"\xe4\x11\n\x17CompilationResultAction\x126\n\x06target\x18\x01 \x01(\x0b2&.google.cloud.dataform.v1alpha2.Target\x12@\n\x10canonical_target\x18\x02 \x01(\x0b2&.google.cloud.dataform.v1alpha2.Target\x12\x11\n\tfile_path\x18\x03 \x01(\t\x12T\n\x08relation\x18\x04 \x01(\x0b2@.google.cloud.dataform.v1alpha2.CompilationResultAction.RelationH\x00\x12X\n\noperations\x18\x05 \x01(\x0b2B.google.cloud.dataform.v1alpha2.CompilationResultAction.OperationsH\x00\x12V\n\tassertion\x18\x06 \x01(\x0b2A.google.cloud.dataform.v1alpha2.CompilationResultAction.AssertionH\x00\x12Z\n\x0bdeclaration\x18\x07 \x01(\x0b2C.google.cloud.dataform.v1alpha2.CompilationResultAction.DeclarationH\x00\x1a\xe3\x08\n\x08Relation\x12B\n\x12dependency_targets\x18\x01 \x03(\x0b2&.google.cloud.dataform.v1alpha2.Target\x12\x10\n\x08disabled\x18\x02 \x01(\x08\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12O\n\x13relation_descriptor\x18\x04 \x01(\x0b22.google.cloud.dataform.v1alpha2.RelationDescriptor\x12d\n\rrelation_type\x18\x05 \x01(\x0e2M.google.cloud.dataform.v1alpha2.CompilationResultAction.Relation.RelationType\x12\x14\n\x0cselect_query\x18\x06 \x01(\t\x12\x16\n\x0epre_operations\x18\x07 \x03(\t\x12\x17\n\x0fpost_operations\x18\x08 \x03(\t\x12y\n\x18incremental_table_config\x18\t \x01(\x0b2W.google.cloud.dataform.v1alpha2.CompilationResultAction.Relation.IncrementalTableConfig\x12\x1c\n\x14partition_expression\x18\n \x01(\t\x12\x1b\n\x13cluster_expressions\x18\x0b \x03(\t\x12!\n\x19partition_expiration_days\x18\x0c \x01(\x05\x12 \n\x18require_partition_filter\x18\r \x01(\x08\x12s\n\x12additional_options\x18\x0e \x03(\x0b2W.google.cloud.dataform.v1alpha2.CompilationResultAction.Relation.AdditionalOptionsEntry\x1a\xd8\x01\n\x16IncrementalTableConfig\x12 \n\x18incremental_select_query\x18\x01 \x01(\t\x12\x18\n\x10refresh_disabled\x18\x02 \x01(\x08\x12\x18\n\x10unique_key_parts\x18\x03 \x03(\t\x12\x1f\n\x17update_partition_filter\x18\x04 \x01(\t\x12"\n\x1aincremental_pre_operations\x18\x05 \x03(\t\x12#\n\x1bincremental_post_operations\x18\x06 \x03(\t\x1a8\n\x16AdditionalOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"p\n\x0cRelationType\x12\x1d\n\x19RELATION_TYPE_UNSPECIFIED\x10\x00\x12\t\n\x05TABLE\x10\x01\x12\x08\n\x04VIEW\x10\x02\x12\x15\n\x11INCREMENTAL_TABLE\x10\x03\x12\x15\n\x11MATERIALIZED_VIEW\x10\x04\x1a\xe6\x01\n\nOperations\x12B\n\x12dependency_targets\x18\x01 \x03(\x0b2&.google.cloud.dataform.v1alpha2.Target\x12\x10\n\x08disabled\x18\x02 \x01(\x08\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12O\n\x13relation_descriptor\x18\x06 \x01(\x0b22.google.cloud.dataform.v1alpha2.RelationDescriptor\x12\x0f\n\x07queries\x18\x04 \x03(\t\x12\x12\n\nhas_output\x18\x05 \x01(\x08\x1a\x95\x02\n\tAssertion\x12B\n\x12dependency_targets\x18\x01 \x03(\x0b2&.google.cloud.dataform.v1alpha2.Target\x12=\n\rparent_action\x18\x05 \x01(\x0b2&.google.cloud.dataform.v1alpha2.Target\x12\x10\n\x08disabled\x18\x02 \x01(\x08\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12\x14\n\x0cselect_query\x18\x04 \x01(\t\x12O\n\x13relation_descriptor\x18\x06 \x01(\x0b22.google.cloud.dataform.v1alpha2.RelationDescriptor\x1a^\n\x0bDeclaration\x12O\n\x13relation_descriptor\x18\x01 \x01(\x0b22.google.cloud.dataform.v1alpha2.RelationDescriptorB\x11\n\x0fcompiled_object"\xad\x01\n$QueryCompilationResultActionsRequest\x12?\n\x04name\x18\x01 \x01(\tB1\xe0A\x02\xfaA+\n)dataform.googleapis.com/CompilationResult\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01"\x9d\x01\n%QueryCompilationResultActionsResponse\x12[\n\x1acompilation_result_actions\x18\x01 \x03(\x0b27.google.cloud.dataform.v1alpha2.CompilationResultAction\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xf1\x06\n\x12WorkflowInvocation\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12M\n\x12compilation_result\x18\x02 \x01(\tB1\xe0A\x05\xfaA+\n)dataform.googleapis.com/CompilationResult\x12c\n\x11invocation_config\x18\x03 \x01(\x0b2C.google.cloud.dataform.v1alpha2.WorkflowInvocation.InvocationConfigB\x03\xe0A\x05\x12L\n\x05state\x18\x04 \x01(\x0e28.google.cloud.dataform.v1alpha2.WorkflowInvocation.StateB\x03\xe0A\x03\x125\n\x11invocation_timing\x18\x05 \x01(\x0b2\x15.google.type.IntervalB\x03\xe0A\x03\x1a\x88\x02\n\x10InvocationConfig\x12E\n\x10included_targets\x18\x01 \x03(\x0b2&.google.cloud.dataform.v1alpha2.TargetB\x03\xe0A\x05\x12\x1a\n\rincluded_tags\x18\x02 \x03(\tB\x03\xe0A\x05\x12-\n transitive_dependencies_included\x18\x03 \x01(\x08B\x03\xe0A\x05\x12+\n\x1etransitive_dependents_included\x18\x04 \x01(\x08B\x03\xe0A\x05\x125\n(fully_refresh_incremental_tables_enabled\x18\x05 \x01(\x08B\x03\xe0A\x05"d\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\r\n\tSUCCEEDED\x10\x02\x12\r\n\tCANCELLED\x10\x03\x12\n\n\x06FAILED\x10\x04\x12\r\n\tCANCELING\x10\x05:\x9d\x01\xeaA\x99\x01\n*dataform.googleapis.com/WorkflowInvocation\x12kprojects/{project}/locations/{location}/repositories/{repository}/workflowInvocations/{workflow_invocation}"\x8d\x01\n\x1eListWorkflowInvocationsRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"\xa1\x01\n\x1fListWorkflowInvocationsResponse\x12P\n\x14workflow_invocations\x18\x01 \x03(\x0b22.google.cloud.dataform.v1alpha2.WorkflowInvocation\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"`\n\x1cGetWorkflowInvocationRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*dataform.googleapis.com/WorkflowInvocation"\xb3\x01\n\x1fCreateWorkflowInvocationRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository\x12T\n\x13workflow_invocation\x18\x02 \x01(\x0b22.google.cloud.dataform.v1alpha2.WorkflowInvocationB\x03\xe0A\x02"c\n\x1fDeleteWorkflowInvocationRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*dataform.googleapis.com/WorkflowInvocation"c\n\x1fCancelWorkflowInvocationRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*dataform.googleapis.com/WorkflowInvocation"\xc0\x04\n\x18WorkflowInvocationAction\x12;\n\x06target\x18\x01 \x01(\x0b2&.google.cloud.dataform.v1alpha2.TargetB\x03\xe0A\x03\x12E\n\x10canonical_target\x18\x02 \x01(\x0b2&.google.cloud.dataform.v1alpha2.TargetB\x03\xe0A\x03\x12R\n\x05state\x18\x04 \x01(\x0e2>.google.cloud.dataform.v1alpha2.WorkflowInvocationAction.StateB\x03\xe0A\x03\x12\x1b\n\x0efailure_reason\x18\x07 \x01(\tB\x03\xe0A\x03\x125\n\x11invocation_timing\x18\x05 \x01(\x0b2\x15.google.type.IntervalB\x03\xe0A\x03\x12e\n\x0fbigquery_action\x18\x06 \x01(\x0b2G.google.cloud.dataform.v1alpha2.WorkflowInvocationAction.BigQueryActionB\x03\xe0A\x03\x1a)\n\x0eBigQueryAction\x12\x17\n\nsql_script\x18\x01 \x01(\tB\x03\xe0A\x03"f\n\x05State\x12\x0b\n\x07PENDING\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0b\n\x07SKIPPED\x10\x02\x12\x0c\n\x08DISABLED\x10\x03\x12\r\n\tSUCCEEDED\x10\x04\x12\r\n\tCANCELLED\x10\x05\x12\n\n\x06FAILED\x10\x06"\x9a\x01\n%QueryWorkflowInvocationActionsRequest\x12@\n\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n*dataform.googleapis.com/WorkflowInvocation\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"\xa0\x01\n&QueryWorkflowInvocationActionsResponse\x12]\n\x1bworkflow_invocation_actions\x18\x01 \x03(\x0b28.google.cloud.dataform.v1alpha2.WorkflowInvocationAction\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\xad?\n\x08Dataform\x12\xce\x01\n\x10ListRepositories\x127.google.cloud.dataform.v1alpha2.ListRepositoriesRequest\x1a8.google.cloud.dataform.v1alpha2.ListRepositoriesResponse"G\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1alpha2/{parent=projects/*/locations/*}/repositories\x12\xb8\x01\n\rGetRepository\x124.google.cloud.dataform.v1alpha2.GetRepositoryRequest\x1a*.google.cloud.dataform.v1alpha2.Repository"E\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1alpha2/{name=projects/*/locations/*/repositories/*}\x12\xe5\x01\n\x10CreateRepository\x127.google.cloud.dataform.v1alpha2.CreateRepositoryRequest\x1a*.google.cloud.dataform.v1alpha2.Repository"l\xdaA\x1fparent,repository,repository_id\x82\xd3\xe4\x93\x02D"6/v1alpha2/{parent=projects/*/locations/*}/repositories:\nrepository\x12\xe7\x01\n\x10UpdateRepository\x127.google.cloud.dataform.v1alpha2.UpdateRepositoryRequest\x1a*.google.cloud.dataform.v1alpha2.Repository"n\xdaA\x16repository,update_mask\x82\xd3\xe4\x93\x02O2A/v1alpha2/{repository.name=projects/*/locations/*/repositories/*}:\nrepository\x12\xaa\x01\n\x10DeleteRepository\x127.google.cloud.dataform.v1alpha2.DeleteRepositoryRequest\x1a\x16.google.protobuf.Empty"E\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1alpha2/{name=projects/*/locations/*/repositories/*}\x12\xe2\x01\n\x13FetchRemoteBranches\x12:.google.cloud.dataform.v1alpha2.FetchRemoteBranchesRequest\x1a;.google.cloud.dataform.v1alpha2.FetchRemoteBranchesResponse"R\x82\xd3\xe4\x93\x02L\x12J/v1alpha2/{name=projects/*/locations/*/repositories/*}:fetchRemoteBranches\x12\xd5\x01\n\x0eListWorkspaces\x125.google.cloud.dataform.v1alpha2.ListWorkspacesRequest\x1a6.google.cloud.dataform.v1alpha2.ListWorkspacesResponse"T\xdaA\x06parent\x82\xd3\xe4\x93\x02E\x12C/v1alpha2/{parent=projects/*/locations/*/repositories/*}/workspaces\x12\xc2\x01\n\x0cGetWorkspace\x123.google.cloud.dataform.v1alpha2.GetWorkspaceRequest\x1a).google.cloud.dataform.v1alpha2.Workspace"R\xdaA\x04name\x82\xd3\xe4\x93\x02E\x12C/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}\x12\xec\x01\n\x0fCreateWorkspace\x126.google.cloud.dataform.v1alpha2.CreateWorkspaceRequest\x1a).google.cloud.dataform.v1alpha2.Workspace"v\xdaA\x1dparent,workspace,workspace_id\x82\xd3\xe4\x93\x02P"C/v1alpha2/{parent=projects/*/locations/*/repositories/*}/workspaces:\tworkspace\x12\xb5\x01\n\x0fDeleteWorkspace\x126.google.cloud.dataform.v1alpha2.DeleteWorkspaceRequest\x1a\x16.google.protobuf.Empty"R\xdaA\x04name\x82\xd3\xe4\x93\x02E*C/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}\x12\xf3\x01\n\x12InstallNpmPackages\x129.google.cloud.dataform.v1alpha2.InstallNpmPackagesRequest\x1a:.google.cloud.dataform.v1alpha2.InstallNpmPackagesResponse"f\x82\xd3\xe4\x93\x02`"[/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:installNpmPackages:\x01*\x12\xb4\x01\n\x0ePullGitCommits\x125.google.cloud.dataform.v1alpha2.PullGitCommitsRequest\x1a\x16.google.protobuf.Empty"S\x82\xd3\xe4\x93\x02M"H/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:pull:\x01*\x12\xb4\x01\n\x0ePushGitCommits\x125.google.cloud.dataform.v1alpha2.PushGitCommitsRequest\x1a\x16.google.protobuf.Empty"S\x82\xd3\xe4\x93\x02M"H/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:push:\x01*\x12\xf3\x01\n\x14FetchFileGitStatuses\x12;.google.cloud.dataform.v1alpha2.FetchFileGitStatusesRequest\x1a<.google.cloud.dataform.v1alpha2.FetchFileGitStatusesResponse"`\x82\xd3\xe4\x93\x02Z\x12X/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:fetchFileGitStatuses\x12\xef\x01\n\x13FetchGitAheadBehind\x12:.google.cloud.dataform.v1alpha2.FetchGitAheadBehindRequest\x1a;.google.cloud.dataform.v1alpha2.FetchGitAheadBehindResponse"_\x82\xd3\xe4\x93\x02Y\x12W/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:fetchGitAheadBehind\x12\xc6\x01\n\x16CommitWorkspaceChanges\x12=.google.cloud.dataform.v1alpha2.CommitWorkspaceChangesRequest\x1a\x16.google.protobuf.Empty"U\x82\xd3\xe4\x93\x02O"J/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:commit:\x01*\x12\xc3\x01\n\x15ResetWorkspaceChanges\x12<.google.cloud.dataform.v1alpha2.ResetWorkspaceChangesRequest\x1a\x16.google.protobuf.Empty"T\x82\xd3\xe4\x93\x02N"I/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:reset:\x01*\x12\xdc\x01\n\rFetchFileDiff\x124.google.cloud.dataform.v1alpha2.FetchFileDiffRequest\x1a5.google.cloud.dataform.v1alpha2.FetchFileDiffResponse"^\x82\xd3\xe4\x93\x02X\x12V/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:fetchFileDiff\x12\x80\x02\n\x16QueryDirectoryContents\x12=.google.cloud.dataform.v1alpha2.QueryDirectoryContentsRequest\x1a>.google.cloud.dataform.v1alpha2.QueryDirectoryContentsResponse"g\x82\xd3\xe4\x93\x02a\x12_/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:queryDirectoryContents\x12\xdf\x01\n\rMakeDirectory\x124.google.cloud.dataform.v1alpha2.MakeDirectoryRequest\x1a5.google.cloud.dataform.v1alpha2.MakeDirectoryResponse"a\x82\xd3\xe4\x93\x02["V/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:makeDirectory:\x01*\x12\xc6\x01\n\x0fRemoveDirectory\x126.google.cloud.dataform.v1alpha2.RemoveDirectoryRequest\x1a\x16.google.protobuf.Empty"c\x82\xd3\xe4\x93\x02]"X/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:removeDirectory:\x01*\x12\xdf\x01\n\rMoveDirectory\x124.google.cloud.dataform.v1alpha2.MoveDirectoryRequest\x1a5.google.cloud.dataform.v1alpha2.MoveDirectoryResponse"a\x82\xd3\xe4\x93\x02["V/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:moveDirectory:\x01*\x12\xc8\x01\n\x08ReadFile\x12/.google.cloud.dataform.v1alpha2.ReadFileRequest\x1a0.google.cloud.dataform.v1alpha2.ReadFileResponse"Y\x82\xd3\xe4\x93\x02S\x12Q/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:readFile\x12\xb7\x01\n\nRemoveFile\x121.google.cloud.dataform.v1alpha2.RemoveFileRequest\x1a\x16.google.protobuf.Empty"^\x82\xd3\xe4\x93\x02X"S/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:removeFile:\x01*\x12\xcb\x01\n\x08MoveFile\x12/.google.cloud.dataform.v1alpha2.MoveFileRequest\x1a0.google.cloud.dataform.v1alpha2.MoveFileResponse"\\\x82\xd3\xe4\x93\x02V"Q/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:moveFile:\x01*\x12\xcf\x01\n\tWriteFile\x120.google.cloud.dataform.v1alpha2.WriteFileRequest\x1a1.google.cloud.dataform.v1alpha2.WriteFileResponse"]\x82\xd3\xe4\x93\x02W"R/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:writeFile:\x01*\x12\xf5\x01\n\x16ListCompilationResults\x12=.google.cloud.dataform.v1alpha2.ListCompilationResultsRequest\x1a>.google.cloud.dataform.v1alpha2.ListCompilationResultsResponse"\\\xdaA\x06parent\x82\xd3\xe4\x93\x02M\x12K/v1alpha2/{parent=projects/*/locations/*/repositories/*}/compilationResults\x12\xe2\x01\n\x14GetCompilationResult\x12;.google.cloud.dataform.v1alpha2.GetCompilationResultRequest\x1a1.google.cloud.dataform.v1alpha2.CompilationResult"Z\xdaA\x04name\x82\xd3\xe4\x93\x02M\x12K/v1alpha2/{name=projects/*/locations/*/repositories/*/compilationResults/*}\x12\x92\x02\n\x17CreateCompilationResult\x12>.google.cloud.dataform.v1alpha2.CreateCompilationResultRequest\x1a1.google.cloud.dataform.v1alpha2.CompilationResult"\x83\x01\xdaA\x19parent,compilation_result\x82\xd3\xe4\x93\x02a"K/v1alpha2/{parent=projects/*/locations/*/repositories/*}/compilationResults:\x12compilation_result\x12\x87\x02\n\x1dQueryCompilationResultActions\x12D.google.cloud.dataform.v1alpha2.QueryCompilationResultActionsRequest\x1aE.google.cloud.dataform.v1alpha2.QueryCompilationResultActionsResponse"Y\x82\xd3\xe4\x93\x02S\x12Q/v1alpha2/{name=projects/*/locations/*/repositories/*/compilationResults/*}:query\x12\xf9\x01\n\x17ListWorkflowInvocations\x12>.google.cloud.dataform.v1alpha2.ListWorkflowInvocationsRequest\x1a?.google.cloud.dataform.v1alpha2.ListWorkflowInvocationsResponse"]\xdaA\x06parent\x82\xd3\xe4\x93\x02N\x12L/v1alpha2/{parent=projects/*/locations/*/repositories/*}/workflowInvocations\x12\xe6\x01\n\x15GetWorkflowInvocation\x12<.google.cloud.dataform.v1alpha2.GetWorkflowInvocationRequest\x1a2.google.cloud.dataform.v1alpha2.WorkflowInvocation"[\xdaA\x04name\x82\xd3\xe4\x93\x02N\x12L/v1alpha2/{name=projects/*/locations/*/repositories/*/workflowInvocations/*}\x12\x98\x02\n\x18CreateWorkflowInvocation\x12?.google.cloud.dataform.v1alpha2.CreateWorkflowInvocationRequest\x1a2.google.cloud.dataform.v1alpha2.WorkflowInvocation"\x86\x01\xdaA\x1aparent,workflow_invocation\x82\xd3\xe4\x93\x02c"L/v1alpha2/{parent=projects/*/locations/*/repositories/*}/workflowInvocations:\x13workflow_invocation\x12\xd0\x01\n\x18DeleteWorkflowInvocation\x12?.google.cloud.dataform.v1alpha2.DeleteWorkflowInvocationRequest\x1a\x16.google.protobuf.Empty"[\xdaA\x04name\x82\xd3\xe4\x93\x02N*L/v1alpha2/{name=projects/*/locations/*/repositories/*/workflowInvocations/*}\x12\xd3\x01\n\x18CancelWorkflowInvocation\x12?.google.cloud.dataform.v1alpha2.CancelWorkflowInvocationRequest\x1a\x16.google.protobuf.Empty"^\x82\xd3\xe4\x93\x02X"S/v1alpha2/{name=projects/*/locations/*/repositories/*/workflowInvocations/*}:cancel:\x01*\x12\x8b\x02\n\x1eQueryWorkflowInvocationActions\x12E.google.cloud.dataform.v1alpha2.QueryWorkflowInvocationActionsRequest\x1aF.google.cloud.dataform.v1alpha2.QueryWorkflowInvocationActionsResponse"Z\x82\xd3\xe4\x93\x02T\x12R/v1alpha2/{name=projects/*/locations/*/repositories/*/workflowInvocations/*}:query\x1aK\xcaA\x17dataform.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xc2\x02\n"com.google.cloud.dataform.v1alpha2B\rDataformProtoP\x01Z>cloud.google.com/go/dataform/apiv1alpha2/dataformpb;dataformpb\xaa\x02\x1eGoogle.Cloud.Dataform.V1Alpha2\xca\x02\x1eGoogle\\Cloud\\Dataform\\V1alpha2\xea\x02!Google::Cloud::Dataform::V1alpha2\xeaAd\n*secretmanager.googleapis.com/SecretVersion\x126projects/{project}/secrets/{secret}/versions/{version}b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.dataform.v1alpha2.dataform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n"com.google.cloud.dataform.v1alpha2B\rDataformProtoP\x01Z>cloud.google.com/go/dataform/apiv1alpha2/dataformpb;dataformpb\xaa\x02\x1eGoogle.Cloud.Dataform.V1Alpha2\xca\x02\x1eGoogle\\Cloud\\Dataform\\V1alpha2\xea\x02!Google::Cloud::Dataform::V1alpha2\xeaAd\n*secretmanager.googleapis.com/SecretVersion\x126projects/{project}/secrets/{secret}/versions/{version}'
    _globals['_REPOSITORY_GITREMOTESETTINGS'].fields_by_name['url']._loaded_options = None
    _globals['_REPOSITORY_GITREMOTESETTINGS'].fields_by_name['url']._serialized_options = b'\xe0A\x02'
    _globals['_REPOSITORY_GITREMOTESETTINGS'].fields_by_name['default_branch']._loaded_options = None
    _globals['_REPOSITORY_GITREMOTESETTINGS'].fields_by_name['default_branch']._serialized_options = b'\xe0A\x02'
    _globals['_REPOSITORY_GITREMOTESETTINGS'].fields_by_name['authentication_token_secret_version']._loaded_options = None
    _globals['_REPOSITORY_GITREMOTESETTINGS'].fields_by_name['authentication_token_secret_version']._serialized_options = b'\xe0A\x02\xfaA,\n*secretmanager.googleapis.com/SecretVersion'
    _globals['_REPOSITORY_GITREMOTESETTINGS'].fields_by_name['token_status']._loaded_options = None
    _globals['_REPOSITORY_GITREMOTESETTINGS'].fields_by_name['token_status']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY'].fields_by_name['name']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY'].fields_by_name['git_remote_settings']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['git_remote_settings']._serialized_options = b'\xe0A\x01'
    _globals['_REPOSITORY']._loaded_options = None
    _globals['_REPOSITORY']._serialized_options = b'\xeaAg\n"dataform.googleapis.com/Repository\x12Aprojects/{project}/locations/{location}/repositories/{repository}'
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_GETREPOSITORYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETREPOSITORYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository'
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository']._loaded_options = None
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository_id']._loaded_options = None
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository_id']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEREPOSITORYREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEREPOSITORYREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEREPOSITORYREQUEST'].fields_by_name['repository']._loaded_options = None
    _globals['_UPDATEREPOSITORYREQUEST'].fields_by_name['repository']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEREPOSITORYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEREPOSITORYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository'
    _globals['_FETCHREMOTEBRANCHESREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_FETCHREMOTEBRANCHESREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository'
    _globals['_WORKSPACE'].fields_by_name['name']._loaded_options = None
    _globals['_WORKSPACE'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_WORKSPACE']._loaded_options = None
    _globals['_WORKSPACE']._serialized_options = b'\xeaA}\n!dataform.googleapis.com/Workspace\x12Xprojects/{project}/locations/{location}/repositories/{repository}/workspaces/{workspace}'
    _globals['_LISTWORKSPACESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTWORKSPACESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository'
    _globals['_LISTWORKSPACESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTWORKSPACESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTWORKSPACESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTWORKSPACESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_LISTWORKSPACESREQUEST'].fields_by_name['order_by']._loaded_options = None
    _globals['_LISTWORKSPACESREQUEST'].fields_by_name['order_by']._serialized_options = b'\xe0A\x01'
    _globals['_LISTWORKSPACESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTWORKSPACESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_GETWORKSPACEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETWORKSPACEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_CREATEWORKSPACEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEWORKSPACEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository'
    _globals['_CREATEWORKSPACEREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_CREATEWORKSPACEREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEWORKSPACEREQUEST'].fields_by_name['workspace_id']._loaded_options = None
    _globals['_CREATEWORKSPACEREQUEST'].fields_by_name['workspace_id']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEWORKSPACEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEWORKSPACEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_COMMITAUTHOR'].fields_by_name['name']._loaded_options = None
    _globals['_COMMITAUTHOR'].fields_by_name['name']._serialized_options = b'\xe0A\x02'
    _globals['_COMMITAUTHOR'].fields_by_name['email_address']._loaded_options = None
    _globals['_COMMITAUTHOR'].fields_by_name['email_address']._serialized_options = b'\xe0A\x02'
    _globals['_PULLGITCOMMITSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_PULLGITCOMMITSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_PULLGITCOMMITSREQUEST'].fields_by_name['remote_branch']._loaded_options = None
    _globals['_PULLGITCOMMITSREQUEST'].fields_by_name['remote_branch']._serialized_options = b'\xe0A\x01'
    _globals['_PULLGITCOMMITSREQUEST'].fields_by_name['author']._loaded_options = None
    _globals['_PULLGITCOMMITSREQUEST'].fields_by_name['author']._serialized_options = b'\xe0A\x02'
    _globals['_PUSHGITCOMMITSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_PUSHGITCOMMITSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_PUSHGITCOMMITSREQUEST'].fields_by_name['remote_branch']._loaded_options = None
    _globals['_PUSHGITCOMMITSREQUEST'].fields_by_name['remote_branch']._serialized_options = b'\xe0A\x01'
    _globals['_FETCHFILEGITSTATUSESREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_FETCHFILEGITSTATUSESREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_FETCHGITAHEADBEHINDREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_FETCHGITAHEADBEHINDREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_FETCHGITAHEADBEHINDREQUEST'].fields_by_name['remote_branch']._loaded_options = None
    _globals['_FETCHGITAHEADBEHINDREQUEST'].fields_by_name['remote_branch']._serialized_options = b'\xe0A\x01'
    _globals['_COMMITWORKSPACECHANGESREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_COMMITWORKSPACECHANGESREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_COMMITWORKSPACECHANGESREQUEST'].fields_by_name['author']._loaded_options = None
    _globals['_COMMITWORKSPACECHANGESREQUEST'].fields_by_name['author']._serialized_options = b'\xe0A\x02'
    _globals['_COMMITWORKSPACECHANGESREQUEST'].fields_by_name['commit_message']._loaded_options = None
    _globals['_COMMITWORKSPACECHANGESREQUEST'].fields_by_name['commit_message']._serialized_options = b'\xe0A\x01'
    _globals['_COMMITWORKSPACECHANGESREQUEST'].fields_by_name['paths']._loaded_options = None
    _globals['_COMMITWORKSPACECHANGESREQUEST'].fields_by_name['paths']._serialized_options = b'\xe0A\x01'
    _globals['_RESETWORKSPACECHANGESREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RESETWORKSPACECHANGESREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_RESETWORKSPACECHANGESREQUEST'].fields_by_name['paths']._loaded_options = None
    _globals['_RESETWORKSPACECHANGESREQUEST'].fields_by_name['paths']._serialized_options = b'\xe0A\x01'
    _globals['_RESETWORKSPACECHANGESREQUEST'].fields_by_name['clean']._loaded_options = None
    _globals['_RESETWORKSPACECHANGESREQUEST'].fields_by_name['clean']._serialized_options = b'\xe0A\x01'
    _globals['_FETCHFILEDIFFREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_FETCHFILEDIFFREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_FETCHFILEDIFFREQUEST'].fields_by_name['path']._loaded_options = None
    _globals['_FETCHFILEDIFFREQUEST'].fields_by_name['path']._serialized_options = b'\xe0A\x02'
    _globals['_QUERYDIRECTORYCONTENTSREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_QUERYDIRECTORYCONTENTSREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_QUERYDIRECTORYCONTENTSREQUEST'].fields_by_name['path']._loaded_options = None
    _globals['_QUERYDIRECTORYCONTENTSREQUEST'].fields_by_name['path']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYDIRECTORYCONTENTSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_QUERYDIRECTORYCONTENTSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYDIRECTORYCONTENTSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_QUERYDIRECTORYCONTENTSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_MAKEDIRECTORYREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_MAKEDIRECTORYREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_MAKEDIRECTORYREQUEST'].fields_by_name['path']._loaded_options = None
    _globals['_MAKEDIRECTORYREQUEST'].fields_by_name['path']._serialized_options = b'\xe0A\x02'
    _globals['_REMOVEDIRECTORYREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_REMOVEDIRECTORYREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_REMOVEDIRECTORYREQUEST'].fields_by_name['path']._loaded_options = None
    _globals['_REMOVEDIRECTORYREQUEST'].fields_by_name['path']._serialized_options = b'\xe0A\x02'
    _globals['_MOVEDIRECTORYREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_MOVEDIRECTORYREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_MOVEDIRECTORYREQUEST'].fields_by_name['path']._loaded_options = None
    _globals['_MOVEDIRECTORYREQUEST'].fields_by_name['path']._serialized_options = b'\xe0A\x02'
    _globals['_MOVEDIRECTORYREQUEST'].fields_by_name['new_path']._loaded_options = None
    _globals['_MOVEDIRECTORYREQUEST'].fields_by_name['new_path']._serialized_options = b'\xe0A\x02'
    _globals['_READFILEREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_READFILEREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_READFILEREQUEST'].fields_by_name['path']._loaded_options = None
    _globals['_READFILEREQUEST'].fields_by_name['path']._serialized_options = b'\xe0A\x02'
    _globals['_REMOVEFILEREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_REMOVEFILEREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_REMOVEFILEREQUEST'].fields_by_name['path']._loaded_options = None
    _globals['_REMOVEFILEREQUEST'].fields_by_name['path']._serialized_options = b'\xe0A\x02'
    _globals['_MOVEFILEREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_MOVEFILEREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_MOVEFILEREQUEST'].fields_by_name['path']._loaded_options = None
    _globals['_MOVEFILEREQUEST'].fields_by_name['path']._serialized_options = b'\xe0A\x02'
    _globals['_MOVEFILEREQUEST'].fields_by_name['new_path']._loaded_options = None
    _globals['_MOVEFILEREQUEST'].fields_by_name['new_path']._serialized_options = b'\xe0A\x02'
    _globals['_WRITEFILEREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_WRITEFILEREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_WRITEFILEREQUEST'].fields_by_name['path']._loaded_options = None
    _globals['_WRITEFILEREQUEST'].fields_by_name['path']._serialized_options = b'\xe0A\x02'
    _globals['_WRITEFILEREQUEST'].fields_by_name['contents']._loaded_options = None
    _globals['_WRITEFILEREQUEST'].fields_by_name['contents']._serialized_options = b'\xe0A\x02'
    _globals['_INSTALLNPMPACKAGESREQUEST'].fields_by_name['workspace']._loaded_options = None
    _globals['_INSTALLNPMPACKAGESREQUEST'].fields_by_name['workspace']._serialized_options = b'\xe0A\x02\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG_VARSENTRY']._loaded_options = None
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG_VARSENTRY']._serialized_options = b'8\x01'
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['default_database']._loaded_options = None
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['default_database']._serialized_options = b'\xe0A\x01'
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['default_schema']._loaded_options = None
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['default_schema']._serialized_options = b'\xe0A\x01'
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['default_location']._loaded_options = None
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['default_location']._serialized_options = b'\xe0A\x01'
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['assertion_schema']._loaded_options = None
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['assertion_schema']._serialized_options = b'\xe0A\x01'
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['vars']._loaded_options = None
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['vars']._serialized_options = b'\xe0A\x01'
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['database_suffix']._loaded_options = None
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['database_suffix']._serialized_options = b'\xe0A\x01'
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['schema_suffix']._loaded_options = None
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['schema_suffix']._serialized_options = b'\xe0A\x01'
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['table_prefix']._loaded_options = None
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG'].fields_by_name['table_prefix']._serialized_options = b'\xe0A\x01'
    _globals['_COMPILATIONRESULT_COMPILATIONERROR'].fields_by_name['message']._loaded_options = None
    _globals['_COMPILATIONRESULT_COMPILATIONERROR'].fields_by_name['message']._serialized_options = b'\xe0A\x03'
    _globals['_COMPILATIONRESULT_COMPILATIONERROR'].fields_by_name['stack']._loaded_options = None
    _globals['_COMPILATIONRESULT_COMPILATIONERROR'].fields_by_name['stack']._serialized_options = b'\xe0A\x03'
    _globals['_COMPILATIONRESULT_COMPILATIONERROR'].fields_by_name['path']._loaded_options = None
    _globals['_COMPILATIONRESULT_COMPILATIONERROR'].fields_by_name['path']._serialized_options = b'\xe0A\x03'
    _globals['_COMPILATIONRESULT_COMPILATIONERROR'].fields_by_name['action_target']._loaded_options = None
    _globals['_COMPILATIONRESULT_COMPILATIONERROR'].fields_by_name['action_target']._serialized_options = b'\xe0A\x03'
    _globals['_COMPILATIONRESULT'].fields_by_name['name']._loaded_options = None
    _globals['_COMPILATIONRESULT'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_COMPILATIONRESULT'].fields_by_name['git_commitish']._loaded_options = None
    _globals['_COMPILATIONRESULT'].fields_by_name['git_commitish']._serialized_options = b'\xe0A\x05'
    _globals['_COMPILATIONRESULT'].fields_by_name['workspace']._loaded_options = None
    _globals['_COMPILATIONRESULT'].fields_by_name['workspace']._serialized_options = b'\xe0A\x05\xfaA#\n!dataform.googleapis.com/Workspace'
    _globals['_COMPILATIONRESULT'].fields_by_name['code_compilation_config']._loaded_options = None
    _globals['_COMPILATIONRESULT'].fields_by_name['code_compilation_config']._serialized_options = b'\xe0A\x05'
    _globals['_COMPILATIONRESULT'].fields_by_name['dataform_core_version']._loaded_options = None
    _globals['_COMPILATIONRESULT'].fields_by_name['dataform_core_version']._serialized_options = b'\xe0A\x03'
    _globals['_COMPILATIONRESULT'].fields_by_name['compilation_errors']._loaded_options = None
    _globals['_COMPILATIONRESULT'].fields_by_name['compilation_errors']._serialized_options = b'\xe0A\x03'
    _globals['_COMPILATIONRESULT']._loaded_options = None
    _globals['_COMPILATIONRESULT']._serialized_options = b'\xeaA\x96\x01\n)dataform.googleapis.com/CompilationResult\x12iprojects/{project}/locations/{location}/repositories/{repository}/compilationResults/{compilation_result}'
    _globals['_LISTCOMPILATIONRESULTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTCOMPILATIONRESULTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository'
    _globals['_LISTCOMPILATIONRESULTSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTCOMPILATIONRESULTSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTCOMPILATIONRESULTSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTCOMPILATIONRESULTSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_GETCOMPILATIONRESULTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETCOMPILATIONRESULTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA+\n)dataform.googleapis.com/CompilationResult'
    _globals['_CREATECOMPILATIONRESULTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATECOMPILATIONRESULTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository'
    _globals['_CREATECOMPILATIONRESULTREQUEST'].fields_by_name['compilation_result']._loaded_options = None
    _globals['_CREATECOMPILATIONRESULTREQUEST'].fields_by_name['compilation_result']._serialized_options = b'\xe0A\x02'
    _globals['_RELATIONDESCRIPTOR_BIGQUERYLABELSENTRY']._loaded_options = None
    _globals['_RELATIONDESCRIPTOR_BIGQUERYLABELSENTRY']._serialized_options = b'8\x01'
    _globals['_COMPILATIONRESULTACTION_RELATION_ADDITIONALOPTIONSENTRY']._loaded_options = None
    _globals['_COMPILATIONRESULTACTION_RELATION_ADDITIONALOPTIONSENTRY']._serialized_options = b'8\x01'
    _globals['_QUERYCOMPILATIONRESULTACTIONSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_QUERYCOMPILATIONRESULTACTIONSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA+\n)dataform.googleapis.com/CompilationResult'
    _globals['_QUERYCOMPILATIONRESULTACTIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_QUERYCOMPILATIONRESULTACTIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYCOMPILATIONRESULTACTIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_QUERYCOMPILATIONRESULTACTIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYCOMPILATIONRESULTACTIONSREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_QUERYCOMPILATIONRESULTACTIONSREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG'].fields_by_name['included_targets']._loaded_options = None
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG'].fields_by_name['included_targets']._serialized_options = b'\xe0A\x05'
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG'].fields_by_name['included_tags']._loaded_options = None
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG'].fields_by_name['included_tags']._serialized_options = b'\xe0A\x05'
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG'].fields_by_name['transitive_dependencies_included']._loaded_options = None
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG'].fields_by_name['transitive_dependencies_included']._serialized_options = b'\xe0A\x05'
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG'].fields_by_name['transitive_dependents_included']._loaded_options = None
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG'].fields_by_name['transitive_dependents_included']._serialized_options = b'\xe0A\x05'
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG'].fields_by_name['fully_refresh_incremental_tables_enabled']._loaded_options = None
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG'].fields_by_name['fully_refresh_incremental_tables_enabled']._serialized_options = b'\xe0A\x05'
    _globals['_WORKFLOWINVOCATION'].fields_by_name['name']._loaded_options = None
    _globals['_WORKFLOWINVOCATION'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_WORKFLOWINVOCATION'].fields_by_name['compilation_result']._loaded_options = None
    _globals['_WORKFLOWINVOCATION'].fields_by_name['compilation_result']._serialized_options = b'\xe0A\x05\xfaA+\n)dataform.googleapis.com/CompilationResult'
    _globals['_WORKFLOWINVOCATION'].fields_by_name['invocation_config']._loaded_options = None
    _globals['_WORKFLOWINVOCATION'].fields_by_name['invocation_config']._serialized_options = b'\xe0A\x05'
    _globals['_WORKFLOWINVOCATION'].fields_by_name['state']._loaded_options = None
    _globals['_WORKFLOWINVOCATION'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_WORKFLOWINVOCATION'].fields_by_name['invocation_timing']._loaded_options = None
    _globals['_WORKFLOWINVOCATION'].fields_by_name['invocation_timing']._serialized_options = b'\xe0A\x03'
    _globals['_WORKFLOWINVOCATION']._loaded_options = None
    _globals['_WORKFLOWINVOCATION']._serialized_options = b'\xeaA\x99\x01\n*dataform.googleapis.com/WorkflowInvocation\x12kprojects/{project}/locations/{location}/repositories/{repository}/workflowInvocations/{workflow_invocation}'
    _globals['_LISTWORKFLOWINVOCATIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTWORKFLOWINVOCATIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository'
    _globals['_LISTWORKFLOWINVOCATIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTWORKFLOWINVOCATIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTWORKFLOWINVOCATIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTWORKFLOWINVOCATIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_GETWORKFLOWINVOCATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETWORKFLOWINVOCATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*dataform.googleapis.com/WorkflowInvocation'
    _globals['_CREATEWORKFLOWINVOCATIONREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEWORKFLOWINVOCATIONREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\n"dataform.googleapis.com/Repository'
    _globals['_CREATEWORKFLOWINVOCATIONREQUEST'].fields_by_name['workflow_invocation']._loaded_options = None
    _globals['_CREATEWORKFLOWINVOCATIONREQUEST'].fields_by_name['workflow_invocation']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEWORKFLOWINVOCATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEWORKFLOWINVOCATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*dataform.googleapis.com/WorkflowInvocation'
    _globals['_CANCELWORKFLOWINVOCATIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_CANCELWORKFLOWINVOCATIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*dataform.googleapis.com/WorkflowInvocation'
    _globals['_WORKFLOWINVOCATIONACTION_BIGQUERYACTION'].fields_by_name['sql_script']._loaded_options = None
    _globals['_WORKFLOWINVOCATIONACTION_BIGQUERYACTION'].fields_by_name['sql_script']._serialized_options = b'\xe0A\x03'
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['target']._loaded_options = None
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['target']._serialized_options = b'\xe0A\x03'
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['canonical_target']._loaded_options = None
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['canonical_target']._serialized_options = b'\xe0A\x03'
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['state']._loaded_options = None
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['failure_reason']._loaded_options = None
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['failure_reason']._serialized_options = b'\xe0A\x03'
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['invocation_timing']._loaded_options = None
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['invocation_timing']._serialized_options = b'\xe0A\x03'
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['bigquery_action']._loaded_options = None
    _globals['_WORKFLOWINVOCATIONACTION'].fields_by_name['bigquery_action']._serialized_options = b'\xe0A\x03'
    _globals['_QUERYWORKFLOWINVOCATIONACTIONSREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_QUERYWORKFLOWINVOCATIONACTIONSREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA,\n*dataform.googleapis.com/WorkflowInvocation'
    _globals['_QUERYWORKFLOWINVOCATIONACTIONSREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_QUERYWORKFLOWINVOCATIONACTIONSREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_QUERYWORKFLOWINVOCATIONACTIONSREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_QUERYWORKFLOWINVOCATIONACTIONSREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_DATAFORM']._loaded_options = None
    _globals['_DATAFORM']._serialized_options = b'\xcaA\x17dataform.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_DATAFORM'].methods_by_name['ListRepositories']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['ListRepositories']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x028\x126/v1alpha2/{parent=projects/*/locations/*}/repositories'
    _globals['_DATAFORM'].methods_by_name['GetRepository']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['GetRepository']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028\x126/v1alpha2/{name=projects/*/locations/*/repositories/*}'
    _globals['_DATAFORM'].methods_by_name['CreateRepository']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['CreateRepository']._serialized_options = b'\xdaA\x1fparent,repository,repository_id\x82\xd3\xe4\x93\x02D"6/v1alpha2/{parent=projects/*/locations/*}/repositories:\nrepository'
    _globals['_DATAFORM'].methods_by_name['UpdateRepository']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['UpdateRepository']._serialized_options = b'\xdaA\x16repository,update_mask\x82\xd3\xe4\x93\x02O2A/v1alpha2/{repository.name=projects/*/locations/*/repositories/*}:\nrepository'
    _globals['_DATAFORM'].methods_by_name['DeleteRepository']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['DeleteRepository']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x028*6/v1alpha2/{name=projects/*/locations/*/repositories/*}'
    _globals['_DATAFORM'].methods_by_name['FetchRemoteBranches']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['FetchRemoteBranches']._serialized_options = b'\x82\xd3\xe4\x93\x02L\x12J/v1alpha2/{name=projects/*/locations/*/repositories/*}:fetchRemoteBranches'
    _globals['_DATAFORM'].methods_by_name['ListWorkspaces']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['ListWorkspaces']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02E\x12C/v1alpha2/{parent=projects/*/locations/*/repositories/*}/workspaces'
    _globals['_DATAFORM'].methods_by_name['GetWorkspace']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['GetWorkspace']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02E\x12C/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}'
    _globals['_DATAFORM'].methods_by_name['CreateWorkspace']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['CreateWorkspace']._serialized_options = b'\xdaA\x1dparent,workspace,workspace_id\x82\xd3\xe4\x93\x02P"C/v1alpha2/{parent=projects/*/locations/*/repositories/*}/workspaces:\tworkspace'
    _globals['_DATAFORM'].methods_by_name['DeleteWorkspace']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['DeleteWorkspace']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02E*C/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}'
    _globals['_DATAFORM'].methods_by_name['InstallNpmPackages']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['InstallNpmPackages']._serialized_options = b'\x82\xd3\xe4\x93\x02`"[/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:installNpmPackages:\x01*'
    _globals['_DATAFORM'].methods_by_name['PullGitCommits']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['PullGitCommits']._serialized_options = b'\x82\xd3\xe4\x93\x02M"H/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:pull:\x01*'
    _globals['_DATAFORM'].methods_by_name['PushGitCommits']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['PushGitCommits']._serialized_options = b'\x82\xd3\xe4\x93\x02M"H/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:push:\x01*'
    _globals['_DATAFORM'].methods_by_name['FetchFileGitStatuses']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['FetchFileGitStatuses']._serialized_options = b'\x82\xd3\xe4\x93\x02Z\x12X/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:fetchFileGitStatuses'
    _globals['_DATAFORM'].methods_by_name['FetchGitAheadBehind']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['FetchGitAheadBehind']._serialized_options = b'\x82\xd3\xe4\x93\x02Y\x12W/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:fetchGitAheadBehind'
    _globals['_DATAFORM'].methods_by_name['CommitWorkspaceChanges']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['CommitWorkspaceChanges']._serialized_options = b'\x82\xd3\xe4\x93\x02O"J/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:commit:\x01*'
    _globals['_DATAFORM'].methods_by_name['ResetWorkspaceChanges']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['ResetWorkspaceChanges']._serialized_options = b'\x82\xd3\xe4\x93\x02N"I/v1alpha2/{name=projects/*/locations/*/repositories/*/workspaces/*}:reset:\x01*'
    _globals['_DATAFORM'].methods_by_name['FetchFileDiff']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['FetchFileDiff']._serialized_options = b'\x82\xd3\xe4\x93\x02X\x12V/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:fetchFileDiff'
    _globals['_DATAFORM'].methods_by_name['QueryDirectoryContents']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['QueryDirectoryContents']._serialized_options = b'\x82\xd3\xe4\x93\x02a\x12_/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:queryDirectoryContents'
    _globals['_DATAFORM'].methods_by_name['MakeDirectory']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['MakeDirectory']._serialized_options = b'\x82\xd3\xe4\x93\x02["V/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:makeDirectory:\x01*'
    _globals['_DATAFORM'].methods_by_name['RemoveDirectory']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['RemoveDirectory']._serialized_options = b'\x82\xd3\xe4\x93\x02]"X/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:removeDirectory:\x01*'
    _globals['_DATAFORM'].methods_by_name['MoveDirectory']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['MoveDirectory']._serialized_options = b'\x82\xd3\xe4\x93\x02["V/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:moveDirectory:\x01*'
    _globals['_DATAFORM'].methods_by_name['ReadFile']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['ReadFile']._serialized_options = b'\x82\xd3\xe4\x93\x02S\x12Q/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:readFile'
    _globals['_DATAFORM'].methods_by_name['RemoveFile']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['RemoveFile']._serialized_options = b'\x82\xd3\xe4\x93\x02X"S/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:removeFile:\x01*'
    _globals['_DATAFORM'].methods_by_name['MoveFile']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['MoveFile']._serialized_options = b'\x82\xd3\xe4\x93\x02V"Q/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:moveFile:\x01*'
    _globals['_DATAFORM'].methods_by_name['WriteFile']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['WriteFile']._serialized_options = b'\x82\xd3\xe4\x93\x02W"R/v1alpha2/{workspace=projects/*/locations/*/repositories/*/workspaces/*}:writeFile:\x01*'
    _globals['_DATAFORM'].methods_by_name['ListCompilationResults']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['ListCompilationResults']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02M\x12K/v1alpha2/{parent=projects/*/locations/*/repositories/*}/compilationResults'
    _globals['_DATAFORM'].methods_by_name['GetCompilationResult']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['GetCompilationResult']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02M\x12K/v1alpha2/{name=projects/*/locations/*/repositories/*/compilationResults/*}'
    _globals['_DATAFORM'].methods_by_name['CreateCompilationResult']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['CreateCompilationResult']._serialized_options = b'\xdaA\x19parent,compilation_result\x82\xd3\xe4\x93\x02a"K/v1alpha2/{parent=projects/*/locations/*/repositories/*}/compilationResults:\x12compilation_result'
    _globals['_DATAFORM'].methods_by_name['QueryCompilationResultActions']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['QueryCompilationResultActions']._serialized_options = b'\x82\xd3\xe4\x93\x02S\x12Q/v1alpha2/{name=projects/*/locations/*/repositories/*/compilationResults/*}:query'
    _globals['_DATAFORM'].methods_by_name['ListWorkflowInvocations']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['ListWorkflowInvocations']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02N\x12L/v1alpha2/{parent=projects/*/locations/*/repositories/*}/workflowInvocations'
    _globals['_DATAFORM'].methods_by_name['GetWorkflowInvocation']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['GetWorkflowInvocation']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02N\x12L/v1alpha2/{name=projects/*/locations/*/repositories/*/workflowInvocations/*}'
    _globals['_DATAFORM'].methods_by_name['CreateWorkflowInvocation']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['CreateWorkflowInvocation']._serialized_options = b'\xdaA\x1aparent,workflow_invocation\x82\xd3\xe4\x93\x02c"L/v1alpha2/{parent=projects/*/locations/*/repositories/*}/workflowInvocations:\x13workflow_invocation'
    _globals['_DATAFORM'].methods_by_name['DeleteWorkflowInvocation']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['DeleteWorkflowInvocation']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02N*L/v1alpha2/{name=projects/*/locations/*/repositories/*/workflowInvocations/*}'
    _globals['_DATAFORM'].methods_by_name['CancelWorkflowInvocation']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['CancelWorkflowInvocation']._serialized_options = b'\x82\xd3\xe4\x93\x02X"S/v1alpha2/{name=projects/*/locations/*/repositories/*/workflowInvocations/*}:cancel:\x01*'
    _globals['_DATAFORM'].methods_by_name['QueryWorkflowInvocationActions']._loaded_options = None
    _globals['_DATAFORM'].methods_by_name['QueryWorkflowInvocationActions']._serialized_options = b'\x82\xd3\xe4\x93\x02T\x12R/v1alpha2/{name=projects/*/locations/*/repositories/*/workflowInvocations/*}:query'
    _globals['_REPOSITORY']._serialized_start = 288
    _globals['_REPOSITORY']._serialized_end = 874
    _globals['_REPOSITORY_GITREMOTESETTINGS']._serialized_start = 418
    _globals['_REPOSITORY_GITREMOTESETTINGS']._serialized_end = 766
    _globals['_REPOSITORY_GITREMOTESETTINGS_TOKENSTATUS']._serialized_start = 684
    _globals['_REPOSITORY_GITREMOTESETTINGS_TOKENSTATUS']._serialized_end = 766
    _globals['_LISTREPOSITORIESREQUEST']._serialized_start = 877
    _globals['_LISTREPOSITORIESREQUEST']._serialized_end = 1054
    _globals['_LISTREPOSITORIESRESPONSE']._serialized_start = 1057
    _globals['_LISTREPOSITORIESRESPONSE']._serialized_end = 1195
    _globals['_GETREPOSITORYREQUEST']._serialized_start = 1197
    _globals['_GETREPOSITORYREQUEST']._serialized_end = 1277
    _globals['_CREATEREPOSITORYREQUEST']._serialized_start = 1280
    _globals['_CREATEREPOSITORYREQUEST']._serialized_end = 1461
    _globals['_UPDATEREPOSITORYREQUEST']._serialized_start = 1464
    _globals['_UPDATEREPOSITORYREQUEST']._serialized_end = 1612
    _globals['_DELETEREPOSITORYREQUEST']._serialized_start = 1614
    _globals['_DELETEREPOSITORYREQUEST']._serialized_end = 1712
    _globals['_FETCHREMOTEBRANCHESREQUEST']._serialized_start = 1714
    _globals['_FETCHREMOTEBRANCHESREQUEST']._serialized_end = 1800
    _globals['_FETCHREMOTEBRANCHESRESPONSE']._serialized_start = 1802
    _globals['_FETCHREMOTEBRANCHESRESPONSE']._serialized_end = 1849
    _globals['_WORKSPACE']._serialized_start = 1852
    _globals['_WORKSPACE']._serialized_end = 2013
    _globals['_LISTWORKSPACESREQUEST']._serialized_start = 2016
    _globals['_LISTWORKSPACESREQUEST']._serialized_end = 2192
    _globals['_LISTWORKSPACESRESPONSE']._serialized_start = 2195
    _globals['_LISTWORKSPACESRESPONSE']._serialized_end = 2328
    _globals['_GETWORKSPACEREQUEST']._serialized_start = 2330
    _globals['_GETWORKSPACEREQUEST']._serialized_end = 2408
    _globals['_CREATEWORKSPACEREQUEST']._serialized_start = 2411
    _globals['_CREATEWORKSPACEREQUEST']._serialized_end = 2589
    _globals['_DELETEWORKSPACEREQUEST']._serialized_start = 2591
    _globals['_DELETEWORKSPACEREQUEST']._serialized_end = 2672
    _globals['_COMMITAUTHOR']._serialized_start = 2674
    _globals['_COMMITAUTHOR']._serialized_end = 2735
    _globals['_PULLGITCOMMITSREQUEST']._serialized_start = 2738
    _globals['_PULLGITCOMMITSREQUEST']._serialized_end = 2913
    _globals['_PUSHGITCOMMITSREQUEST']._serialized_start = 2915
    _globals['_PUSHGITCOMMITSREQUEST']._serialized_end = 3023
    _globals['_FETCHFILEGITSTATUSESREQUEST']._serialized_start = 3025
    _globals['_FETCHFILEGITSTATUSESREQUEST']._serialized_end = 3111
    _globals['_FETCHFILEGITSTATUSESRESPONSE']._serialized_start = 3114
    _globals['_FETCHFILEGITSTATUSESRESPONSE']._serialized_end = 3496
    _globals['_FETCHFILEGITSTATUSESRESPONSE_UNCOMMITTEDFILECHANGE']._serialized_start = 3265
    _globals['_FETCHFILEGITSTATUSESRESPONSE_UNCOMMITTEDFILECHANGE']._serialized_end = 3496
    _globals['_FETCHFILEGITSTATUSESRESPONSE_UNCOMMITTEDFILECHANGE_STATE']._serialized_start = 3409
    _globals['_FETCHFILEGITSTATUSESRESPONSE_UNCOMMITTEDFILECHANGE_STATE']._serialized_end = 3496
    _globals['_FETCHGITAHEADBEHINDREQUEST']._serialized_start = 3498
    _globals['_FETCHGITAHEADBEHINDREQUEST']._serialized_end = 3611
    _globals['_FETCHGITAHEADBEHINDRESPONSE']._serialized_start = 3613
    _globals['_FETCHGITAHEADBEHINDRESPONSE']._serialized_end = 3689
    _globals['_COMMITWORKSPACECHANGESREQUEST']._serialized_start = 3692
    _globals['_COMMITWORKSPACECHANGESREQUEST']._serialized_end = 3896
    _globals['_RESETWORKSPACECHANGESREQUEST']._serialized_start = 3898
    _globals['_RESETWORKSPACECHANGESREQUEST']._serialized_end = 4025
    _globals['_FETCHFILEDIFFREQUEST']._serialized_start = 4027
    _globals['_FETCHFILEDIFFREQUEST']._serialized_end = 4130
    _globals['_FETCHFILEDIFFRESPONSE']._serialized_start = 4132
    _globals['_FETCHFILEDIFFRESPONSE']._serialized_end = 4179
    _globals['_QUERYDIRECTORYCONTENTSREQUEST']._serialized_start = 4182
    _globals['_QUERYDIRECTORYCONTENTSREQUEST']._serialized_end = 4343
    _globals['_QUERYDIRECTORYCONTENTSRESPONSE']._serialized_start = 4346
    _globals['_QUERYDIRECTORYCONTENTSRESPONSE']._serialized_end = 4573
    _globals['_QUERYDIRECTORYCONTENTSRESPONSE_DIRECTORYENTRY']._serialized_start = 4511
    _globals['_QUERYDIRECTORYCONTENTSRESPONSE_DIRECTORYENTRY']._serialized_end = 4573
    _globals['_MAKEDIRECTORYREQUEST']._serialized_start = 4575
    _globals['_MAKEDIRECTORYREQUEST']._serialized_end = 4678
    _globals['_MAKEDIRECTORYRESPONSE']._serialized_start = 4680
    _globals['_MAKEDIRECTORYRESPONSE']._serialized_end = 4703
    _globals['_REMOVEDIRECTORYREQUEST']._serialized_start = 4705
    _globals['_REMOVEDIRECTORYREQUEST']._serialized_end = 4810
    _globals['_MOVEDIRECTORYREQUEST']._serialized_start = 4812
    _globals['_MOVEDIRECTORYREQUEST']._serialized_end = 4938
    _globals['_MOVEDIRECTORYRESPONSE']._serialized_start = 4940
    _globals['_MOVEDIRECTORYRESPONSE']._serialized_end = 4963
    _globals['_READFILEREQUEST']._serialized_start = 4965
    _globals['_READFILEREQUEST']._serialized_end = 5063
    _globals['_READFILERESPONSE']._serialized_start = 5065
    _globals['_READFILERESPONSE']._serialized_end = 5106
    _globals['_REMOVEFILEREQUEST']._serialized_start = 5108
    _globals['_REMOVEFILEREQUEST']._serialized_end = 5208
    _globals['_MOVEFILEREQUEST']._serialized_start = 5210
    _globals['_MOVEFILEREQUEST']._serialized_end = 5331
    _globals['_MOVEFILERESPONSE']._serialized_start = 5333
    _globals['_MOVEFILERESPONSE']._serialized_end = 5351
    _globals['_WRITEFILEREQUEST']._serialized_start = 5353
    _globals['_WRITEFILEREQUEST']._serialized_end = 5475
    _globals['_WRITEFILERESPONSE']._serialized_start = 5477
    _globals['_WRITEFILERESPONSE']._serialized_end = 5496
    _globals['_INSTALLNPMPACKAGESREQUEST']._serialized_start = 5498
    _globals['_INSTALLNPMPACKAGESREQUEST']._serialized_end = 5587
    _globals['_INSTALLNPMPACKAGESRESPONSE']._serialized_start = 5589
    _globals['_INSTALLNPMPACKAGESRESPONSE']._serialized_end = 5617
    _globals['_COMPILATIONRESULT']._serialized_start = 5620
    _globals['_COMPILATIONRESULT']._serialized_end = 6697
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG']._serialized_start = 6003
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG']._serialized_end = 6380
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG_VARSENTRY']._serialized_start = 6337
    _globals['_COMPILATIONRESULT_CODECOMPILATIONCONFIG_VARSENTRY']._serialized_end = 6380
    _globals['_COMPILATIONRESULT_COMPILATIONERROR']._serialized_start = 6383
    _globals['_COMPILATIONRESULT_COMPILATIONERROR']._serialized_end = 6530
    _globals['_LISTCOMPILATIONRESULTSREQUEST']._serialized_start = 6700
    _globals['_LISTCOMPILATIONRESULTSREQUEST']._serialized_end = 6840
    _globals['_LISTCOMPILATIONRESULTSRESPONSE']._serialized_start = 6843
    _globals['_LISTCOMPILATIONRESULTSRESPONSE']._serialized_end = 7001
    _globals['_GETCOMPILATIONRESULTREQUEST']._serialized_start = 7003
    _globals['_GETCOMPILATIONRESULTREQUEST']._serialized_end = 7097
    _globals['_CREATECOMPILATIONRESULTREQUEST']._serialized_start = 7100
    _globals['_CREATECOMPILATIONRESULTREQUEST']._serialized_end = 7276
    _globals['_TARGET']._serialized_start = 7278
    _globals['_TARGET']._serialized_end = 7334
    _globals['_RELATIONDESCRIPTOR']._serialized_start = 7337
    _globals['_RELATIONDESCRIPTOR']._serialized_end = 7701
    _globals['_RELATIONDESCRIPTOR_COLUMNDESCRIPTOR']._serialized_start = 7563
    _globals['_RELATIONDESCRIPTOR_COLUMNDESCRIPTOR']._serialized_end = 7646
    _globals['_RELATIONDESCRIPTOR_BIGQUERYLABELSENTRY']._serialized_start = 7648
    _globals['_RELATIONDESCRIPTOR_BIGQUERYLABELSENTRY']._serialized_end = 7701
    _globals['_COMPILATIONRESULTACTION']._serialized_start = 7704
    _globals['_COMPILATIONRESULTACTION']._serialized_end = 9980
    _globals['_COMPILATIONRESULTACTION_RELATION']._serialized_start = 8229
    _globals['_COMPILATIONRESULTACTION_RELATION']._serialized_end = 9352
    _globals['_COMPILATIONRESULTACTION_RELATION_INCREMENTALTABLECONFIG']._serialized_start = 8964
    _globals['_COMPILATIONRESULTACTION_RELATION_INCREMENTALTABLECONFIG']._serialized_end = 9180
    _globals['_COMPILATIONRESULTACTION_RELATION_ADDITIONALOPTIONSENTRY']._serialized_start = 9182
    _globals['_COMPILATIONRESULTACTION_RELATION_ADDITIONALOPTIONSENTRY']._serialized_end = 9238
    _globals['_COMPILATIONRESULTACTION_RELATION_RELATIONTYPE']._serialized_start = 9240
    _globals['_COMPILATIONRESULTACTION_RELATION_RELATIONTYPE']._serialized_end = 9352
    _globals['_COMPILATIONRESULTACTION_OPERATIONS']._serialized_start = 9355
    _globals['_COMPILATIONRESULTACTION_OPERATIONS']._serialized_end = 9585
    _globals['_COMPILATIONRESULTACTION_ASSERTION']._serialized_start = 9588
    _globals['_COMPILATIONRESULTACTION_ASSERTION']._serialized_end = 9865
    _globals['_COMPILATIONRESULTACTION_DECLARATION']._serialized_start = 9867
    _globals['_COMPILATIONRESULTACTION_DECLARATION']._serialized_end = 9961
    _globals['_QUERYCOMPILATIONRESULTACTIONSREQUEST']._serialized_start = 9983
    _globals['_QUERYCOMPILATIONRESULTACTIONSREQUEST']._serialized_end = 10156
    _globals['_QUERYCOMPILATIONRESULTACTIONSRESPONSE']._serialized_start = 10159
    _globals['_QUERYCOMPILATIONRESULTACTIONSRESPONSE']._serialized_end = 10316
    _globals['_WORKFLOWINVOCATION']._serialized_start = 10319
    _globals['_WORKFLOWINVOCATION']._serialized_end = 11200
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG']._serialized_start = 10674
    _globals['_WORKFLOWINVOCATION_INVOCATIONCONFIG']._serialized_end = 10938
    _globals['_WORKFLOWINVOCATION_STATE']._serialized_start = 10940
    _globals['_WORKFLOWINVOCATION_STATE']._serialized_end = 11040
    _globals['_LISTWORKFLOWINVOCATIONSREQUEST']._serialized_start = 11203
    _globals['_LISTWORKFLOWINVOCATIONSREQUEST']._serialized_end = 11344
    _globals['_LISTWORKFLOWINVOCATIONSRESPONSE']._serialized_start = 11347
    _globals['_LISTWORKFLOWINVOCATIONSRESPONSE']._serialized_end = 11508
    _globals['_GETWORKFLOWINVOCATIONREQUEST']._serialized_start = 11510
    _globals['_GETWORKFLOWINVOCATIONREQUEST']._serialized_end = 11606
    _globals['_CREATEWORKFLOWINVOCATIONREQUEST']._serialized_start = 11609
    _globals['_CREATEWORKFLOWINVOCATIONREQUEST']._serialized_end = 11788
    _globals['_DELETEWORKFLOWINVOCATIONREQUEST']._serialized_start = 11790
    _globals['_DELETEWORKFLOWINVOCATIONREQUEST']._serialized_end = 11889
    _globals['_CANCELWORKFLOWINVOCATIONREQUEST']._serialized_start = 11891
    _globals['_CANCELWORKFLOWINVOCATIONREQUEST']._serialized_end = 11990
    _globals['_WORKFLOWINVOCATIONACTION']._serialized_start = 11993
    _globals['_WORKFLOWINVOCATIONACTION']._serialized_end = 12569
    _globals['_WORKFLOWINVOCATIONACTION_BIGQUERYACTION']._serialized_start = 12424
    _globals['_WORKFLOWINVOCATIONACTION_BIGQUERYACTION']._serialized_end = 12465
    _globals['_WORKFLOWINVOCATIONACTION_STATE']._serialized_start = 12467
    _globals['_WORKFLOWINVOCATIONACTION_STATE']._serialized_end = 12569
    _globals['_QUERYWORKFLOWINVOCATIONACTIONSREQUEST']._serialized_start = 12572
    _globals['_QUERYWORKFLOWINVOCATIONACTIONSREQUEST']._serialized_end = 12726
    _globals['_QUERYWORKFLOWINVOCATIONACTIONSRESPONSE']._serialized_start = 12729
    _globals['_QUERYWORKFLOWINVOCATIONACTIONSRESPONSE']._serialized_end = 12889
    _globals['_DATAFORM']._serialized_start = 12892
    _globals['_DATAFORM']._serialized_end = 21001