[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "evoagent"
version = "0.0.4"
description = "An orchestration framework for evolving autonomous AI agents"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai",
    "anthropic",
    "groq",
    "python-dotenv",
    "qdrant-client",
    "requests",
    "PyPDF2",
    "python-docx",
    "soundfile",
    "tiktoken",
    "faiss-cpu",
    "pydantic",
    "fastapi",
    "uvicorn",
    "pymupdf",
    "pandas",
    "numpy",
    "matplotlib",
    "langchain",
    "llama-index",
    "chainlit",
    "phidata",
    "huggingface_hub"
]

[tool.setuptools.packages.find]
where = ["."]  
include = ["evoagent*"]
