"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 28, 1, '', 'google/cloud/filestore/v1beta1/cloud_filestore_service.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.cloud.common import operation_metadata_pb2 as google_dot_cloud_dot_common_dot_operation__metadata__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<google/cloud/filestore/v1beta1/cloud_filestore_service.proto\x12\x1egoogle.cloud.filestore.v1beta1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a,google/cloud/common/operation_metadata.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto"\x8a\x03\n\rNetworkConfig\x12\x0f\n\x07network\x18\x01 \x01(\t\x12H\n\x05modes\x18\x03 \x03(\x0e29.google.cloud.filestore.v1beta1.NetworkConfig.AddressMode\x12\x19\n\x11reserved_ip_range\x18\x04 \x01(\t\x12\x19\n\x0cip_addresses\x18\x05 \x03(\tB\x03\xe0A\x03\x12O\n\x0cconnect_mode\x18\x06 \x01(\x0e29.google.cloud.filestore.v1beta1.NetworkConfig.ConnectMode":\n\x0bAddressMode\x12\x1c\n\x18ADDRESS_MODE_UNSPECIFIED\x10\x00\x12\r\n\tMODE_IPV4\x10\x01"[\n\x0bConnectMode\x12\x1c\n\x18CONNECT_MODE_UNSPECIFIED\x10\x00\x12\x12\n\x0eDIRECT_PEERING\x10\x01\x12\x1a\n\x16PRIVATE_SERVICE_ACCESS\x10\x02"\xc6\x01\n\x0fFileShareConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bcapacity_gb\x18\x02 \x01(\x03\x128\n\rsource_backup\x18\t \x01(\tB\x1f\xfaA\x1c\n\x1afile.googleapis.com/BackupH\x00\x12L\n\x12nfs_export_options\x18\x08 \x03(\x0b20.google.cloud.filestore.v1beta1.NfsExportOptionsB\x08\n\x06source"\xc3\x04\n\x10NfsExportOptions\x12\x11\n\tip_ranges\x18\x01 \x03(\t\x12P\n\x0baccess_mode\x18\x02 \x01(\x0e2;.google.cloud.filestore.v1beta1.NfsExportOptions.AccessMode\x12P\n\x0bsquash_mode\x18\x03 \x01(\x0e2;.google.cloud.filestore.v1beta1.NfsExportOptions.SquashMode\x12\x10\n\x08anon_uid\x18\x04 \x01(\x03\x12\x10\n\x08anon_gid\x18\x05 \x01(\x03\x12Y\n\x10security_flavors\x18\x06 \x03(\x0e2?.google.cloud.filestore.v1beta1.NfsExportOptions.SecurityFlavor"H\n\nAccessMode\x12\x1b\n\x17ACCESS_MODE_UNSPECIFIED\x10\x00\x12\r\n\tREAD_ONLY\x10\x01\x12\x0e\n\nREAD_WRITE\x10\x02"N\n\nSquashMode\x12\x1b\n\x17SQUASH_MODE_UNSPECIFIED\x10\x00\x12\x12\n\x0eNO_ROOT_SQUASH\x10\x01\x12\x0f\n\x0bROOT_SQUASH\x10\x02"_\n\x0eSecurityFlavor\x12\x1f\n\x1bSECURITY_FLAVOR_UNSPECIFIED\x10\x00\x12\x0c\n\x08AUTH_SYS\x10\x01\x12\x08\n\x04KRB5\x10\x02\x12\t\n\x05KRB5I\x10\x03\x12\t\n\x05KRB5P\x10\x04"@\n\x1cManagedActiveDirectoryConfig\x12\x0e\n\x06domain\x18\x01 \x01(\t\x12\x10\n\x08computer\x18\x02 \x01(\t"\x85\x01\n\x17DirectoryServicesConfig\x12`\n\x18managed_active_directory\x18\x01 \x01(\x0b2<.google.cloud.filestore.v1beta1.ManagedActiveDirectoryConfigH\x00B\x08\n\x06config"\xbc\x0c\n\x08Instance\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x13\n\x0bdescription\x18\x02 \x01(\t\x12B\n\x05state\x18\x05 \x01(\x0e2..google.cloud.filestore.v1beta1.Instance.StateB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x06 \x01(\tB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x07 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12;\n\x04tier\x18\x08 \x01(\x0e2-.google.cloud.filestore.v1beta1.Instance.Tier\x12D\n\x06labels\x18\t \x03(\x0b24.google.cloud.filestore.v1beta1.Instance.LabelsEntry\x12D\n\x0bfile_shares\x18\n \x03(\x0b2/.google.cloud.filestore.v1beta1.FileShareConfig\x12?\n\x08networks\x18\x0b \x03(\x0b2-.google.cloud.filestore.v1beta1.NetworkConfig\x12\x0c\n\x04etag\x18\x0c \x01(\t\x126\n\rsatisfies_pzs\x18\r \x01(\x0b2\x1a.google.protobuf.BoolValueB\x03\xe0A\x03\x12\x1a\n\rsatisfies_pzi\x18\x1a \x01(\x08B\x03\xe0A\x03\x12\x14\n\x0ckms_key_name\x18\x0e \x01(\t\x12Z\n\x12suspension_reasons\x18\x0f \x03(\x0e29.google.cloud.filestore.v1beta1.Instance.SuspensionReasonB\x03\xe0A\x03\x12\x1c\n\x0fmax_capacity_gb\x18\x10 \x01(\x03B\x03\xe0A\x03\x12"\n\x15capacity_step_size_gb\x18\x11 \x01(\x03B\x03\xe0A\x03\x12\x17\n\x0fmax_share_count\x18\x12 \x01(\x03\x12\x13\n\x0bcapacity_gb\x18\x13 \x01(\x03\x12\x1b\n\x13multi_share_enabled\x18\x14 \x01(\x08\x12L\n\x08protocol\x18\x15 \x01(\x0e25.google.cloud.filestore.v1beta1.Instance.FileProtocolB\x03\xe0A\x05\x12S\n\x12directory_services\x18\x18 \x01(\x0b27.google.cloud.filestore.v1beta1.DirectoryServicesConfig\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"\xaa\x01\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\t\n\x05READY\x10\x02\x12\r\n\tREPAIRING\x10\x03\x12\x0c\n\x08DELETING\x10\x04\x12\t\n\x05ERROR\x10\x06\x12\r\n\tRESTORING\x10\x07\x12\r\n\tSUSPENDED\x10\x08\x12\r\n\tREVERTING\x10\t\x12\x0e\n\nSUSPENDING\x10\n\x12\x0c\n\x08RESUMING\x10\x0b"\x92\x01\n\x04Tier\x12\x14\n\x10TIER_UNSPECIFIED\x10\x00\x12\x0c\n\x08STANDARD\x10\x01\x12\x0b\n\x07PREMIUM\x10\x02\x12\r\n\tBASIC_HDD\x10\x03\x12\r\n\tBASIC_SSD\x10\x04\x12\x12\n\x0eHIGH_SCALE_SSD\x10\x06\x12\x0e\n\nENTERPRISE\x10\x07\x12\t\n\x05ZONAL\x10\x08\x12\x0c\n\x08REGIONAL\x10\t"H\n\x10SuspensionReason\x12!\n\x1dSUSPENSION_REASON_UNSPECIFIED\x10\x00\x12\x11\n\rKMS_KEY_ISSUE\x10\x01"G\n\x0cFileProtocol\x12\x1d\n\x19FILE_PROTOCOL_UNSPECIFIED\x10\x00\x12\n\n\x06NFS_V3\x10\x01\x12\x0c\n\x08NFS_V4_1\x10\x02:_\xeaA\\\n\x1cfile.googleapis.com/Instance\x12<projects/{project}/locations/{location}/instances/{instance}"\xad\x01\n\x15CreateInstanceRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x18\n\x0binstance_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12?\n\x08instance\x18\x03 \x01(\x0b2(.google.cloud.filestore.v1beta1.InstanceB\x03\xe0A\x02"H\n\x12GetInstanceRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance"\x8e\x01\n\x15UpdateInstanceRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12?\n\x08instance\x18\x02 \x01(\x0b2(.google.cloud.filestore.v1beta1.InstanceB\x03\xe0A\x02"\xe9\x01\n\x16RestoreInstanceRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x17\n\nfile_share\x18\x02 \x01(\tB\x03\xe0A\x02\x12>\n\x0fsource_snapshot\x18\x03 \x01(\tB#\x18\x01\xfaA\x1e\n\x1cfile.googleapis.com/SnapshotH\x00\x128\n\rsource_backup\x18\x04 \x01(\tB\x1f\xfaA\x1c\n\x1afile.googleapis.com/BackupH\x00B\x08\n\x06source"l\n\x15RevertInstanceRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x1f\n\x12target_snapshot_id\x18\x02 \x01(\tB\x03\xe0A\x02"Z\n\x15DeleteInstanceRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\r\n\x05force\x18\x02 \x01(\x08"\x9a\x01\n\x14ListInstancesRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t"\x82\x01\n\x15ListInstancesResponse\x12;\n\tinstances\x18\x01 \x03(\x0b2(.google.cloud.filestore.v1beta1.Instance\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\x82\x04\n\x08Snapshot\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x13\n\x0bdescription\x18\x02 \x01(\t\x12B\n\x05state\x18\x03 \x01(\x0e2..google.cloud.filestore.v1beta1.Snapshot.StateB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12D\n\x06labels\x18\x05 \x03(\x0b24.google.cloud.filestore.v1beta1.Snapshot.LabelsEntry\x12"\n\x15filesystem_used_bytes\x18\x0c \x01(\x03B\x03\xe0A\x03\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"E\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\t\n\x05READY\x10\x03\x12\x0c\n\x08DELETING\x10\x04:t\xeaAq\n\x1cfile.googleapis.com/Snapshot\x12Qprojects/{project}/locations/{location}/instances/{instance}/snapshots/{snapshot}"\xa8\x01\n\x15CreateSnapshotRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x18\n\x0bsnapshot_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12?\n\x08snapshot\x18\x03 \x01(\x0b2(.google.cloud.filestore.v1beta1.SnapshotB\x03\xe0A\x02"H\n\x12GetSnapshotRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Snapshot"K\n\x15DeleteSnapshotRequest\x122\n\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Snapshot"\x8e\x01\n\x15UpdateSnapshotRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x12?\n\x08snapshot\x18\x02 \x01(\x0b2(.google.cloud.filestore.v1beta1.SnapshotB\x03\xe0A\x02"\x95\x01\n\x14ListSnapshotsRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t"m\n\x15ListSnapshotsResponse\x12;\n\tsnapshots\x18\x01 \x03(\x0b2(.google.cloud.filestore.v1beta1.Snapshot\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"\xc5\x06\n\x06Backup\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x13\n\x0bdescription\x18\x02 \x01(\t\x12@\n\x05state\x18\x03 \x01(\x0e2,.google.cloud.filestore.v1beta1.Backup.StateB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12B\n\x06labels\x18\x05 \x03(\x0b22.google.cloud.filestore.v1beta1.Backup.LabelsEntry\x12\x18\n\x0bcapacity_gb\x18\x06 \x01(\x03B\x03\xe0A\x03\x12\x1a\n\rstorage_bytes\x18\x07 \x01(\x03B\x03\xe0A\x03\x12:\n\x0fsource_instance\x18\x08 \x01(\tB!\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x19\n\x11source_file_share\x18\t \x01(\t\x12P\n\x14source_instance_tier\x18\n \x01(\x0e2-.google.cloud.filestore.v1beta1.Instance.TierB\x03\xe0A\x03\x12\x1b\n\x0edownload_bytes\x18\x0b \x01(\x03B\x03\xe0A\x03\x126\n\rsatisfies_pzs\x18\x0c \x01(\x0b2\x1a.google.protobuf.BoolValueB\x03\xe0A\x03\x12\x1a\n\rsatisfies_pzi\x18\x0e \x01(\x08B\x03\xe0A\x03\x12\x19\n\x0ckms_key_name\x18\r \x01(\tB\x03\xe0A\x05\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"b\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\x0e\n\nFINALIZING\x10\x02\x12\t\n\x05READY\x10\x03\x12\x0c\n\x08DELETING\x10\x04\x12\x0b\n\x07INVALID\x10\x05:Y\xeaAV\n\x1afile.googleapis.com/Backup\x128projects/{project}/locations/{location}/backups/{backup}"\xa5\x01\n\x13CreateBackupRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12;\n\x06backup\x18\x02 \x01(\x0b2&.google.cloud.filestore.v1beta1.BackupB\x03\xe0A\x02\x12\x16\n\tbackup_id\x18\x03 \x01(\tB\x03\xe0A\x02"G\n\x13DeleteBackupRequest\x120\n\x04name\x18\x01 \x01(\tB"\xe0A\x02\xfaA\x1c\n\x1afile.googleapis.com/Backup"\x88\x01\n\x13UpdateBackupRequest\x12;\n\x06backup\x18\x01 \x01(\x0b2&.google.cloud.filestore.v1beta1.BackupB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"D\n\x10GetBackupRequest\x120\n\x04name\x18\x01 \x01(\tB"\xe0A\x02\xfaA\x1c\n\x1afile.googleapis.com/Backup"\x98\x01\n\x12ListBackupsRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t"|\n\x13ListBackupsResponse\x127\n\x07backups\x18\x01 \x03(\x0b2&.google.cloud.filestore.v1beta1.Backup\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\x83\x05\n\x05Share\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x12\n\nmount_name\x18\x02 \x01(\t\x12\x13\n\x0bdescription\x18\x03 \x01(\t\x12\x13\n\x0bcapacity_gb\x18\x04 \x01(\x03\x12L\n\x12nfs_export_options\x18\x05 \x03(\x0b20.google.cloud.filestore.v1beta1.NfsExportOptions\x12?\n\x05state\x18\x06 \x01(\x0e2+.google.cloud.filestore.v1beta1.Share.StateB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x07 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12A\n\x06labels\x18\x08 \x03(\x0b21.google.cloud.filestore.v1beta1.Share.LabelsEntry\x124\n\x06backup\x18\t \x01(\tB"\xe0A\x05\xfaA\x1c\n\x1afile.googleapis.com/BackupH\x00\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"E\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\t\n\x05READY\x10\x03\x12\x0c\n\x08DELETING\x10\x04:k\xeaAh\n\x19file.googleapis.com/Share\x12Kprojects/{project}/locations/{location}/instances/{instance}/shares/{share}B\x08\n\x06source"\x9c\x01\n\x12CreateShareRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x15\n\x08share_id\x18\x02 \x01(\tB\x03\xe0A\x02\x129\n\x05share\x18\x03 \x01(\x0b2%.google.cloud.filestore.v1beta1.ShareB\x03\xe0A\x02"B\n\x0fGetShareRequest\x12/\n\x04name\x18\x01 \x01(\tB!\xe0A\x02\xfaA\x1b\n\x19file.googleapis.com/Share"E\n\x12DeleteShareRequest\x12/\n\x04name\x18\x01 \x01(\tB!\xe0A\x02\xfaA\x1b\n\x19file.googleapis.com/Share"\x92\x01\n\x11ListSharesRequest\x124\n\x06parent\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t"y\n\x12ListSharesResponse\x125\n\x06shares\x18\x01 \x03(\x0b2%.google.cloud.filestore.v1beta1.Share\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\x85\x01\n\x12UpdateShareRequest\x129\n\x05share\x18\x01 \x01(\x0b2%.google.cloud.filestore.v1beta1.ShareB\x03\xe0A\x02\x124\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x022\xc8\'\n\x15CloudFilestoreManager\x12\xc1\x01\n\rListInstances\x124.google.cloud.filestore.v1beta1.ListInstancesRequest\x1a5.google.cloud.filestore.v1beta1.ListInstancesResponse"C\xdaA\x06parent\x82\xd3\xe4\x93\x024\x122/v1beta1/{parent=projects/*/locations/*}/instances\x12\xae\x01\n\x0bGetInstance\x122.google.cloud.filestore.v1beta1.GetInstanceRequest\x1a(.google.cloud.filestore.v1beta1.Instance"A\xdaA\x04name\x82\xd3\xe4\x93\x024\x122/v1beta1/{name=projects/*/locations/*/instances/*}\x12\xff\x01\n\x0eCreateInstance\x125.google.cloud.filestore.v1beta1.CreateInstanceRequest\x1a\x1d.google.longrunning.Operation"\x96\x01\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\xdaA\x1bparent,instance,instance_id\x82\xd3\xe4\x93\x02>"2/v1beta1/{parent=projects/*/locations/*}/instances:\x08instance\x12\x81\x02\n\x0eUpdateInstance\x125.google.cloud.filestore.v1beta1.UpdateInstanceRequest\x1a\x1d.google.longrunning.Operation"\x98\x01\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\xdaA\x14instance,update_mask\x82\xd3\xe4\x93\x02G2;/v1beta1/{instance.name=projects/*/locations/*/instances/*}:\x08instance\x12\xe3\x01\n\x0fRestoreInstance\x126.google.cloud.filestore.v1beta1.RestoreInstanceRequest\x1a\x1d.google.longrunning.Operation"y\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\x82\xd3\xe4\x93\x02?":/v1beta1/{name=projects/*/locations/*/instances/*}:restore:\x01*\x12\xe0\x01\n\x0eRevertInstance\x125.google.cloud.filestore.v1beta1.RevertInstanceRequest\x1a\x1d.google.longrunning.Operation"x\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\x82\xd3\xe4\x93\x02>"9/v1beta1/{name=projects/*/locations/*/instances/*}:revert:\x01*\x12\xeb\x01\n\x0eDeleteInstance\x125.google.cloud.filestore.v1beta1.DeleteInstanceRequest\x1a\x1d.google.longrunning.Operation"\x82\x01\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x024*2/v1beta1/{name=projects/*/locations/*/instances/*}\x12\xcd\x01\n\rListSnapshots\x124.google.cloud.filestore.v1beta1.ListSnapshotsRequest\x1a5.google.cloud.filestore.v1beta1.ListSnapshotsResponse"O\xdaA\x06parent\x82\xd3\xe4\x93\x02@\x12>/v1beta1/{parent=projects/*/locations/*/instances/*}/snapshots\x12\xba\x01\n\x0bGetSnapshot\x122.google.cloud.filestore.v1beta1.GetSnapshotRequest\x1a(.google.cloud.filestore.v1beta1.Snapshot"M\xdaA\x04name\x82\xd3\xe4\x93\x02@\x12>/v1beta1/{name=projects/*/locations/*/instances/*/snapshots/*}\x12\x8b\x02\n\x0eCreateSnapshot\x125.google.cloud.filestore.v1beta1.CreateSnapshotRequest\x1a\x1d.google.longrunning.Operation"\xa2\x01\xcaA1\n\x08Snapshot\x12%google.cloud.common.OperationMetadata\xdaA\x1bparent,snapshot,snapshot_id\x82\xd3\xe4\x93\x02J">/v1beta1/{parent=projects/*/locations/*/instances/*}/snapshots:\x08snapshot\x12\xf7\x01\n\x0eDeleteSnapshot\x125.google.cloud.filestore.v1beta1.DeleteSnapshotRequest\x1a\x1d.google.longrunning.Operation"\x8e\x01\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02@*>/v1beta1/{name=projects/*/locations/*/instances/*/snapshots/*}\x12\x8d\x02\n\x0eUpdateSnapshot\x125.google.cloud.filestore.v1beta1.UpdateSnapshotRequest\x1a\x1d.google.longrunning.Operation"\xa4\x01\xcaA1\n\x08Snapshot\x12%google.cloud.common.OperationMetadata\xdaA\x14snapshot,update_mask\x82\xd3\xe4\x93\x02S2G/v1beta1/{snapshot.name=projects/*/locations/*/instances/*/snapshots/*}:\x08snapshot\x12\xb9\x01\n\x0bListBackups\x122.google.cloud.filestore.v1beta1.ListBackupsRequest\x1a3.google.cloud.filestore.v1beta1.ListBackupsResponse"A\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1beta1/{parent=projects/*/locations/*}/backups\x12\xa6\x01\n\tGetBackup\x120.google.cloud.filestore.v1beta1.GetBackupRequest\x1a&.google.cloud.filestore.v1beta1.Backup"?\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1beta1/{name=projects/*/locations/*/backups/*}\x12\xf1\x01\n\x0cCreateBackup\x123.google.cloud.filestore.v1beta1.CreateBackupRequest\x1a\x1d.google.longrunning.Operation"\x8c\x01\xcaA/\n\x06Backup\x12%google.cloud.common.OperationMetadata\xdaA\x17parent,backup,backup_id\x82\xd3\xe4\x93\x02:"0/v1beta1/{parent=projects/*/locations/*}/backups:\x06backup\x12\xe5\x01\n\x0cDeleteBackup\x123.google.cloud.filestore.v1beta1.DeleteBackupRequest\x1a\x1d.google.longrunning.Operation"\x80\x01\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x022*0/v1beta1/{name=projects/*/locations/*/backups/*}\x12\xf3\x01\n\x0cUpdateBackup\x123.google.cloud.filestore.v1beta1.UpdateBackupRequest\x1a\x1d.google.longrunning.Operation"\x8e\x01\xcaA/\n\x06Backup\x12%google.cloud.common.OperationMetadata\xdaA\x12backup,update_mask\x82\xd3\xe4\x93\x02A27/v1beta1/{backup.name=projects/*/locations/*/backups/*}:\x06backup\x12\xc1\x01\n\nListShares\x121.google.cloud.filestore.v1beta1.ListSharesRequest\x1a2.google.cloud.filestore.v1beta1.ListSharesResponse"L\xdaA\x06parent\x82\xd3\xe4\x93\x02=\x12;/v1beta1/{parent=projects/*/locations/*/instances/*}/shares\x12\xae\x01\n\x08GetShare\x12/.google.cloud.filestore.v1beta1.GetShareRequest\x1a%.google.cloud.filestore.v1beta1.Share"J\xdaA\x04name\x82\xd3\xe4\x93\x02=\x12;/v1beta1/{name=projects/*/locations/*/instances/*/shares/*}\x12\xf6\x01\n\x0bCreateShare\x122.google.cloud.filestore.v1beta1.CreateShareRequest\x1a\x1d.google.longrunning.Operation"\x93\x01\xcaA.\n\x05Share\x12%google.cloud.common.OperationMetadata\xdaA\x15parent,share,share_id\x82\xd3\xe4\x93\x02D";/v1beta1/{parent=projects/*/locations/*/instances/*}/shares:\x05share\x12\xee\x01\n\x0bDeleteShare\x122.google.cloud.filestore.v1beta1.DeleteShareRequest\x1a\x1d.google.longrunning.Operation"\x8b\x01\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02=*;/v1beta1/{name=projects/*/locations/*/instances/*/shares/*}\x12\xf8\x01\n\x0bUpdateShare\x122.google.cloud.filestore.v1beta1.UpdateShareRequest\x1a\x1d.google.longrunning.Operation"\x95\x01\xcaA.\n\x05Share\x12%google.cloud.common.OperationMetadata\xdaA\x11share,update_mask\x82\xd3\xe4\x93\x02J2A/v1beta1/{share.name=projects/*/locations/*/instances/*/shares/*}:\x05share\x1aG\xcaA\x13file.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xc6\x01\n"com.google.cloud.filestore.v1beta1B\x1aCloudFilestoreServiceProtoP\x01Z@cloud.google.com/go/filestore/apiv1beta1/filestorepb;filestorepb\xaa\x02\x1eGoogle.Cloud.Filestore.V1Beta1\xca\x02\x1eGoogle\\Cloud\\Filestore\\V1beta1b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.filestore.v1beta1.cloud_filestore_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n"com.google.cloud.filestore.v1beta1B\x1aCloudFilestoreServiceProtoP\x01Z@cloud.google.com/go/filestore/apiv1beta1/filestorepb;filestorepb\xaa\x02\x1eGoogle.Cloud.Filestore.V1Beta1\xca\x02\x1eGoogle\\Cloud\\Filestore\\V1beta1'
    _globals['_NETWORKCONFIG'].fields_by_name['ip_addresses']._loaded_options = None
    _globals['_NETWORKCONFIG'].fields_by_name['ip_addresses']._serialized_options = b'\xe0A\x03'
    _globals['_FILESHARECONFIG'].fields_by_name['source_backup']._loaded_options = None
    _globals['_FILESHARECONFIG'].fields_by_name['source_backup']._serialized_options = b'\xfaA\x1c\n\x1afile.googleapis.com/Backup'
    _globals['_INSTANCE_LABELSENTRY']._loaded_options = None
    _globals['_INSTANCE_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_INSTANCE'].fields_by_name['name']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['state']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['status_message']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['create_time']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['satisfies_pzs']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['satisfies_pzs']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['satisfies_pzi']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['satisfies_pzi']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['suspension_reasons']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['suspension_reasons']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['max_capacity_gb']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['max_capacity_gb']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['capacity_step_size_gb']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['capacity_step_size_gb']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['protocol']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['protocol']._serialized_options = b'\xe0A\x05'
    _globals['_INSTANCE']._loaded_options = None
    _globals['_INSTANCE']._serialized_options = b'\xeaA\\\n\x1cfile.googleapis.com/Instance\x12<projects/{project}/locations/{location}/instances/{instance}'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x02'
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_UPDATEINSTANCEREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x02'
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['file_share']._loaded_options = None
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['file_share']._serialized_options = b'\xe0A\x02'
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['source_snapshot']._loaded_options = None
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['source_snapshot']._serialized_options = b'\x18\x01\xfaA\x1e\n\x1cfile.googleapis.com/Snapshot'
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['source_backup']._loaded_options = None
    _globals['_RESTOREINSTANCEREQUEST'].fields_by_name['source_backup']._serialized_options = b'\xfaA\x1c\n\x1afile.googleapis.com/Backup'
    _globals['_REVERTINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_REVERTINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_REVERTINSTANCEREQUEST'].fields_by_name['target_snapshot_id']._loaded_options = None
    _globals['_REVERTINSTANCEREQUEST'].fields_by_name['target_snapshot_id']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_SNAPSHOT_LABELSENTRY']._loaded_options = None
    _globals['_SNAPSHOT_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_SNAPSHOT'].fields_by_name['name']._loaded_options = None
    _globals['_SNAPSHOT'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_SNAPSHOT'].fields_by_name['state']._loaded_options = None
    _globals['_SNAPSHOT'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_SNAPSHOT'].fields_by_name['create_time']._loaded_options = None
    _globals['_SNAPSHOT'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_SNAPSHOT'].fields_by_name['filesystem_used_bytes']._loaded_options = None
    _globals['_SNAPSHOT'].fields_by_name['filesystem_used_bytes']._serialized_options = b'\xe0A\x03'
    _globals['_SNAPSHOT']._loaded_options = None
    _globals['_SNAPSHOT']._serialized_options = b'\xeaAq\n\x1cfile.googleapis.com/Snapshot\x12Qprojects/{project}/locations/{location}/instances/{instance}/snapshots/{snapshot}'
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['snapshot_id']._loaded_options = None
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['snapshot_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['snapshot']._loaded_options = None
    _globals['_CREATESNAPSHOTREQUEST'].fields_by_name['snapshot']._serialized_options = b'\xe0A\x02'
    _globals['_GETSNAPSHOTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSNAPSHOTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Snapshot'
    _globals['_DELETESNAPSHOTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESNAPSHOTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Snapshot'
    _globals['_UPDATESNAPSHOTREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATESNAPSHOTREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESNAPSHOTREQUEST'].fields_by_name['snapshot']._loaded_options = None
    _globals['_UPDATESNAPSHOTREQUEST'].fields_by_name['snapshot']._serialized_options = b'\xe0A\x02'
    _globals['_LISTSNAPSHOTSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSNAPSHOTSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_BACKUP_LABELSENTRY']._loaded_options = None
    _globals['_BACKUP_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_BACKUP'].fields_by_name['name']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['state']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['create_time']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['capacity_gb']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['capacity_gb']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['storage_bytes']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['storage_bytes']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['source_instance']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['source_instance']._serialized_options = b'\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_BACKUP'].fields_by_name['source_instance_tier']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['source_instance_tier']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['download_bytes']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['download_bytes']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['satisfies_pzs']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['satisfies_pzs']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['satisfies_pzi']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['satisfies_pzi']._serialized_options = b'\xe0A\x03'
    _globals['_BACKUP'].fields_by_name['kms_key_name']._loaded_options = None
    _globals['_BACKUP'].fields_by_name['kms_key_name']._serialized_options = b'\xe0A\x05'
    _globals['_BACKUP']._loaded_options = None
    _globals['_BACKUP']._serialized_options = b'\xeaAV\n\x1afile.googleapis.com/Backup\x128projects/{project}/locations/{location}/backups/{backup}'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup_id']._loaded_options = None
    _globals['_CREATEBACKUPREQUEST'].fields_by_name['backup_id']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEBACKUPREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1c\n\x1afile.googleapis.com/Backup'
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['backup']._loaded_options = None
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['backup']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEBACKUPREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_GETBACKUPREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETBACKUPREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1c\n\x1afile.googleapis.com/Backup'
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTBACKUPSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_SHARE_LABELSENTRY']._loaded_options = None
    _globals['_SHARE_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_SHARE'].fields_by_name['name']._loaded_options = None
    _globals['_SHARE'].fields_by_name['name']._serialized_options = b'\xe0A\x03'
    _globals['_SHARE'].fields_by_name['state']._loaded_options = None
    _globals['_SHARE'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_SHARE'].fields_by_name['create_time']._loaded_options = None
    _globals['_SHARE'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_SHARE'].fields_by_name['backup']._loaded_options = None
    _globals['_SHARE'].fields_by_name['backup']._serialized_options = b'\xe0A\x05\xfaA\x1c\n\x1afile.googleapis.com/Backup'
    _globals['_SHARE']._loaded_options = None
    _globals['_SHARE']._serialized_options = b'\xeaAh\n\x19file.googleapis.com/Share\x12Kprojects/{project}/locations/{location}/instances/{instance}/shares/{share}'
    _globals['_CREATESHAREREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATESHAREREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_CREATESHAREREQUEST'].fields_by_name['share_id']._loaded_options = None
    _globals['_CREATESHAREREQUEST'].fields_by_name['share_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATESHAREREQUEST'].fields_by_name['share']._loaded_options = None
    _globals['_CREATESHAREREQUEST'].fields_by_name['share']._serialized_options = b'\xe0A\x02'
    _globals['_GETSHAREREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETSHAREREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1b\n\x19file.googleapis.com/Share'
    _globals['_DELETESHAREREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETESHAREREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x1b\n\x19file.googleapis.com/Share'
    _globals['_LISTSHARESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTSHARESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x1e\n\x1cfile.googleapis.com/Instance'
    _globals['_UPDATESHAREREQUEST'].fields_by_name['share']._loaded_options = None
    _globals['_UPDATESHAREREQUEST'].fields_by_name['share']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATESHAREREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATESHAREREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_CLOUDFILESTOREMANAGER']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER']._serialized_options = b'\xcaA\x13file.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListInstances']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListInstances']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x024\x122/v1beta1/{parent=projects/*/locations/*}/instances'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetInstance']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x024\x122/v1beta1/{name=projects/*/locations/*/instances/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateInstance']._serialized_options = b'\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\xdaA\x1bparent,instance,instance_id\x82\xd3\xe4\x93\x02>"2/v1beta1/{parent=projects/*/locations/*}/instances:\x08instance'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateInstance']._serialized_options = b'\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\xdaA\x14instance,update_mask\x82\xd3\xe4\x93\x02G2;/v1beta1/{instance.name=projects/*/locations/*/instances/*}:\x08instance'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['RestoreInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['RestoreInstance']._serialized_options = b'\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\x82\xd3\xe4\x93\x02?":/v1beta1/{name=projects/*/locations/*/instances/*}:restore:\x01*'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['RevertInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['RevertInstance']._serialized_options = b'\xcaA1\n\x08Instance\x12%google.cloud.common.OperationMetadata\x82\xd3\xe4\x93\x02>"9/v1beta1/{name=projects/*/locations/*/instances/*}:revert:\x01*'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteInstance']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteInstance']._serialized_options = b'\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x024*2/v1beta1/{name=projects/*/locations/*/instances/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListSnapshots']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListSnapshots']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02@\x12>/v1beta1/{parent=projects/*/locations/*/instances/*}/snapshots'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetSnapshot']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetSnapshot']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02@\x12>/v1beta1/{name=projects/*/locations/*/instances/*/snapshots/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateSnapshot']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateSnapshot']._serialized_options = b'\xcaA1\n\x08Snapshot\x12%google.cloud.common.OperationMetadata\xdaA\x1bparent,snapshot,snapshot_id\x82\xd3\xe4\x93\x02J">/v1beta1/{parent=projects/*/locations/*/instances/*}/snapshots:\x08snapshot'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteSnapshot']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteSnapshot']._serialized_options = b'\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02@*>/v1beta1/{name=projects/*/locations/*/instances/*/snapshots/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateSnapshot']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateSnapshot']._serialized_options = b'\xcaA1\n\x08Snapshot\x12%google.cloud.common.OperationMetadata\xdaA\x14snapshot,update_mask\x82\xd3\xe4\x93\x02S2G/v1beta1/{snapshot.name=projects/*/locations/*/instances/*/snapshots/*}:\x08snapshot'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListBackups']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListBackups']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1beta1/{parent=projects/*/locations/*}/backups'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetBackup']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetBackup']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1beta1/{name=projects/*/locations/*/backups/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateBackup']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateBackup']._serialized_options = b'\xcaA/\n\x06Backup\x12%google.cloud.common.OperationMetadata\xdaA\x17parent,backup,backup_id\x82\xd3\xe4\x93\x02:"0/v1beta1/{parent=projects/*/locations/*}/backups:\x06backup'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteBackup']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteBackup']._serialized_options = b'\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x022*0/v1beta1/{name=projects/*/locations/*/backups/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateBackup']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateBackup']._serialized_options = b'\xcaA/\n\x06Backup\x12%google.cloud.common.OperationMetadata\xdaA\x12backup,update_mask\x82\xd3\xe4\x93\x02A27/v1beta1/{backup.name=projects/*/locations/*/backups/*}:\x06backup'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListShares']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['ListShares']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02=\x12;/v1beta1/{parent=projects/*/locations/*/instances/*}/shares'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetShare']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['GetShare']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02=\x12;/v1beta1/{name=projects/*/locations/*/instances/*/shares/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateShare']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['CreateShare']._serialized_options = b'\xcaA.\n\x05Share\x12%google.cloud.common.OperationMetadata\xdaA\x15parent,share,share_id\x82\xd3\xe4\x93\x02D";/v1beta1/{parent=projects/*/locations/*/instances/*}/shares:\x05share'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteShare']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['DeleteShare']._serialized_options = b'\xcaA>\n\x15google.protobuf.Empty\x12%google.cloud.common.OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02=*;/v1beta1/{name=projects/*/locations/*/instances/*/shares/*}'
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateShare']._loaded_options = None
    _globals['_CLOUDFILESTOREMANAGER'].methods_by_name['UpdateShare']._serialized_options = b'\xcaA.\n\x05Share\x12%google.cloud.common.OperationMetadata\xdaA\x11share,update_mask\x82\xd3\xe4\x93\x02J2A/v1beta1/{share.name=projects/*/locations/*/instances/*/shares/*}:\x05share'
    _globals['_NETWORKCONFIG']._serialized_start = 423
    _globals['_NETWORKCONFIG']._serialized_end = 817
    _globals['_NETWORKCONFIG_ADDRESSMODE']._serialized_start = 666
    _globals['_NETWORKCONFIG_ADDRESSMODE']._serialized_end = 724
    _globals['_NETWORKCONFIG_CONNECTMODE']._serialized_start = 726
    _globals['_NETWORKCONFIG_CONNECTMODE']._serialized_end = 817
    _globals['_FILESHARECONFIG']._serialized_start = 820
    _globals['_FILESHARECONFIG']._serialized_end = 1018
    _globals['_NFSEXPORTOPTIONS']._serialized_start = 1021
    _globals['_NFSEXPORTOPTIONS']._serialized_end = 1600
    _globals['_NFSEXPORTOPTIONS_ACCESSMODE']._serialized_start = 1351
    _globals['_NFSEXPORTOPTIONS_ACCESSMODE']._serialized_end = 1423
    _globals['_NFSEXPORTOPTIONS_SQUASHMODE']._serialized_start = 1425
    _globals['_NFSEXPORTOPTIONS_SQUASHMODE']._serialized_end = 1503
    _globals['_NFSEXPORTOPTIONS_SECURITYFLAVOR']._serialized_start = 1505
    _globals['_NFSEXPORTOPTIONS_SECURITYFLAVOR']._serialized_end = 1600
    _globals['_MANAGEDACTIVEDIRECTORYCONFIG']._serialized_start = 1602
    _globals['_MANAGEDACTIVEDIRECTORYCONFIG']._serialized_end = 1666
    _globals['_DIRECTORYSERVICESCONFIG']._serialized_start = 1669
    _globals['_DIRECTORYSERVICESCONFIG']._serialized_end = 1802
    _globals['_INSTANCE']._serialized_start = 1805
    _globals['_INSTANCE']._serialized_end = 3401
    _globals['_INSTANCE_LABELSENTRY']._serialized_start = 2790
    _globals['_INSTANCE_LABELSENTRY']._serialized_end = 2835
    _globals['_INSTANCE_STATE']._serialized_start = 2838
    _globals['_INSTANCE_STATE']._serialized_end = 3008
    _globals['_INSTANCE_TIER']._serialized_start = 3011
    _globals['_INSTANCE_TIER']._serialized_end = 3157
    _globals['_INSTANCE_SUSPENSIONREASON']._serialized_start = 3159
    _globals['_INSTANCE_SUSPENSIONREASON']._serialized_end = 3231
    _globals['_INSTANCE_FILEPROTOCOL']._serialized_start = 3233
    _globals['_INSTANCE_FILEPROTOCOL']._serialized_end = 3304
    _globals['_CREATEINSTANCEREQUEST']._serialized_start = 3404
    _globals['_CREATEINSTANCEREQUEST']._serialized_end = 3577
    _globals['_GETINSTANCEREQUEST']._serialized_start = 3579
    _globals['_GETINSTANCEREQUEST']._serialized_end = 3651
    _globals['_UPDATEINSTANCEREQUEST']._serialized_start = 3654
    _globals['_UPDATEINSTANCEREQUEST']._serialized_end = 3796
    _globals['_RESTOREINSTANCEREQUEST']._serialized_start = 3799
    _globals['_RESTOREINSTANCEREQUEST']._serialized_end = 4032
    _globals['_REVERTINSTANCEREQUEST']._serialized_start = 4034
    _globals['_REVERTINSTANCEREQUEST']._serialized_end = 4142
    _globals['_DELETEINSTANCEREQUEST']._serialized_start = 4144
    _globals['_DELETEINSTANCEREQUEST']._serialized_end = 4234
    _globals['_LISTINSTANCESREQUEST']._serialized_start = 4237
    _globals['_LISTINSTANCESREQUEST']._serialized_end = 4391
    _globals['_LISTINSTANCESRESPONSE']._serialized_start = 4394
    _globals['_LISTINSTANCESRESPONSE']._serialized_end = 4524
    _globals['_SNAPSHOT']._serialized_start = 4527
    _globals['_SNAPSHOT']._serialized_end = 5041
    _globals['_SNAPSHOT_LABELSENTRY']._serialized_start = 2790
    _globals['_SNAPSHOT_LABELSENTRY']._serialized_end = 2835
    _globals['_SNAPSHOT_STATE']._serialized_start = 4854
    _globals['_SNAPSHOT_STATE']._serialized_end = 4923
    _globals['_CREATESNAPSHOTREQUEST']._serialized_start = 5044
    _globals['_CREATESNAPSHOTREQUEST']._serialized_end = 5212
    _globals['_GETSNAPSHOTREQUEST']._serialized_start = 5214
    _globals['_GETSNAPSHOTREQUEST']._serialized_end = 5286
    _globals['_DELETESNAPSHOTREQUEST']._serialized_start = 5288
    _globals['_DELETESNAPSHOTREQUEST']._serialized_end = 5363
    _globals['_UPDATESNAPSHOTREQUEST']._serialized_start = 5366
    _globals['_UPDATESNAPSHOTREQUEST']._serialized_end = 5508
    _globals['_LISTSNAPSHOTSREQUEST']._serialized_start = 5511
    _globals['_LISTSNAPSHOTSREQUEST']._serialized_end = 5660
    _globals['_LISTSNAPSHOTSRESPONSE']._serialized_start = 5662
    _globals['_LISTSNAPSHOTSRESPONSE']._serialized_end = 5771
    _globals['_BACKUP']._serialized_start = 5774
    _globals['_BACKUP']._serialized_end = 6611
    _globals['_BACKUP_LABELSENTRY']._serialized_start = 2790
    _globals['_BACKUP_LABELSENTRY']._serialized_end = 2835
    _globals['_BACKUP_STATE']._serialized_start = 6422
    _globals['_BACKUP_STATE']._serialized_end = 6520
    _globals['_CREATEBACKUPREQUEST']._serialized_start = 6614
    _globals['_CREATEBACKUPREQUEST']._serialized_end = 6779
    _globals['_DELETEBACKUPREQUEST']._serialized_start = 6781
    _globals['_DELETEBACKUPREQUEST']._serialized_end = 6852
    _globals['_UPDATEBACKUPREQUEST']._serialized_start = 6855
    _globals['_UPDATEBACKUPREQUEST']._serialized_end = 6991
    _globals['_GETBACKUPREQUEST']._serialized_start = 6993
    _globals['_GETBACKUPREQUEST']._serialized_end = 7061
    _globals['_LISTBACKUPSREQUEST']._serialized_start = 7064
    _globals['_LISTBACKUPSREQUEST']._serialized_end = 7216
    _globals['_LISTBACKUPSRESPONSE']._serialized_start = 7218
    _globals['_LISTBACKUPSRESPONSE']._serialized_end = 7342
    _globals['_SHARE']._serialized_start = 7345
    _globals['_SHARE']._serialized_end = 7988
    _globals['_SHARE_LABELSENTRY']._serialized_start = 2790
    _globals['_SHARE_LABELSENTRY']._serialized_end = 2835
    _globals['_SHARE_STATE']._serialized_start = 4854
    _globals['_SHARE_STATE']._serialized_end = 4923
    _globals['_CREATESHAREREQUEST']._serialized_start = 7991
    _globals['_CREATESHAREREQUEST']._serialized_end = 8147
    _globals['_GETSHAREREQUEST']._serialized_start = 8149
    _globals['_GETSHAREREQUEST']._serialized_end = 8215
    _globals['_DELETESHAREREQUEST']._serialized_start = 8217
    _globals['_DELETESHAREREQUEST']._serialized_end = 8286
    _globals['_LISTSHARESREQUEST']._serialized_start = 8289
    _globals['_LISTSHARESREQUEST']._serialized_end = 8435
    _globals['_LISTSHARESRESPONSE']._serialized_start = 8437
    _globals['_LISTSHARESRESPONSE']._serialized_end = 8558
    _globals['_UPDATESHAREREQUEST']._serialized_start = 8561
    _globals['_UPDATESHAREREQUEST']._serialized_end = 8694
    _globals['_CLOUDFILESTOREMANAGER']._serialized_start = 8697
    _globals['_CLOUDFILESTOREMANAGER']._serialized_end = 13761