# SPDX-License-Identifier: MIT
# Inspired by: https://hynek.me/articles/python-recursive-optional-dependencies/
# We here use a flat-layout distribution style https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

[build-system]
# never uppercap requirements unless we have evidence it won't work https://iscinumpy.dev/post/bound-version-constraints/ 
# cython cannot be placed in optional-dependencies, Cython won't be able to do its magic to make it importable in setup.py
# setuptools>=61 is necessary to support dynamic version in pyproject.toml: https://packaging.python.org/en/latest/guides/single-sourcing-package-version/ -- but only setuptools up to 44.1.1 is available on Py2, so we define setuptools>44 as the highest version for Py2, and this works because on Py2, pyproject.toml is only used for build-system (because this table only exists in pyproject.toml, see PEP 518), and then pip/setuptools switch to setup.cfg on Py2 for the rest of the build process. For more infos on dependency specification, see: https://peps.python.org/pep-0508/
requires = ["setuptools>=44;python_version<'3'", "setuptools>=61;python_version>='3'"]
build-backend = "setuptools.build_meta"

[project]  # beware if using setuptools: setup.py still gets executed, and even if pyproject.toml fields take precedence, if there is any code error in setup.py, building will fail!
name = "subtitles2text"
version = "0.0.3"
description = "Subtitles (VTT, SRT, PDF, DOCX, HTML, images, etc) to text convertor, with a GUI, great for preprocessing to feed to LLMs"
dependencies = [
    "vtt2txt-ng",
    "docling",
]
requires-python = ">=3.7"
authors = [
    {name = "Stephen Karl Larroque", email = "lrq3000@gmail.com"},
    ]
maintainers = [
    {name = "Stephen Karl Larroque", email = "lrq3000@gmail.com"},
    ]
license = {text = "MIT License"} # { file = "LICENSE" }
keywords = ["subtitles", "srt", "vtt", "docx", "pdf", "html", "conversion", "converter", "llm", "gpt", "preprocessing"]
classifiers = [
    'Development Status :: 3 - Alpha',
    'License :: OSI Approved :: MIT License',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: POSIX :: Linux',
    'Intended Audience :: Developers',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: Implementation :: PyPy',
    'Topic :: Utilities',
]

[project.scripts]
subtitles2text = "subtitles2text.main:run_gui"

[project.urls]
Homepage = "https://github.com/lrq3000/subtitles2text"
Documentation = "https://github.com/lrq3000/subtitles2text/blob/master/README.md"
"Source" = "https://github.com/lrq3000/subtitles2text"
Tracker = "https://github.com/lrq3000/subtitles2text/issues"
Download = "https://github.com/lrq3000/subtitles2text/releases"
#Changelog = "https://url/changelog"

[project.readme]
# Do NOT use .. code:: python for interactive code session, otherwise syntax error due to prompt handle >>>, see https://svn.python.org/projects/external/Sphinx-1.2/doc/markup/code.rst and https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#python-docstrings
# also use rstcheck if rst
file = "README.md"
content-type = "text/markdown"
