"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 28, 1, '', 'google/cloud/securesourcemanager/v1/secure_source_manager.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.iam.v1 import iam_policy_pb2 as google_dot_iam_dot_v1_dot_iam__policy__pb2
from .....google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?google/cloud/securesourcemanager/v1/secure_source_manager.proto\x12#google.cloud.securesourcemanager.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1egoogle/iam/v1/iam_policy.proto\x1a\x1agoogle/iam/v1/policy.proto\x1a#google/longrunning/operations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xd5\n\n\x08Instance\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x01\x124\n\x0bcreate_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x124\n\x0bupdate_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12N\n\x06labels\x18\x04 \x03(\x0b29.google.cloud.securesourcemanager.v1.Instance.LabelsEntryB\x03\xe0A\x01\x12X\n\x0eprivate_config\x18\r \x01(\x0b2;.google.cloud.securesourcemanager.v1.Instance.PrivateConfigB\x03\xe0A\x01\x12G\n\x05state\x18\x05 \x01(\x0e23.google.cloud.securesourcemanager.v1.Instance.StateB\x03\xe0A\x03\x12P\n\nstate_note\x18\n \x01(\x0e27.google.cloud.securesourcemanager.v1.Instance.StateNoteB\x03\xe0A\x03\x12:\n\x07kms_key\x18\x0b \x01(\tB)\xe0A\x05\xfaA#\n!cloudkms.googleapis.com/CryptoKey\x12R\n\x0bhost_config\x18\t \x01(\x0b28.google.cloud.securesourcemanager.v1.Instance.HostConfigB\x03\xe0A\x03\x1a^\n\nHostConfig\x12\x11\n\x04html\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x10\n\x03api\x18\x02 \x01(\tB\x03\xe0A\x03\x12\x15\n\x08git_http\x18\x03 \x01(\tB\x03\xe0A\x03\x12\x14\n\x07git_ssh\x18\x04 \x01(\tB\x03\xe0A\x03\x1a\xb0\x02\n\rPrivateConfig\x12\x1a\n\nis_private\x18\x01 \x01(\x08B\x06\xe0A\x05\xe0A\x02\x12;\n\x07ca_pool\x18\x02 \x01(\tB*\xe0A\x05\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool\x12Q\n\x17http_service_attachment\x18\x03 \x01(\tB0\xe0A\x03\xfaA*\n(compute.googleapis.com/ServiceAttachment\x12P\n\x16ssh_service_attachment\x18\x04 \x01(\tB0\xe0A\x03\xfaA*\n(compute.googleapis.com/ServiceAttachment\x12!\n\x14psc_allowed_projects\x18\x06 \x03(\tB\x03\xe0A\x01\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"_\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\n\n\x06ACTIVE\x10\x02\x12\x0c\n\x08DELETING\x10\x03\x12\n\n\x06PAUSED\x10\x04\x12\x0b\n\x07UNKNOWN\x10\x06"_\n\tStateNote\x12\x1a\n\x16STATE_NOTE_UNSPECIFIED\x10\x00\x12\x1b\n\x17PAUSED_CMEK_UNAVAILABLE\x10\x01\x12\x19\n\x11INSTANCE_RESUMING\x10\x02\x1a\x02\x08\x01:q\xeaAn\n+securesourcemanager.googleapis.com/Instance\x12<projects/{project}/locations/{location}/instances/{instance}R\x01\x01"\xd0\x05\n\nRepository\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x01\x12\x18\n\x0bdescription\x18\x02 \x01(\tB\x03\xe0A\x01\x12E\n\x08instance\x18\x03 \x01(\tB3\xe0A\x01\xfaA-\n+securesourcemanager.googleapis.com/Instance\x12\x10\n\x03uid\x18\x04 \x01(\tB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x05 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x124\n\x0bupdate_time\x18\x06 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x11\n\x04etag\x18\x08 \x01(\tB\x03\xe0A\x01\x12G\n\x04uris\x18\t \x01(\x0b24.google.cloud.securesourcemanager.v1.Repository.URIsB\x03\xe0A\x03\x12Z\n\x0einitial_config\x18\n \x01(\x0b2=.google.cloud.securesourcemanager.v1.Repository.InitialConfigB\x03\xe0A\x04\x1aC\n\x04URIs\x12\x11\n\x04html\x18\x01 \x01(\tB\x03\xe0A\x03\x12\x16\n\tgit_https\x18\x02 \x01(\tB\x03\xe0A\x03\x12\x10\n\x03api\x18\x03 \x01(\tB\x03\xe0A\x03\x1a\\\n\rInitialConfig\x12\x16\n\x0edefault_branch\x18\x01 \x01(\t\x12\x12\n\ngitignores\x18\x02 \x03(\t\x12\x0f\n\x07license\x18\x03 \x01(\t\x12\x0e\n\x06readme\x18\x04 \x01(\t:u\xeaAr\n-securesourcemanager.googleapis.com/Repository\x12Aprojects/{project}/locations/{location}/repositories/{repository}"\xdf\x06\n\nBranchRule\x12\x11\n\x04name\x18\x01 \x01(\tB\x03\xe0A\x01\x12\x10\n\x03uid\x18\x02 \x01(\tB\x03\xe0A\x03\x124\n\x0bcreate_time\x18\x03 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x124\n\x0bupdate_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12Z\n\x0bannotations\x18\x05 \x03(\x0b2@.google.cloud.securesourcemanager.v1.BranchRule.AnnotationsEntryB\x03\xe0A\x01\x12\x11\n\x04etag\x18\x06 \x01(\tB\x03\xe0A\x01\x12\x1c\n\x0finclude_pattern\x18\x07 \x01(\tB\x03\xe0A\x01\x12\x15\n\x08disabled\x18\x08 \x01(\x08B\x03\xe0A\x01\x12!\n\x14require_pull_request\x18\t \x01(\x08B\x03\xe0A\x01\x12"\n\x15minimum_reviews_count\x18\n \x01(\x05B\x03\xe0A\x01\x12$\n\x17minimum_approvals_count\x18\x0b \x01(\x05B\x03\xe0A\x01\x12&\n\x19require_comments_resolved\x18\x0c \x01(\x08B\x03\xe0A\x01\x12 \n\x13allow_stale_reviews\x18\x0f \x01(\x08B\x03\xe0A\x01\x12#\n\x16require_linear_history\x18\r \x01(\x08B\x03\xe0A\x01\x12Z\n\x16required_status_checks\x18\x0e \x03(\x0b25.google.cloud.securesourcemanager.v1.BranchRule.CheckB\x03\xe0A\x01\x1a\x1d\n\x05Check\x12\x14\n\x07context\x18\x01 \x01(\tB\x03\xe0A\x02\x1a2\n\x10AnnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01:\x90\x01\xeaA\x8c\x01\n-securesourcemanager.googleapis.com/BranchRule\x12[projects/{project}/locations/{location}/repositories/{repository}/branchRules/{branch_rule}"\xa4\x01\n\x14ListInstancesRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+securesourcemanager.googleapis.com/Instance\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x04 \x01(\t\x12\x10\n\x08order_by\x18\x05 \x01(\t"\x87\x01\n\x15ListInstancesResponse\x12@\n\tinstances\x18\x01 \x03(\x0b2-.google.cloud.securesourcemanager.v1.Instance\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"W\n\x12GetInstanceRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+securesourcemanager.googleapis.com/Instance"\xd5\x01\n\x15CreateInstanceRequest\x12C\n\x06parent\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\x12+securesourcemanager.googleapis.com/Instance\x12\x18\n\x0binstance_id\x18\x02 \x01(\tB\x03\xe0A\x02\x12D\n\x08instance\x18\x03 \x01(\x0b2-.google.cloud.securesourcemanager.v1.InstanceB\x03\xe0A\x02\x12\x17\n\nrequest_id\x18\x04 \x01(\tB\x03\xe0A\x01"s\n\x15DeleteInstanceRequest\x12A\n\x04name\x18\x01 \x01(\tB3\xe0A\x02\xfaA-\n+securesourcemanager.googleapis.com/Instance\x12\x17\n\nrequest_id\x18\x02 \x01(\tB\x03\xe0A\x01"\x80\x02\n\x11OperationMetadata\x124\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x121\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12\x13\n\x06target\x18\x03 \x01(\tB\x03\xe0A\x03\x12\x11\n\x04verb\x18\x04 \x01(\tB\x03\xe0A\x03\x12\x1b\n\x0estatus_message\x18\x05 \x01(\tB\x03\xe0A\x03\x12#\n\x16requested_cancellation\x18\x06 \x01(\x08B\x03\xe0A\x03\x12\x18\n\x0bapi_version\x18\x07 \x01(\tB\x03\xe0A\x03"\xe8\x01\n\x17ListRepositoriesRequest\x12E\n\x06parent\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\x12-securesourcemanager.googleapis.com/Repository\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x13\n\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01\x12E\n\x08instance\x18\x05 \x01(\tB3\xe0A\x01\xfaA-\n+securesourcemanager.googleapis.com/Instance"z\n\x18ListRepositoriesResponse\x12E\n\x0crepositories\x18\x01 \x03(\x0b2/.google.cloud.securesourcemanager.v1.Repository\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t"[\n\x14GetRepositoryRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-securesourcemanager.googleapis.com/Repository"\xc6\x01\n\x17CreateRepositoryRequest\x12E\n\x06parent\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\x12-securesourcemanager.googleapis.com/Repository\x12H\n\nrepository\x18\x02 \x01(\x0b2/.google.cloud.securesourcemanager.v1.RepositoryB\x03\xe0A\x02\x12\x1a\n\rrepository_id\x18\x03 \x01(\tB\x03\xe0A\x02"z\n\x17DeleteRepositoryRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-securesourcemanager.googleapis.com/Repository\x12\x1a\n\rallow_missing\x18\x02 \x01(\x08B\x03\xe0A\x01"[\n\x14GetBranchRuleRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-securesourcemanager.googleapis.com/BranchRule"\xc8\x01\n\x17CreateBranchRuleRequest\x12E\n\x06parent\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\x12-securesourcemanager.googleapis.com/BranchRule\x12I\n\x0bbranch_rule\x18\x02 \x01(\x0b2/.google.cloud.securesourcemanager.v1.BranchRuleB\x03\xe0A\x02\x12\x1b\n\x0ebranch_rule_id\x18\x03 \x01(\tB\x03\xe0A\x02"\x90\x01\n\x16ListBranchRulesRequest\x12E\n\x06parent\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\x12-securesourcemanager.googleapis.com/BranchRule\x12\x16\n\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01\x12\x17\n\npage_token\x18\x03 \x01(\tB\x03\xe0A\x01"z\n\x17DeleteBranchRuleRequest\x12C\n\x04name\x18\x01 \x01(\tB5\xe0A\x02\xfaA/\n-securesourcemanager.googleapis.com/BranchRule\x12\x1a\n\rallow_missing\x18\x02 \x01(\x08B\x03\xe0A\x01"\xb6\x01\n\x17UpdateBranchRuleRequest\x12I\n\x0bbranch_rule\x18\x01 \x01(\x0b2/.google.cloud.securesourcemanager.v1.BranchRuleB\x03\xe0A\x02\x12\x1a\n\rvalidate_only\x18\x02 \x01(\x08B\x03\xe0A\x01\x124\n\x0bupdate_mask\x18\x03 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02"y\n\x17ListBranchRulesResponse\x12E\n\x0cbranch_rules\x18\x01 \x03(\x0b2/.google.cloud.securesourcemanager.v1.BranchRule\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\xfa\x1b\n\x13SecureSourceManager\x12\xc6\x01\n\rListInstances\x129.google.cloud.securesourcemanager.v1.ListInstancesRequest\x1a:.google.cloud.securesourcemanager.v1.ListInstancesResponse">\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1/{parent=projects/*/locations/*}/instances\x12\xb3\x01\n\x0bGetInstance\x127.google.cloud.securesourcemanager.v1.GetInstanceRequest\x1a-.google.cloud.securesourcemanager.v1.Instance"<\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1/{name=projects/*/locations/*/instances/*}\x12\xea\x01\n\x0eCreateInstance\x12:.google.cloud.securesourcemanager.v1.CreateInstanceRequest\x1a\x1d.google.longrunning.Operation"}\xcaA\x1d\n\x08Instance\x12\x11OperationMetadata\xdaA\x1bparent,instance,instance_id\x82\xd3\xe4\x93\x029"-/v1/{parent=projects/*/locations/*}/instances:\x08instance\x12\xd6\x01\n\x0eDeleteInstance\x12:.google.cloud.securesourcemanager.v1.DeleteInstanceRequest\x1a\x1d.google.longrunning.Operation"i\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v1/{name=projects/*/locations/*/instances/*}\x12\xd2\x01\n\x10ListRepositories\x12<.google.cloud.securesourcemanager.v1.ListRepositoriesRequest\x1a=.google.cloud.securesourcemanager.v1.ListRepositoriesResponse"A\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=projects/*/locations/*}/repositories\x12\xbc\x01\n\rGetRepository\x129.google.cloud.securesourcemanager.v1.GetRepositoryRequest\x1a/.google.cloud.securesourcemanager.v1.Repository"?\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1/{name=projects/*/locations/*/repositories/*}\x12\xfa\x01\n\x10CreateRepository\x12<.google.cloud.securesourcemanager.v1.CreateRepositoryRequest\x1a\x1d.google.longrunning.Operation"\x88\x01\xcaA\x1f\n\nRepository\x12\x11OperationMetadata\xdaA\x1fparent,repository,repository_id\x82\xd3\xe4\x93\x02>"0/v1/{parent=projects/*/locations/*}/repositories:\nrepository\x12\xdd\x01\n\x10DeleteRepository\x12<.google.cloud.securesourcemanager.v1.DeleteRepositoryRequest\x1a\x1d.google.longrunning.Operation"l\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x022*0/v1/{name=projects/*/locations/*/repositories/*}\x12\xa3\x01\n\x10GetIamPolicyRepo\x12".google.iam.v1.GetIamPolicyRequest\x1a\x15.google.iam.v1.Policy"T\xdaA\x08resource\x82\xd3\xe4\x93\x02C\x12A/v1/{resource=projects/*/locations/*/repositories/*}:getIamPolicy\x12\xa6\x01\n\x10SetIamPolicyRepo\x12".google.iam.v1.SetIamPolicyRequest\x1a\x15.google.iam.v1.Policy"W\xdaA\x08resource\x82\xd3\xe4\x93\x02F"A/v1/{resource=projects/*/locations/*/repositories/*}:setIamPolicy:\x01*\x12\xcc\x01\n\x16TestIamPermissionsRepo\x12(.google.iam.v1.TestIamPermissionsRequest\x1a).google.iam.v1.TestIamPermissionsResponse"]\xdaA\x08resource\x82\xd3\xe4\x93\x02L"G/v1/{resource=projects/*/locations/*/repositories/*}:testIamPermissions:\x01*\x12\x8b\x02\n\x10CreateBranchRule\x12<.google.cloud.securesourcemanager.v1.CreateBranchRuleRequest\x1a\x1d.google.longrunning.Operation"\x99\x01\xcaA\x1f\n\nBranchRule\x12\x11OperationMetadata\xdaA!parent,branch_rule,branch_rule_id\x82\xd3\xe4\x93\x02M">/v1/{parent=projects/*/locations/*/repositories/*}/branchRules:\x0bbranch_rule\x12\xdd\x01\n\x0fListBranchRules\x12;.google.cloud.securesourcemanager.v1.ListBranchRulesRequest\x1a<.google.cloud.securesourcemanager.v1.ListBranchRulesResponse"O\xdaA\x06parent\x82\xd3\xe4\x93\x02@\x12>/v1/{parent=projects/*/locations/*/repositories/*}/branchRules\x12\xca\x01\n\rGetBranchRule\x129.google.cloud.securesourcemanager.v1.GetBranchRuleRequest\x1a/.google.cloud.securesourcemanager.v1.BranchRule"M\xdaA\x04name\x82\xd3\xe4\x93\x02@\x12>/v1/{name=projects/*/locations/*/repositories/*/branchRules/*}\x12\x8d\x02\n\x10UpdateBranchRule\x12<.google.cloud.securesourcemanager.v1.UpdateBranchRuleRequest\x1a\x1d.google.longrunning.Operation"\x9b\x01\xcaA\x1f\n\nBranchRule\x12\x11OperationMetadata\xdaA\x17branch_rule,update_mask\x82\xd3\xe4\x93\x02Y2J/v1/{branch_rule.name=projects/*/locations/*/repositories/*/branchRules/*}:\x0bbranch_rule\x12\xeb\x01\n\x10DeleteBranchRule\x12<.google.cloud.securesourcemanager.v1.DeleteBranchRuleRequest\x1a\x1d.google.longrunning.Operation"z\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02@*>/v1/{name=projects/*/locations/*/repositories/*/branchRules/*}\x1aV\xcaA"securesourcemanager.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xe9\x04\n\'com.google.cloud.securesourcemanager.v1B\x18SecureSourceManagerProtoP\x01ZYcloud.google.com/go/securesourcemanager/apiv1/securesourcemanagerpb;securesourcemanagerpb\xaa\x02#Google.Cloud.SecureSourceManager.V1\xca\x02#Google\\Cloud\\SecureSourceManager\\V1\xea\x02&Google::Cloud::SecureSourceManager::V1\xeaAx\n!cloudkms.googleapis.com/CryptoKey\x12Sprojects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}\xeaA\\\n\x1fprivateca.googleapis.com/CaPool\x129projects/{project}/locations/{location}/caPools/{ca_pool}\xeaAw\n(compute.googleapis.com/ServiceAttachment\x12Kprojects/{project}/regions/{region}/serviceAttachments/{service_attachment}b\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.securesourcemanager.v1.secure_source_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b"\n'com.google.cloud.securesourcemanager.v1B\x18SecureSourceManagerProtoP\x01ZYcloud.google.com/go/securesourcemanager/apiv1/securesourcemanagerpb;securesourcemanagerpb\xaa\x02#Google.Cloud.SecureSourceManager.V1\xca\x02#Google\\Cloud\\SecureSourceManager\\V1\xea\x02&Google::Cloud::SecureSourceManager::V1\xeaAx\n!cloudkms.googleapis.com/CryptoKey\x12Sprojects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}\xeaA\\\n\x1fprivateca.googleapis.com/CaPool\x129projects/{project}/locations/{location}/caPools/{ca_pool}\xeaAw\n(compute.googleapis.com/ServiceAttachment\x12Kprojects/{project}/regions/{region}/serviceAttachments/{service_attachment}"
    _globals['_INSTANCE_HOSTCONFIG'].fields_by_name['html']._loaded_options = None
    _globals['_INSTANCE_HOSTCONFIG'].fields_by_name['html']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE_HOSTCONFIG'].fields_by_name['api']._loaded_options = None
    _globals['_INSTANCE_HOSTCONFIG'].fields_by_name['api']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE_HOSTCONFIG'].fields_by_name['git_http']._loaded_options = None
    _globals['_INSTANCE_HOSTCONFIG'].fields_by_name['git_http']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE_HOSTCONFIG'].fields_by_name['git_ssh']._loaded_options = None
    _globals['_INSTANCE_HOSTCONFIG'].fields_by_name['git_ssh']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE_PRIVATECONFIG'].fields_by_name['is_private']._loaded_options = None
    _globals['_INSTANCE_PRIVATECONFIG'].fields_by_name['is_private']._serialized_options = b'\xe0A\x05\xe0A\x02'
    _globals['_INSTANCE_PRIVATECONFIG'].fields_by_name['ca_pool']._loaded_options = None
    _globals['_INSTANCE_PRIVATECONFIG'].fields_by_name['ca_pool']._serialized_options = b'\xe0A\x05\xe0A\x02\xfaA!\n\x1fprivateca.googleapis.com/CaPool'
    _globals['_INSTANCE_PRIVATECONFIG'].fields_by_name['http_service_attachment']._loaded_options = None
    _globals['_INSTANCE_PRIVATECONFIG'].fields_by_name['http_service_attachment']._serialized_options = b'\xe0A\x03\xfaA*\n(compute.googleapis.com/ServiceAttachment'
    _globals['_INSTANCE_PRIVATECONFIG'].fields_by_name['ssh_service_attachment']._loaded_options = None
    _globals['_INSTANCE_PRIVATECONFIG'].fields_by_name['ssh_service_attachment']._serialized_options = b'\xe0A\x03\xfaA*\n(compute.googleapis.com/ServiceAttachment'
    _globals['_INSTANCE_PRIVATECONFIG'].fields_by_name['psc_allowed_projects']._loaded_options = None
    _globals['_INSTANCE_PRIVATECONFIG'].fields_by_name['psc_allowed_projects']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE_LABELSENTRY']._loaded_options = None
    _globals['_INSTANCE_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_INSTANCE_STATENOTE'].values_by_name['INSTANCE_RESUMING']._loaded_options = None
    _globals['_INSTANCE_STATENOTE'].values_by_name['INSTANCE_RESUMING']._serialized_options = b'\x08\x01'
    _globals['_INSTANCE'].fields_by_name['name']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['name']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['create_time']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['update_time']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['update_time']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['labels']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['labels']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['private_config']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['private_config']._serialized_options = b'\xe0A\x01'
    _globals['_INSTANCE'].fields_by_name['state']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['state_note']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['state_note']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE'].fields_by_name['kms_key']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['kms_key']._serialized_options = b'\xe0A\x05\xfaA#\n!cloudkms.googleapis.com/CryptoKey'
    _globals['_INSTANCE'].fields_by_name['host_config']._loaded_options = None
    _globals['_INSTANCE'].fields_by_name['host_config']._serialized_options = b'\xe0A\x03'
    _globals['_INSTANCE']._loaded_options = None
    _globals['_INSTANCE']._serialized_options = b'\xeaAn\n+securesourcemanager.googleapis.com/Instance\x12<projects/{project}/locations/{location}/instances/{instance}R\x01\x01'
    _globals['_REPOSITORY_URIS'].fields_by_name['html']._loaded_options = None
    _globals['_REPOSITORY_URIS'].fields_by_name['html']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY_URIS'].fields_by_name['git_https']._loaded_options = None
    _globals['_REPOSITORY_URIS'].fields_by_name['git_https']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY_URIS'].fields_by_name['api']._loaded_options = None
    _globals['_REPOSITORY_URIS'].fields_by_name['api']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY'].fields_by_name['name']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['name']._serialized_options = b'\xe0A\x01'
    _globals['_REPOSITORY'].fields_by_name['description']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['description']._serialized_options = b'\xe0A\x01'
    _globals['_REPOSITORY'].fields_by_name['instance']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['instance']._serialized_options = b'\xe0A\x01\xfaA-\n+securesourcemanager.googleapis.com/Instance'
    _globals['_REPOSITORY'].fields_by_name['uid']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['uid']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY'].fields_by_name['create_time']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY'].fields_by_name['update_time']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['update_time']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY'].fields_by_name['etag']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_REPOSITORY'].fields_by_name['uris']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['uris']._serialized_options = b'\xe0A\x03'
    _globals['_REPOSITORY'].fields_by_name['initial_config']._loaded_options = None
    _globals['_REPOSITORY'].fields_by_name['initial_config']._serialized_options = b'\xe0A\x04'
    _globals['_REPOSITORY']._loaded_options = None
    _globals['_REPOSITORY']._serialized_options = b'\xeaAr\n-securesourcemanager.googleapis.com/Repository\x12Aprojects/{project}/locations/{location}/repositories/{repository}'
    _globals['_BRANCHRULE_CHECK'].fields_by_name['context']._loaded_options = None
    _globals['_BRANCHRULE_CHECK'].fields_by_name['context']._serialized_options = b'\xe0A\x02'
    _globals['_BRANCHRULE_ANNOTATIONSENTRY']._loaded_options = None
    _globals['_BRANCHRULE_ANNOTATIONSENTRY']._serialized_options = b'8\x01'
    _globals['_BRANCHRULE'].fields_by_name['name']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['name']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['uid']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['uid']._serialized_options = b'\xe0A\x03'
    _globals['_BRANCHRULE'].fields_by_name['create_time']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_BRANCHRULE'].fields_by_name['update_time']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['update_time']._serialized_options = b'\xe0A\x03'
    _globals['_BRANCHRULE'].fields_by_name['annotations']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['annotations']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['etag']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['etag']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['include_pattern']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['include_pattern']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['disabled']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['disabled']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['require_pull_request']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['require_pull_request']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['minimum_reviews_count']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['minimum_reviews_count']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['minimum_approvals_count']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['minimum_approvals_count']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['require_comments_resolved']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['require_comments_resolved']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['allow_stale_reviews']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['allow_stale_reviews']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['require_linear_history']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['require_linear_history']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE'].fields_by_name['required_status_checks']._loaded_options = None
    _globals['_BRANCHRULE'].fields_by_name['required_status_checks']._serialized_options = b'\xe0A\x01'
    _globals['_BRANCHRULE']._loaded_options = None
    _globals['_BRANCHRULE']._serialized_options = b'\xeaA\x8c\x01\n-securesourcemanager.googleapis.com/BranchRule\x12[projects/{project}/locations/{location}/repositories/{repository}/branchRules/{branch_rule}'
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTINSTANCESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+securesourcemanager.googleapis.com/Instance'
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+securesourcemanager.googleapis.com/Instance'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA-\x12+securesourcemanager.googleapis.com/Instance'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance_id']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_CREATEINSTANCEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA-\n+securesourcemanager.googleapis.com/Instance'
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['request_id']._loaded_options = None
    _globals['_DELETEINSTANCEREQUEST'].fields_by_name['request_id']._serialized_options = b'\xe0A\x01'
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['end_time']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['target']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['verb']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['status_message']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['requested_cancellation']._serialized_options = b'\xe0A\x03'
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._loaded_options = None
    _globals['_OPERATIONMETADATA'].fields_by_name['api_version']._serialized_options = b'\xe0A\x03'
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA/\x12-securesourcemanager.googleapis.com/Repository'
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['filter']._loaded_options = None
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['filter']._serialized_options = b'\xe0A\x01'
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['instance']._loaded_options = None
    _globals['_LISTREPOSITORIESREQUEST'].fields_by_name['instance']._serialized_options = b'\xe0A\x01\xfaA-\n+securesourcemanager.googleapis.com/Instance'
    _globals['_GETREPOSITORYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETREPOSITORYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-securesourcemanager.googleapis.com/Repository'
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA/\x12-securesourcemanager.googleapis.com/Repository'
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository']._loaded_options = None
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository_id']._loaded_options = None
    _globals['_CREATEREPOSITORYREQUEST'].fields_by_name['repository_id']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEREPOSITORYREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEREPOSITORYREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-securesourcemanager.googleapis.com/Repository'
    _globals['_DELETEREPOSITORYREQUEST'].fields_by_name['allow_missing']._loaded_options = None
    _globals['_DELETEREPOSITORYREQUEST'].fields_by_name['allow_missing']._serialized_options = b'\xe0A\x01'
    _globals['_GETBRANCHRULEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETBRANCHRULEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-securesourcemanager.googleapis.com/BranchRule'
    _globals['_CREATEBRANCHRULEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEBRANCHRULEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA/\x12-securesourcemanager.googleapis.com/BranchRule'
    _globals['_CREATEBRANCHRULEREQUEST'].fields_by_name['branch_rule']._loaded_options = None
    _globals['_CREATEBRANCHRULEREQUEST'].fields_by_name['branch_rule']._serialized_options = b'\xe0A\x02'
    _globals['_CREATEBRANCHRULEREQUEST'].fields_by_name['branch_rule_id']._loaded_options = None
    _globals['_CREATEBRANCHRULEREQUEST'].fields_by_name['branch_rule_id']._serialized_options = b'\xe0A\x02'
    _globals['_LISTBRANCHRULESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTBRANCHRULESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA/\x12-securesourcemanager.googleapis.com/BranchRule'
    _globals['_LISTBRANCHRULESREQUEST'].fields_by_name['page_size']._loaded_options = None
    _globals['_LISTBRANCHRULESREQUEST'].fields_by_name['page_size']._serialized_options = b'\xe0A\x01'
    _globals['_LISTBRANCHRULESREQUEST'].fields_by_name['page_token']._loaded_options = None
    _globals['_LISTBRANCHRULESREQUEST'].fields_by_name['page_token']._serialized_options = b'\xe0A\x01'
    _globals['_DELETEBRANCHRULEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEBRANCHRULEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA/\n-securesourcemanager.googleapis.com/BranchRule'
    _globals['_DELETEBRANCHRULEREQUEST'].fields_by_name['allow_missing']._loaded_options = None
    _globals['_DELETEBRANCHRULEREQUEST'].fields_by_name['allow_missing']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEBRANCHRULEREQUEST'].fields_by_name['branch_rule']._loaded_options = None
    _globals['_UPDATEBRANCHRULEREQUEST'].fields_by_name['branch_rule']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATEBRANCHRULEREQUEST'].fields_by_name['validate_only']._loaded_options = None
    _globals['_UPDATEBRANCHRULEREQUEST'].fields_by_name['validate_only']._serialized_options = b'\xe0A\x01'
    _globals['_UPDATEBRANCHRULEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATEBRANCHRULEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_SECURESOURCEMANAGER']._loaded_options = None
    _globals['_SECURESOURCEMANAGER']._serialized_options = b'\xcaA"securesourcemanager.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['ListInstances']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['ListInstances']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1/{parent=projects/*/locations/*}/instances'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['GetInstance']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['GetInstance']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1/{name=projects/*/locations/*/instances/*}'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['CreateInstance']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['CreateInstance']._serialized_options = b'\xcaA\x1d\n\x08Instance\x12\x11OperationMetadata\xdaA\x1bparent,instance,instance_id\x82\xd3\xe4\x93\x029"-/v1/{parent=projects/*/locations/*}/instances:\x08instance'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['DeleteInstance']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['DeleteInstance']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v1/{name=projects/*/locations/*/instances/*}'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['ListRepositories']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['ListRepositories']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x022\x120/v1/{parent=projects/*/locations/*}/repositories'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['GetRepository']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['GetRepository']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x022\x120/v1/{name=projects/*/locations/*/repositories/*}'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['CreateRepository']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['CreateRepository']._serialized_options = b'\xcaA\x1f\n\nRepository\x12\x11OperationMetadata\xdaA\x1fparent,repository,repository_id\x82\xd3\xe4\x93\x02>"0/v1/{parent=projects/*/locations/*}/repositories:\nrepository'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['DeleteRepository']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['DeleteRepository']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x022*0/v1/{name=projects/*/locations/*/repositories/*}'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['GetIamPolicyRepo']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['GetIamPolicyRepo']._serialized_options = b'\xdaA\x08resource\x82\xd3\xe4\x93\x02C\x12A/v1/{resource=projects/*/locations/*/repositories/*}:getIamPolicy'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['SetIamPolicyRepo']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['SetIamPolicyRepo']._serialized_options = b'\xdaA\x08resource\x82\xd3\xe4\x93\x02F"A/v1/{resource=projects/*/locations/*/repositories/*}:setIamPolicy:\x01*'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['TestIamPermissionsRepo']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['TestIamPermissionsRepo']._serialized_options = b'\xdaA\x08resource\x82\xd3\xe4\x93\x02L"G/v1/{resource=projects/*/locations/*/repositories/*}:testIamPermissions:\x01*'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['CreateBranchRule']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['CreateBranchRule']._serialized_options = b'\xcaA\x1f\n\nBranchRule\x12\x11OperationMetadata\xdaA!parent,branch_rule,branch_rule_id\x82\xd3\xe4\x93\x02M">/v1/{parent=projects/*/locations/*/repositories/*}/branchRules:\x0bbranch_rule'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['ListBranchRules']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['ListBranchRules']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02@\x12>/v1/{parent=projects/*/locations/*/repositories/*}/branchRules'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['GetBranchRule']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['GetBranchRule']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02@\x12>/v1/{name=projects/*/locations/*/repositories/*/branchRules/*}'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['UpdateBranchRule']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['UpdateBranchRule']._serialized_options = b'\xcaA\x1f\n\nBranchRule\x12\x11OperationMetadata\xdaA\x17branch_rule,update_mask\x82\xd3\xe4\x93\x02Y2J/v1/{branch_rule.name=projects/*/locations/*/repositories/*/branchRules/*}:\x0bbranch_rule'
    _globals['_SECURESOURCEMANAGER'].methods_by_name['DeleteBranchRule']._loaded_options = None
    _globals['_SECURESOURCEMANAGER'].methods_by_name['DeleteBranchRule']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02@*>/v1/{name=projects/*/locations/*/repositories/*/branchRules/*}'
    _globals['_INSTANCE']._serialized_start = 413
    _globals['_INSTANCE']._serialized_end = 1778
    _globals['_INSTANCE_HOSTCONFIG']._serialized_start = 1021
    _globals['_INSTANCE_HOSTCONFIG']._serialized_end = 1115
    _globals['_INSTANCE_PRIVATECONFIG']._serialized_start = 1118
    _globals['_INSTANCE_PRIVATECONFIG']._serialized_end = 1422
    _globals['_INSTANCE_LABELSENTRY']._serialized_start = 1424
    _globals['_INSTANCE_LABELSENTRY']._serialized_end = 1469
    _globals['_INSTANCE_STATE']._serialized_start = 1471
    _globals['_INSTANCE_STATE']._serialized_end = 1566
    _globals['_INSTANCE_STATENOTE']._serialized_start = 1568
    _globals['_INSTANCE_STATENOTE']._serialized_end = 1663
    _globals['_REPOSITORY']._serialized_start = 1781
    _globals['_REPOSITORY']._serialized_end = 2501
    _globals['_REPOSITORY_URIS']._serialized_start = 2221
    _globals['_REPOSITORY_URIS']._serialized_end = 2288
    _globals['_REPOSITORY_INITIALCONFIG']._serialized_start = 2290
    _globals['_REPOSITORY_INITIALCONFIG']._serialized_end = 2382
    _globals['_BRANCHRULE']._serialized_start = 2504
    _globals['_BRANCHRULE']._serialized_end = 3367
    _globals['_BRANCHRULE_CHECK']._serialized_start = 3139
    _globals['_BRANCHRULE_CHECK']._serialized_end = 3168
    _globals['_BRANCHRULE_ANNOTATIONSENTRY']._serialized_start = 3170
    _globals['_BRANCHRULE_ANNOTATIONSENTRY']._serialized_end = 3220
    _globals['_LISTINSTANCESREQUEST']._serialized_start = 3370
    _globals['_LISTINSTANCESREQUEST']._serialized_end = 3534
    _globals['_LISTINSTANCESRESPONSE']._serialized_start = 3537
    _globals['_LISTINSTANCESRESPONSE']._serialized_end = 3672
    _globals['_GETINSTANCEREQUEST']._serialized_start = 3674
    _globals['_GETINSTANCEREQUEST']._serialized_end = 3761
    _globals['_CREATEINSTANCEREQUEST']._serialized_start = 3764
    _globals['_CREATEINSTANCEREQUEST']._serialized_end = 3977
    _globals['_DELETEINSTANCEREQUEST']._serialized_start = 3979
    _globals['_DELETEINSTANCEREQUEST']._serialized_end = 4094
    _globals['_OPERATIONMETADATA']._serialized_start = 4097
    _globals['_OPERATIONMETADATA']._serialized_end = 4353
    _globals['_LISTREPOSITORIESREQUEST']._serialized_start = 4356
    _globals['_LISTREPOSITORIESREQUEST']._serialized_end = 4588
    _globals['_LISTREPOSITORIESRESPONSE']._serialized_start = 4590
    _globals['_LISTREPOSITORIESRESPONSE']._serialized_end = 4712
    _globals['_GETREPOSITORYREQUEST']._serialized_start = 4714
    _globals['_GETREPOSITORYREQUEST']._serialized_end = 4805
    _globals['_CREATEREPOSITORYREQUEST']._serialized_start = 4808
    _globals['_CREATEREPOSITORYREQUEST']._serialized_end = 5006
    _globals['_DELETEREPOSITORYREQUEST']._serialized_start = 5008
    _globals['_DELETEREPOSITORYREQUEST']._serialized_end = 5130
    _globals['_GETBRANCHRULEREQUEST']._serialized_start = 5132
    _globals['_GETBRANCHRULEREQUEST']._serialized_end = 5223
    _globals['_CREATEBRANCHRULEREQUEST']._serialized_start = 5226
    _globals['_CREATEBRANCHRULEREQUEST']._serialized_end = 5426
    _globals['_LISTBRANCHRULESREQUEST']._serialized_start = 5429
    _globals['_LISTBRANCHRULESREQUEST']._serialized_end = 5573
    _globals['_DELETEBRANCHRULEREQUEST']._serialized_start = 5575
    _globals['_DELETEBRANCHRULEREQUEST']._serialized_end = 5697
    _globals['_UPDATEBRANCHRULEREQUEST']._serialized_start = 5700
    _globals['_UPDATEBRANCHRULEREQUEST']._serialized_end = 5882
    _globals['_LISTBRANCHRULESRESPONSE']._serialized_start = 5884
    _globals['_LISTBRANCHRULESRESPONSE']._serialized_end = 6005
    _globals['_SECURESOURCEMANAGER']._serialized_start = 6008
    _globals['_SECURESOURCEMANAGER']._serialized_end = 9586