[package]
name = "qwgraph"
version = "1.0.1"
edition = "2021"

[lib]
# The name of the native library. This is the name which will be used in Python to import the
# library (i.e. `import string_sum`). If you change this, you must also change the name of the
# `#[pymodule]` in `src/lib.rs`.
name = "qwgraph"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.0", features = ["extension-module","num-complex"] }
num-complex = "0.4.3"
rayon = "1.7.0"
indicatif = {version = "0.17.4", features = ["rayon"]}
