[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "blochpesto"
version = "1.0.0"
authors = [
  { name="Craig Polley", email="craig.polley@maxiv.lu.se" },
]
description = "Analysis and visualization package for ARPES data"
readme = "README.md"
requires-python = ">=3.8"
dependencies=[
  "numpy",
  "astropy",
  "packaging",
  "matplotlib<3.9.0",
  "scipy",
  "pyperclip",
  "ipywidgets",
  "ipympl",
  "igor2",
  "pandas",
  "h5py",
  "lmfit"
]


classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://pesto.readthedocs.io"