[build-system]
requires = ["setuptools"] # REQUIRED if [build-system] table is used
build-backend = "setuptools.build_meta"


[project]
name = "filestore_guagua"
version = "0.1.0"
description = "guagua自用文件存储库"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
keywords = ["jex", "files" ,'python']
authors = [{ name = "guagua", email = "guagua1053@gmail.com" }]
maintainers = [
  { name = "jex.huang", email = "guagua1053@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = ["peppercorn"]


[project.optional-dependencies]
dev = ["check-manifest"]
test = ["coverage"]

[project.urls]
"Homepage" = "https://github.com/dream-until-dawn/filestore_guagua"
"Bug Reports" = "https://github.com/dream-until-dawn/filestore_guagua/issues"

[project.scripts]
sample = "sample:main"