[tool.poetry]
name = "lms-grader"
version = "0.0.6"
description = "A Learning Management System Grader."
authors = ["nqabenhle <nqmlabajhb024@student.wethinkcode.co.za>"]
readme = "README.md"
packages = [{include = "lms"}]

[tool.poetry.dependencies]
python = "^3.10"
charset-normalizer = "^3.4.1"
colorful-test = "^1.0.2"
idna = "^3.10"
python-gitlab = "^5.6.0"
requests = "^2.32.3"
requests-toolbelt = "^1.0.0"
urllib3 = "^2.3.0"
certifi = "^2025.1.31"

[tool.setuptools]
packages = ["lms"]

[tool.poetry.scripts]
lms-grader = "lms.grader:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
