[project]
name = "pyttp"
version = "0.1.1"
description = "Http utils for python REST APIs"
authors = []
dependencies = []
readme = "README.md"
requires-python = ">= 3.12"

[tool.rye]
managed = true
dev-dependencies = [
    "mypy>=1.10.1",
    "pytest-cov>=5.0.0",
    "ruff>=0.5.0",
    "mkdocs>=1.6.0",
    "mkdocstrings[python]>=0.25.1",
    "mkdocs-material>=9.5.29",
]

[tool.rye.scripts]
test = { cmd = "pytest --cov=src/ tests/" }
test-ui = { cmd = "pytest --cov=src/ --cov-report=html tests/" }
fix = { chain = [
   "ruff check --fix --quiet",
   "format:ruff",
]}
"format:ruff" = "ruff format"

"lint" = "ruff check --fix"

[build-system]
requires = ["hatchling==1.26.3", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.ruff.format]
docstring-code-format = true

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.report]
fail_under = 90

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/pyttp"]
