services:
  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - ENABLE_MONITORING=${ENABLE_MONITORING:-false}
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - mloptiflow-net

  kafka:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - mloptiflow-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - mloptiflow-net

networks:
  mloptiflow-net:
    driver: bridge
