name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and report coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        #run: uv run pytest tests
        run: uv run pytest --cov=./ --cov-branch --cov-report=xml tests

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
