[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "yyzz-sdk"
version = "0.1.0"
description = "A Python SDK"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.28.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=22.0",
    "mypy>=1.0",
]

# Add this section to specify the package location
[tool.hatch.build.targets.wheel]
packages = ["src/my_sdk"] 