[project]
name = "cgse"
version = "0.2.3"
description = "Generic Common-EGSE: Commanding and monitoring lab equipment"
authors = [
    {name = "Rik Huygen", email = "rik.huygen@kuleuven.be"},
    {name = "Sara Regibo", email = "sara.regibo@kuleuven.be"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "rich>=13.9.4",
    "tomlkit>=0.13.2",
]

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = [
    "libs/cgse-common/tests",
    "libs/cgse-core/tests",
]
addopts = "-rA --cov --cov-branch --cov-report html"
filterwarnings = [
    "ignore::DeprecationWarning"
]

[tool.coverage.run]
omit = [
    "*/tests/*",
    "conftest.py",
]

[tool.coverage.report]
fail_under = 80

[tool.uv.sources]
cgse-common = { workspace = true }
cgse-core = { workspace = true }
cgse-coordinates = { workspace = true }
cgse-gui = { workspace = true }
plato-spw = { workspace = true }

[tool.uv.workspace]
members = ["libs/*", "projects/generic/*", "projects/plato/*"]
exclude = ["docs/*"]

[tool.ruff.lint]
extend-select = ["E", "W"]

[tool.hatch.build.targets.wheel]
only-include = ["bump.py", "README.md"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.0",
]
