# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/ads/googleads/v18/resources/customer_lifecycle_goal.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'google/ads/googleads/v18/resources/customer_lifecycle_goal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.ads.googleads.v18.common import lifecycle_goals_pb2 as google_dot_ads_dot_googleads_dot_v18_dot_common_dot_lifecycle__goals__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@google/ads/googleads/v18/resources/customer_lifecycle_goal.proto\x12\"google.ads.googleads.v18.resources\x1a\x35google/ads/googleads/v18/common/lifecycle_goals.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xbf\x02\n\x15\x43ustomerLifecycleGoal\x12M\n\rresource_name\x18\x01 \x01(\tB6\xe0\x41\x05\xfa\x41\x30\n.googleads.googleapis.com/CustomerLifecycleGoal\x12r\n(customer_acquisition_goal_value_settings\x18\x03 \x01(\x0b\x32;.google.ads.googleads.v18.common.LifecycleGoalValueSettingsB\x03\xe0\x41\x03:c\xea\x41`\n.googleads.googleapis.com/CustomerLifecycleGoal\x12.customers/{customer_id}/customerLifecycleGoalsB\x8c\x02\n&com.google.ads.googleads.v18.resourcesB\x1a\x43ustomerLifecycleGoalProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v18/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V18.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V18\\Resources\xea\x02&Google::Ads::GoogleAds::V18::Resourcesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.ads.googleads.v18.resources.customer_lifecycle_goal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.google.ads.googleads.v18.resourcesB\032CustomerLifecycleGoalProtoP\001ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v18/resources;resources\242\002\003GAA\252\002\"Google.Ads.GoogleAds.V18.Resources\312\002\"Google\\Ads\\GoogleAds\\V18\\Resources\352\002&Google::Ads::GoogleAds::V18::Resources'
  _globals['_CUSTOMERLIFECYCLEGOAL'].fields_by_name['resource_name']._loaded_options = None
  _globals['_CUSTOMERLIFECYCLEGOAL'].fields_by_name['resource_name']._serialized_options = b'\340A\005\372A0\n.googleads.googleapis.com/CustomerLifecycleGoal'
  _globals['_CUSTOMERLIFECYCLEGOAL'].fields_by_name['customer_acquisition_goal_value_settings']._loaded_options = None
  _globals['_CUSTOMERLIFECYCLEGOAL'].fields_by_name['customer_acquisition_goal_value_settings']._serialized_options = b'\340A\003'
  _globals['_CUSTOMERLIFECYCLEGOAL']._loaded_options = None
  _globals['_CUSTOMERLIFECYCLEGOAL']._serialized_options = b'\352A`\n.googleads.googleapis.com/CustomerLifecycleGoal\022.customers/{customer_id}/customerLifecycleGoals'
  _globals['_CUSTOMERLIFECYCLEGOAL']._serialized_start=220
  _globals['_CUSTOMERLIFECYCLEGOAL']._serialized_end=539
# @@protoc_insertion_point(module_scope)
