repos:
  # Python
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
        types: [python]
      - id: check-builtin-literals
        types: [python]
      - id: detect-private-key
        types: [python]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=119
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args:
        - --max-line-length=119
  - repo: https://github.com/pycqa/pylint
    rev: v2.13.3
    hooks:
    -   id: pylint
        args:
        - --max-attributes=10
        - --ignore-imports=yes
        - -d duplicate-code
        - --disable=E0401
        - --max-line-length=119