[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "puntdice"
version = "1.1.1"
authors = [
  { name="Themadpunter", email="themadpunter@proton.me" },
]
description = "A Python dice roller command line utility and module."
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
Homepage = "https://github.com/familycomicsstudios/dice"

[project.scripts]
dice = "dice:main"
