# coding: utf-8

"""
    Canva Connect API

    API for building integrations with Canva via a REST api

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canva_ti.models.design_autofill_status import DesignAutofillStatus

class TestDesignAutofillStatus(unittest.TestCase):
    """DesignAutofillStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDesignAutofillStatus(self):
        """Test DesignAutofillStatus"""
        # inst = DesignAutofillStatus()

if __name__ == '__main__':
    unittest.main()
