# coding: utf-8

"""
    Canva Connect API

    API for building integrations with Canva via a REST api

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canva_ti.models.folder_item import FolderItem

class TestFolderItem(unittest.TestCase):
    """FolderItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FolderItem:
        """Test FolderItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FolderItem`
        """
        model = FolderItem()
        if include_optional:
            return FolderItem(
                type = 'folder',
                folder = canva_ti.models.folder.Folder(
                    id = 'FAF2lZtloor', 
                    name = 'My awesome holiday', 
                    created_at = 1377396000, 
                    updated_at = 1692928800, 
                    thumbnail = canva_ti.models.thumbnail.Thumbnail(
                        width = 595, 
                        height = 335, 
                        url = 'https://document-export.canva.com/Vczz9/zF9vzVtdADc/2/thumbnail/0001.png?<query-string>', ), )
            )
        else:
            return FolderItem(
                type = 'folder',
                folder = canva_ti.models.folder.Folder(
                    id = 'FAF2lZtloor', 
                    name = 'My awesome holiday', 
                    created_at = 1377396000, 
                    updated_at = 1692928800, 
                    thumbnail = canva_ti.models.thumbnail.Thumbnail(
                        width = 595, 
                        height = 335, 
                        url = 'https://document-export.canva.com/Vczz9/zF9vzVtdADc/2/thumbnail/0001.png?<query-string>', ), ),
        )
        """

    def testFolderItem(self):
        """Test FolderItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
