# coding: utf-8

"""
    Canva Connect API

    API for building integrations with Canva via a REST api

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canva_ti.api.asset_api import AssetApi


class TestAssetApi(unittest.TestCase):
    """AssetApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetApi()

    def tearDown(self) -> None:
        pass

    def test_create_asset_upload_job(self) -> None:
        """Test case for create_asset_upload_job

        """
        pass

    def test_delete_asset(self) -> None:
        """Test case for delete_asset

        """
        pass

    def test_get_asset(self) -> None:
        """Test case for get_asset

        """
        pass

    def test_get_asset_upload_job(self) -> None:
        """Test case for get_asset_upload_job

        """
        pass

    def test_update_asset(self) -> None:
        """Test case for update_asset

        """
        pass


if __name__ == '__main__':
    unittest.main()
