[tool.poetry]
name = "iam-actions"
version = "1.2.99999999"
description = "JSON of AWS policy components"
authors = ["Constable <info@constableapp.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/constableapp/iam_actions"
packages = [{include = "iam_actions"}]

include = [
    "iam_actions/actions.json", 
    "iam_actions/policies.json", 
    "iam_actions/resourcetypes.json", 
    "iam_actions/services.json"
]

[project.urls]
Homepage = "https://constableapp.com/"
Repository = "https://github.com/constableapp/iam_actions"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"

[tool.poetry.group.dev.dependencies]
slack-sdk = "^3.19.5"
beautifulsoup4 = "^4.11.1"
boto3 = "^1.26.46"
loguru = "^0.6.0"
black = "^22.12.0"
flakeheaven = "^3.2.1"

[tool.poetry.group.dev]
optional = true

[tool.black]
line-length = 180

[tool.flakeheaven]
format = "grouped"
max_line_length = 180
exclude = ["*.md", "dist"]

[tool.flakeheaven.plugins]
pyflakes = ["+*"]
pycodestyle = ["-*"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
iam_actions_generate = "iam_actions.generate:run"
