[project]
name = "tqdm-prometheus-exporter"
version = "0.1.0"
description = "Echo tqdm progress to a prometheus endpoint"
readme = "README.md"
authors = [
  { name="arrowed", email="arrowed@arrowed.org" },
]

requires-python = ">=3.12"

dependencies = [
    "tqdm>=4.67.1",
    "bottle>=0.13.0",
    "requests>=2.26.0",
    "pytest>=8.3.4",
    "pytest-cov>=3.0.0",
    "pytest-html>=3.0.0",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
  #  "Private :: Do Not Upload"
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/arrowed/tqdm-prometheus-exporter"
Issues = "https://github.com/arrowed/tqdm-prometheus-exporter/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages=["tqdmpromproxy"]

[[tool.uv.index]]
name = "testpypi"
url = "https://pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"