[project]
name = "cgse-coordinates"
version = "0.2.3"
description = "Reference Frames and Coordinate Transofrmations for CGSE"
authors = [
    {name = "Rik Huygen", email = "rik.huygen@kuleuven.be"},
    {name = "Sara Regibo", email = "sara.regibo@kuleuven.be"}
]
readme = {"file" = "README.md", "content-type" = "text/markdown"}
requires-python = ">=3.9"
license = "MIT"
keywords = [
    "CGSE",
    "Common-EGSE",
    "hardware testing",
    "software framework",
    "reference frames",
]
dependencies = [
    "cgse-common",
    "cgse-core",
    "numpy==1.22.4",
    "pandas>=1.5.1",
    "pip>=24.3.1",
    "transforms3d>=0.4.2",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-mock", "pytest-cov"]

[project.entry-points."cgse.version"]
cgse-coordinates = 'egse.version:get_version_installed'

[tool.hatch.build.targets.sdist]
exclude = [
    "/tests",
    "/pytest.ini",
    "/.gitignore",
]

[tool.hatch.build.targets.wheel]
packages = ["src/egse"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.0",
]
