name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.10"

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Build dist
        run: uv build

      - name: Build dist
        run: uv publish
