[project]
name = "dmt-smtp"
version = "0.1.1"
description = ""
authors = [
    {name = "Daniel",email = "daniel.mtorres7@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.1"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
