[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "ludic-slides"
dynamic = ["version"]
description = "Build fast presentations with Ludic"
keywords = ["html", "slides", "presentation"]
authors = [{ name = "Pavel Dedík", email = "dedikx@gmail.com" }]
maintainers = [{ name = "Pavel Dedík", email = "dedikx@gmail.com" }]
requires-python = ">=3.12"
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Education",
    "Intended Audience :: Other Audience",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Multimedia :: Graphics :: Presentation",
]
dependencies = ["ludic>=0.5.5", "pygments"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[project.scripts]
ludic-slides = "ludic_slides.cli:main"

[tool.hatch.envs.default]
python = "3.12"
platforms = ["linux", "macos"]
description = "Default environment with Python 3.12 for maximum compatibility"
features = ["test"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "_version.py"

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",    # flake8 rules
    "F",    # flake8 rules
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "I",    # isort
    "D2",   # pydocstyle
    "C901", # maccabe complexity
    "S",    # flake8-bandit
    "UP",   # pyupgrade
    "T10",  # flake8-debugger
]
ignore = ["B904", "S101", "D203", "D211", "D213", "UP040"]
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["ludic"]
known-third-party = ["examples"]

[tool.mypy]
python_version = "3.12"
strict = true
disallow_subclassing_any = false

[tool.pytest.ini_options]
testpaths = "tests"
norecursedirs = ".git docs .pytest_cache .mypy_cache .ruff_cache"
filterwarnings = [
    "ignore:The \\'app\\' shortcut is now deprecated. Use the explicit style \\'transport=WSGITransport\\(app=\\.\\.\\.\\)\\' instead\\.",
]
