# coding: utf-8

"""
    Canva Connect API

    API for building integrations with Canva via a REST api

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canva_alpha_ti.models.get_design_autofill_job_response import GetDesignAutofillJobResponse

class TestGetDesignAutofillJobResponse(unittest.TestCase):
    """GetDesignAutofillJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDesignAutofillJobResponse:
        """Test GetDesignAutofillJobResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDesignAutofillJobResponse`
        """
        model = GetDesignAutofillJobResponse()
        if include_optional:
            return GetDesignAutofillJobResponse(
                job = canva_alpha_ti.models.design_autofill_job.DesignAutofillJob(
                    id = '450a76e7-f96f-43ae-9c37-0e1ce492ac72', 
                    status = 'success', 
                    result = canva_alpha_ti.models.design_autofill_job_result.DesignAutofillJobResult(), 
                    error = canva_alpha_ti.models.autofill_error.AutofillError(
                        code = 'autofill_error', 
                        message = '', ), )
            )
        else:
            return GetDesignAutofillJobResponse(
                job = canva_alpha_ti.models.design_autofill_job.DesignAutofillJob(
                    id = '450a76e7-f96f-43ae-9c37-0e1ce492ac72', 
                    status = 'success', 
                    result = canva_alpha_ti.models.design_autofill_job_result.DesignAutofillJobResult(), 
                    error = canva_alpha_ti.models.autofill_error.AutofillError(
                        code = 'autofill_error', 
                        message = '', ), ),
        )
        """

    def testGetDesignAutofillJobResponse(self):
        """Test GetDesignAutofillJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
