[tool.poetry]
name = "colorex-py"
version = "0.1.0"
description = ""
authors = ["LunaStev <lunastev@gurmstudios.com>"]
packages = [{ include = "colorex" }]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.5,<4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
