[build-system]
requires = ["setuptools>=45", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "excel-to-db"
version = "1.1.3"
description = "A tool for importing Excel files to MySQL database"
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["excel", "mysql", "database", "import"]
dynamic = ["readme"]
dependencies = [
    "pandas>=1.3.0",
    "mysql-connector-python>=8.0.26",
    "openpyxl>=3.0.7",
    "tqdm>=4.62.0",
    "click>=8.0.1",
    "PyYAML>=5.4.1",
]
requires-python = ">=3.6"

[project.urls]
Homepage = "https://github.com/yourusername/excel_to_db"
Repository = "https://github.com/yourusername/excel_to_db.git"

[project.scripts]
excel2db = "excel_to_db.cli:cli"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["excel_to_db"] 