[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "tablemage"
version = "0.1.0-alpha.1"
description = "A Python package for low-code analysis of tabular data"
authors = [
    {name = "Andrew Yang", email = "andrew_j_yang@brown.edu"},
    {name = "Joshua Woo", email = "joshua_woo@brown.edu"},
    {name = "Ryan Zhang", email = "rzryanz00@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "numpy==1.26.4",
    "pandas==2.2.2",
    "scipy==1.14.1",
    "scikit-learn==1.5.2",
    "matplotlib==3.9.2",
    "seaborn==0.13.2",
    "xgboost==2.1.1",
    "statsmodels==0.14.3",
    "adjustText==1.2.0",
    "tableone==0.9.1",
    "umap-learn==0.5.7",
    "optuna==4.0.0",
    "optuna-integration==4.0.0",
]
license = {file = "LICENSE"}
keywords = ["data science", "low-code", "no-code", "statistics", "machine learning"]
classifiers = [
    "Programming Language :: Python"
]


[project.optional-dependencies]
agents = [
    "llama-index==0.12.13",
    "llama-index-llms-groq==0.3.1",
    "llama-index-llms-ollama==0.5.0",
    "llama-index-llms-openai==0.3.12",
    "Flask==3.0.3",
    "Flask-Cors==5.0.0",
    "python-dotenv==1.0.1",
    "llama-index-embeddings-fastembed==0.3.0",
    "fastembed==0.5.0",
]


[project.urls]
Homepage = "https://tablemage.readthedocs.io/"


[tool.hatch.metadata]
packages = [
    {include = "tablemage"}
]
