[project]
name = "photo-cleanup"
version = "0.1.5"
description = ""
authors = [
    {name = "Natalie Albers",email = "nralbers@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer (>=0.15.1,<0.16.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]

photo-cleanup = "photo_cleanup.main:app"