[package]
name = "pyaxp"
version = "0.1.14"
edition = "2021"

[dependencies]
pyo3 = { version = "0.23.3", features = ["extension-module", "serde"] }
yaxp-common = { path = "../yaxp-common", version = "0.1.14" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
arrow = "54.1.0"
polars = "0.46.0"
encoding_rs = "0.8.35"


[lib]
name = "pyaxp"
crate-type = ["cdylib", "rlib"]
