[tool.poetry]
name = "ceda-sentinel-dhs-tools"
version = "0.1.2"
description = "Tools for managing CEDA Sentinel DHS"
authors = ["Edbo849 <edborthwick84@gmail.com>"]
packages = [
    { include = "ceda_sentinel_dhs_tools" }
]
include = [
    "ceda_sentinel_dhs_tools/templates/*.json"
]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.32.3"
click = "^8.1.8"
jinja2 = "^3.1.5"
tabulate = "^0.9.0"
importlib_resources = "^6.0.0"

[tool.poetry.scripts]
list_producer_consumers = "ceda_sentinel_dhs_tools.list_producer_consumers:main"
create_producer_consumer = "ceda_sentinel_dhs_tools.create_producer_consumer:main"
delete_producer_consumer = "ceda_sentinel_dhs_tools.delete_producer_consumer:main"

[tool.poetry.group.dev.dependencies]
black = "^24.1.0"
mypy = "^1.8.0"
isort = "^5.13.2"
ruff = "^0.2.1"
bandit = "^1.7.7"
xenon = "^0.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.ruff.lint]
select = ["E", "F", "B", "I", "N", "W", "C"]
ignore = ["E501"]


[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.bandit]
exclude_dirs = ["tests"]
targets = ["ceda_sentinel_dhs_tools"]

[tool.quality.mccabe]
average = "B"
block = "B"
module = "B"
