[project]
name = "jarvais"
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64", "win-64", "osx-64"]

[tasks]
example = "jupyter lab"

[dependencies]
python = ">=3.10"
pyyaml = ">=6.0.2,<7"
fpdf2 = ">=2.8.1,<3"
jupyterlab = ">=4.2.5,<5"
seaborn = ">=0.13.2,<0.14"
"autogluon.tabular" = ">1.0"
pandas = ">2.0"
openpyxl = ">=3.1.5,<3.2"
htmlmin = "==0.1.12"
scipy = ">=1.11.4,<1.13"
tableone = "==0.9.1"
borb = ">=2.1.25,<3"
prettytable = ">=3.12.0,<4"
lifelines = ">=0.30.0,<0.31"
lightning = ">=2.4.0,<3"
optuna = "==4.1.0"
fairlearn = ">=0.12.0,<0.13"
shap = ">=0.46.0,<0.47"
statsmodels = ">=0.14.4,<0.15"
mkdocs = ">=1.6.1,<2"
scikit-learn = ">=1.5.2,<2"
hatch = ">=1.14.0,<2"

[pypi-dependencies]
jarvais = { path = ".", editable = true }
mrmr-selection = "==0.2.8"
umap-learn = ">=0.5.6, <0.6"
scikit-survival = ">=0.23.1,<0.24"
mkdocs-material = ">=9.5.49,<10" 
mkdocs-jupyter = ">=0.25.1,<0.26" 
mkdocs-pdf = ">=0.1.2,<0.2"
mkdocstrings = { version = ">=0.27.0, <0.28", extras = ["python"] }
optuna-integration = { version = "==4.1.0", extras = ["pytorch-lightning"] }

[environments]
dev = { features = ["test", "style"], solve-group = "default" }
py310 = ["py310", "test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]

############################################## python ###############################################

[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

############################################## TEST ################################################

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"

[feature.test.tasks.test]
cmd = [
  "pytest",
  "--numprocesses=auto",
  "-s",
  "--verbose",
  "--cov=readii",
  "--cov-report=xml:coverage-report/coverage.xml",
  "--cov-config=configs/coverage.toml",
]
inputs = ["src", "tests", "configs/coverage.toml"]
outputs = ["coverage-report/coverage.xml"]
description = "Run pytest (Note: run `coverage` task to do both)"

[feature.test.tasks.coverage]
cmd = "coverage report --rcfile=configs/coverage.toml"
inputs = ["coverage-report/coverage.xml", "configs/coverage.toml"]
depends-on = ["test"]
description = "Run pytest and generate coverage report"

############################################## STYLE ###############################################
# See configs/ruff.toml for the configuration
[feature.style.dependencies]
ruff = ">=0.4.4"
pre-commit = ">=3.7.1,<3.8"

[feature.style.tasks]
[feature.style.tasks.lint]
cmd = "ruff check  --config=configs/ruff.toml"
inputs = ["src", "configs/ruff.toml"]
description = "Run ruff linter"

[feature.style.tasks.format]
cmd = "ruff format --config=configs/ruff.toml"
inputs = ["src", "configs/ruff.toml"]
description = "Run ruff formatter, use `--diff` to see changes only"
