[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcsmapi"
version = "0.1.3"
description = "Shortcut the pypi package of MCSM./快捷操作MCSM的pypi包"
readme = "README.md"
authors = [
    { name = "molanp", email = "molanpp@outlook.com" }
]
urls = { "Source" = "https://github.com/molanp/mcsmapi" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

dependencies = [
    "requests",
    "pydantic"
]