[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flexible-datetime"
version = "1.0.9"
description = "Flexible datetime handling for Python"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11"
dependencies = [
    "arrow>=1.3.0",
    "pydantic>=2.10.6",
]

[dependency-groups]
dev = [
    "beanie>=1.29.0",
    "black>=25.1.0",
    "pytest>=8.3.4",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
