[package]
name = "rscheduler"
version = "0.2.1"
edition = "2021"
authors = ["Takahiro Ishiguro"]
description = "A high-precision task scheduler for Python, built with Rust for accuracy and efficiency"
readme = "README.md"
repository = "https://github.com/LemonPepperSeasoning/rscheduler"
license = "Apache-2.0"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rscheduler"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
