[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "taskman-sv"
version = "0.1.1"
description = "A secure task management and note-taking application"
readme = "README.md"
authors = [{name = "Shreedhar", email = "shreedharv16@gmail.com"}]
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
keywords = ["task", "management", "notes", "productivity"]
dependencies = [
    "colorama",
    "cryptography",
    "bcrypt",
    "pywin32; platform_system == 'Windows'",
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/shreedharv16/taskman"
Repository = "https://github.com/shreedharv16/taskman.git"

[project.scripts]
taskman = "taskman.cli:main"