[project]
name = "lsqbc"
dynamic = [ "version" ]
description = "A functional programming language"
authors = [
    {name = "henceiusegentoo",email = "61363222+henceiusegentoo@users.noreply.github.com"}
]
requires-python = ">=3.12"
dependencies = [
]
readme="package-info.md"

[tool.poetry]
version = "0.1.0"
packages = [
    {include = "qb",from = "."}
]

[project.scripts]
qb = "qb.__main__:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
