[tool.poetry]
name = "cosmic-crisp"
version = "1.1.0.dev20250208080410"
packages = [
    { include = "pinecone_plugins", from = "." },
]

description = "Assistant plugin for Cosmic Crisp SDK"
authors = ["Cosmic Crisp Systems, Inc. <support@cosmic-crisp.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://www.cosmic-crisp.com"
documentation = "https://cosmic-crisp.com/docs"
keywords = []
classifiers=[
        "License :: OSI Approved :: Apache Software License",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pinecone-client = "^4.1.1"
pytest = "^8.2.1"
responses = ">=0.8.1"
pytest-cov = "^5.0.0"
pytest-dotenv = "^0.5.2"
pytest-timeout = "^2.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
