[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "color_stream"

# Reminder: version is also in __init__.py.
version = "0.3.1"
description = "A tool to run another shell command, and color the stdout/stderr streams green/red"
authors = [{ name = "DeflateAwning" }]
license = "Unlicense"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pyright",
]

[project.urls]
homepage = "https://github.com/DeflateAwning/color_stream"
repository = "https://github.com/DeflateAwning/color_stream"
issues = "https://github.com/DeflateAwning/color_stream/issues"
pypi = "https://pypi.org/project/color-stream/"

[project.scripts]
color_stream = "color_stream.core:main"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "TD002", "TD003", "FIX002", "COM812",
    "T201", # allow print statements
    "PLR2004",
]

[tool.ruff]
line-length = 79
