[project]
name = "{{folder_name}}"
version = "0.4.0"
description = "{{name}} using cropioAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "cropioai[tools]>=0.2.0,<1.0.0",
]

[project.scripts]
ignite = "{{folder_name}}.main:ignite"
plot = "{{folder_name}}.main:plot"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.cropioai]
type = "flow"
