[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "did-stuff"
authors = [
  {name="Jarad DeLorenzo", email="jaradd@gmail.com"}
]
description = "AI-powered Git commit message generator"
readme = "README.md"
keywords = ["git", "commit", "message", "generator", "AI"]
license = {text = "MIT"}
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
version = "0.1.6"
dependencies = [
  "click>=8.1.3",
  "openai>=0.27.0", 
  "boto3>=1.26"
]

[project.optional-dependencies]
dev = [
  "pytest>=7.4.3",
  "pytest-cov>=4.0.0"
]

[project.scripts]
did-stuff = "did_stuff.cli:main"

[tool.setuptools]
packages = ["did_stuff"]

[tool.ruff]
select = ["E", "F", "I"]
ignore = []
line-length = 120

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pytest.ini_options]
addopts = "--cov=did_stuff --cov-report=xml:coverage.xml"
testpaths = ["tests"]

[tool.coverage.run]
source = ["did_stuff"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "if self.debug:",
  "if __name__ == .__main__.:",
  "raise NotImplementedError",
  "pass",
  "except ImportError:",
]
