[project]
name = "msaf2"
version = "0.5.0"
description = "Building and managing MSA prior to stucture inference"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.83",
    "fastparquet>=2024.11.0",
    "pandas>=2.2.3",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
]
authors = [
  {name = "Guillaume Launay", email = "guillaume.launay@univ-lyon1.fr"}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
msaf2 = "msaf2.__main__:main"

[tool.uv]
dev-dependencies = [
  "ipykernel",
]