[project]
name = "pelican-photos"
version = "1.6.2"
authors = [
    { name = "Joaquim Baptista", email = "pxquim@gmail.com" },
]
description = "Add a photo or a gallery of photos to an article"
readme = "README.md"
keywords = [
    "pelican",
    "plugin",
    "photos",
    "image",
]
repository = "https://github.com/pelican-plugins/photos"
documentation = "https://docs.getpelican.com"
packages = [
    { include = "pelican" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Framework :: Pelican",
    "Framework :: Pelican :: Plugins",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.8.1,<4.0"
dependencies = [
    "pelican>=4.5",
    "piexif~=1.1.3",
    "Pillow>=10.0.1,<12.0.0",
]

[project.license]
text = "AGPL-3.0"

[project.urls]
Funding = "https://donate.getpelican.com/"
"Issue Tracker" = "https://github.com/pelican-plugins/photos/issues"

[project.optional-dependencies]
markdown = [
    "markdown",
]

[tool.pdm.dev-dependencies]
lint = [
    "invoke>=2.2.0",
    "ruff>=0.4,<0.5",
]
test = [
    "markdown>=3.4",
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "pytest-sugar>=0.9.7",
]

[tool.pdm.build]
source-includes = [
    "CONTRIBUTING.rst",
    "examples/",
]
includes = [
    "pelican/",
]
excludes = [
    "**/test_data/**",
]

[tool.autopub]
project-name = "Photos"
git-username = "botpub"
git-email = "52496925+botpub@users.noreply.github.com"
append-github-contributor = true

[tool.ruff.lint]
select = [
    "B",
    "BLE",
    "C4",
    "D",
    "E",
    "F",
    "I",
    "ICN",
    "ISC",
    "PGH",
    "PL",
    "RET",
    "RUF",
    "SIM",
    "T10",
    "T20",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT",
]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    "D203",
    "D213",
    "ISC001",
    "PGH004",
    "PLR2004",
    "PLW0603",
    "RUF100",
    "TRY003",
    "TRY400",
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = [
    "pelican",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
