[project]
name = "cv-depot"
version = "0.6.1"
description = "Computer Vision Tools"
readme = "README.md"
license = "MIT"
keywords = [
    "OpenEXR",
    "EXR",
    "openexr",
    "exr",
    "computer-vision",
    "cv",
    "image",
    "compositing",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.3",
    "IPython",
    "ipywidgets",
    "lunchbox>=0.3.3",
    "numpy>=2.2.2",
    "openexr-tools>=0.4.0",
    "pillow>=11.1.0",
]
authors = [
    { name = "Alex Braun", email = "alexander.g.braun@gmail.com" },
]

[project.urls]
repository = "https://github.com/thenewflesh/cv-depot"
documentation = "https://theNewFlesh.github.io/cv-depot"

[project.scripts]
cv-depot = "cv_depot.command:main"

[build-system]
requires = [
    "pdm-pep517>=1.0.0",
]
build-backend = "pdm.pep517.api"

[tool.uv]
cache-dir = "/home/ubuntu/pdm/cache"

[tool.coverage.report]
show_missing = true
omit = [
    "*/__init__.py",
    "*/*_test_base.py",
    "*/*_test.py",
    "*/*_tests.py",
    "*/cli.py",
    "*/command.py",
    "*/mock_*.py",
    "*/conftest.py",
]
