# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/ads/googleads/v17/resources/campaign_lifecycle_goal.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'google/ads/googleads/v17/resources/campaign_lifecycle_goal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.ads.googleads.v17.common import lifecycle_goals_pb2 as google_dot_ads_dot_googleads_dot_v17_dot_common_dot_lifecycle__goals__pb2
from google.ads.googleads.v17.enums import customer_acquisition_optimization_mode_pb2 as google_dot_ads_dot_googleads_dot_v17_dot_enums_dot_customer__acquisition__optimization__mode__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@google/ads/googleads/v17/resources/campaign_lifecycle_goal.proto\x12\"google.ads.googleads.v17.resources\x1a\x35google/ads/googleads/v17/common/lifecycle_goals.proto\x1aKgoogle/ads/googleads/v17/enums/customer_acquisition_optimization_mode.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x8c\x03\n\x15\x43\x61mpaignLifecycleGoal\x12M\n\rresource_name\x18\x01 \x01(\tB6\xe0\x41\x05\xfa\x41\x30\n.googleads.googleapis.com/CampaignLifecycleGoal\x12;\n\x08\x63\x61mpaign\x18\x02 \x01(\tB)\xe0\x41\x03\xfa\x41#\n!googleads.googleapis.com/Campaign\x12t\n\"customer_acquisition_goal_settings\x18\x03 \x01(\x0b\x32\x43.google.ads.googleads.v17.resources.CustomerAcquisitionGoalSettingsB\x03\xe0\x41\x03:q\xea\x41n\n.googleads.googleapis.com/CampaignLifecycleGoal\x12<customers/{customer_id}/campaignLifecycleGoals/{campaign_id}\"\x89\x02\n\x1f\x43ustomerAcquisitionGoalSettings\x12\x8b\x01\n\x11optimization_mode\x18\x01 \x01(\x0e\x32k.google.ads.googleads.v17.enums.CustomerAcquisitionOptimizationModeEnum.CustomerAcquisitionOptimizationModeB\x03\xe0\x41\x03\x12X\n\x0evalue_settings\x18\x02 \x01(\x0b\x32;.google.ads.googleads.v17.common.LifecycleGoalValueSettingsB\x03\xe0\x41\x03\x42\x8c\x02\n&com.google.ads.googleads.v17.resourcesB\x1a\x43\x61mpaignLifecycleGoalProtoP\x01ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v17/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V17.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V17\\Resources\xea\x02&Google::Ads::GoogleAds::V17::Resourcesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.ads.googleads.v17.resources.campaign_lifecycle_goal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.google.ads.googleads.v17.resourcesB\032CampaignLifecycleGoalProtoP\001ZKgoogle.golang.org/genproto/googleapis/ads/googleads/v17/resources;resources\242\002\003GAA\252\002\"Google.Ads.GoogleAds.V17.Resources\312\002\"Google\\Ads\\GoogleAds\\V17\\Resources\352\002&Google::Ads::GoogleAds::V17::Resources'
  _globals['_CAMPAIGNLIFECYCLEGOAL'].fields_by_name['resource_name']._loaded_options = None
  _globals['_CAMPAIGNLIFECYCLEGOAL'].fields_by_name['resource_name']._serialized_options = b'\340A\005\372A0\n.googleads.googleapis.com/CampaignLifecycleGoal'
  _globals['_CAMPAIGNLIFECYCLEGOAL'].fields_by_name['campaign']._loaded_options = None
  _globals['_CAMPAIGNLIFECYCLEGOAL'].fields_by_name['campaign']._serialized_options = b'\340A\003\372A#\n!googleads.googleapis.com/Campaign'
  _globals['_CAMPAIGNLIFECYCLEGOAL'].fields_by_name['customer_acquisition_goal_settings']._loaded_options = None
  _globals['_CAMPAIGNLIFECYCLEGOAL'].fields_by_name['customer_acquisition_goal_settings']._serialized_options = b'\340A\003'
  _globals['_CAMPAIGNLIFECYCLEGOAL']._loaded_options = None
  _globals['_CAMPAIGNLIFECYCLEGOAL']._serialized_options = b'\352An\n.googleads.googleapis.com/CampaignLifecycleGoal\022<customers/{customer_id}/campaignLifecycleGoals/{campaign_id}'
  _globals['_CUSTOMERACQUISITIONGOALSETTINGS'].fields_by_name['optimization_mode']._loaded_options = None
  _globals['_CUSTOMERACQUISITIONGOALSETTINGS'].fields_by_name['optimization_mode']._serialized_options = b'\340A\003'
  _globals['_CUSTOMERACQUISITIONGOALSETTINGS'].fields_by_name['value_settings']._loaded_options = None
  _globals['_CUSTOMERACQUISITIONGOALSETTINGS'].fields_by_name['value_settings']._serialized_options = b'\340A\003'
  _globals['_CAMPAIGNLIFECYCLEGOAL']._serialized_start=297
  _globals['_CAMPAIGNLIFECYCLEGOAL']._serialized_end=693
  _globals['_CUSTOMERACQUISITIONGOALSETTINGS']._serialized_start=696
  _globals['_CUSTOMERACQUISITIONGOALSETTINGS']._serialized_end=961
# @@protoc_insertion_point(module_scope)
