[build-system]
requires = ['setuptools>=61.0']
build-backend = 'setuptools.build_meta'

[bdist_wheel]
universal = 0

[project]
name = "setux_core"
dynamic = ['version', 'readme']
description = 'System deployment'
authors = [
    {name = 'Louis RIVIERE', email = 'louis@riviere.xyz'},
]
requires-python = ">=3.9"
dependencies = [
    'pybrary>=0.2507.1',
]
keywords = [
    'utility',
]
classifiers = [
    'Development Status :: 3 - Alpha',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
    'Intended Audience :: Developers',
    'Intended Audience :: Information Technology',
    'Intended Audience :: System Administrators',
    'Topic :: System :: Installation/Setup',
    'Topic :: System :: Systems Administration',
    'Topic :: Utilities',
]
license = {text = 'MIT'}

[project.urls]
pypi = 'https://pypi.org/project/setux-core'
repository = 'https://github.com/louis-riviere-xyz/setux_core'
[tool.setuptools]
include-package-data = false

[tool.setuptools.dynamic]
version = {attr = 'setux.core.__version__'}
readme = {file = ['README.md'], content-type = 'text/markdown'}

[tool.setuptools.packages.find]
include = ['setux.*']
