[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tyrian-sphinx-theme"
authors = [
    {name = "Max Magorsch", email = "max@magorsch.de"},
]
description = "A Tyrian based Sphinx theme for Gentoo"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.8"
license = {text = "BSD-2-Clause"}
classifiers = [
    "Framework :: Sphinx",
    "Framework :: Sphinx :: Theme",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
]
dynamic = ["version"]
dependencies = [
    "sphinx",
]

[project.urls]
Homepage = "https://gitweb.gentoo.org/proj/tyrian-sphinx-theme.git"

[project.entry-points."sphinx.html_themes"]
tyrian_sphinx_theme = "tyrian_sphinx_theme"
