from dataclasses import dataclass
from ydata.sdk.datasources._models.datasource import DataSource

@dataclass
class MySQLDataSource(DataSource):
    query: str = ...
    tables: dict = ...
    def to_payload(self): ...
    def __init__(self, query=..., tables=...) -> None: ...
