[tool.poetry]
name = "peak-utility"
version = "0.7.0"
description = "A library of utilities, created by peaky76"
authors = ["peaky76 <robertjamespeacock@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [{ include = "peak_utility" }]

[tool.poetry.dependencies]
python = "^3.8"
infix = "^1.2"
deprecation = "^2.1.0"

[tool.poetry.group.dev.dependencies]
auto-changelog = "^0.6.0"
coverage = "^7.3.1"
mypy = "^1.5.1"
pytest = ">=7.4.2,<9.0.0"
pytest-cov = ">=4.1,<6.0"
sphinx = "^7.1.2"
sphinx-rtd-theme = ">=1.3,<4.0"
ruff = ">=0.1.4,<0.10.0"

[tool.ruff.lint]
select = [
    "E", # pycodestyle Error
    "F", # pyflakes
    "C90", # mccabe
    "I", # isort
    "N", # pep8-naming
    "UP", # pyupgrade
    "FBT", # flake8-boolean-trap
    "C4", # flake8-comprehensions
    "PYI", # flake8-pyi
    "PT", # flake8-pytest-style
    "RSE", # flake8-raise
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "PTH", # flake8-use-pathlib
    "PERF", # perflint
    "FURB", # refurb
    "RUF", # ruff specific

]
ignore = ["E501", "E731", "PT011"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
