# Generated by Django 3.2.12 on 2024-04-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0035_auto_20240403_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='boolean_1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='boolean_2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='boolean_3',
        ),
        migrations.RemoveField(
            model_name='member',
            name='boolean_4',
        ),
        migrations.RemoveField(
            model_name='member',
            name='boolean_5',
        ),
        migrations.RemoveField(
            model_name='member',
            name='boolean_6',
        ),
        migrations.RemoveField(
            model_name='member',
            name='group_when_created',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_10',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_11',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_12',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_13',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_14',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_3',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_4',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_5',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_6',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_7',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_8',
        ),
        migrations.RemoveField(
            model_name='member',
            name='string_9',
        ),
        migrations.AddField(
            model_name='member',
            name='extras_json',
            field=models.JSONField(default=dict),
        ),
    ]
