# Generated by Django 3.2.12 on 2024-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0036_auto_20240405_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='boolean_1',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='boolean_2',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='boolean_3',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='boolean_4',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='boolean_5',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='date_1',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='date_2',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='int_1',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='int_2',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='int_3',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='int_4',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='int_5',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='meta_json',
            field=models.JSONField(default=dict),
        ),
    ]
