# Generated by Django 3.2.12 on 2024-04-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0037_auto_20240418_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='string_1',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='string_2',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='string_3',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='string_4',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='string_5',
        ),
    ]
