"""
biosim-server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import unittest

from biosim_client.api.biosim.api.verification_api import VerificationApi


class TestVerificationApi(unittest.TestCase):
    """VerificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VerificationApi()

    def tearDown(self) -> None:
        pass

    def test_get_verify_omex(self) -> None:
        """Test case for get_verify_omex

        Retrieve verification report for OMEX/COMBINE archive
        """
        pass

    def test_get_verify_runs(self) -> None:
        """Test case for get_verify_runs

        Get verification report for biosimulation runs
        """
        pass

    def test_start_verify_omex(self) -> None:
        """Test case for start_verify_omex

        Request verification report for OMEX/COMBINE archive
        """
        pass

    def test_start_verify_runs(self) -> None:
        """Test case for start_verify_runs

        Request verification report for biosimulation runs
        """
        pass


if __name__ == "__main__":
    unittest.main()
