[package]
name = "chikvdf"
version = "1.1.5"
edition = "2021"
license = "Apache-2.0"
description = "Bindings to the chikvdf C++ library."
authors = ["Brandon Haggstrom <b.haggstrom@chiknetwork.com>"]
homepage = "https://github.com/Chik-Network/chikvdf"
repository = "https://github.com/Chik-Network/chikvdf"

[dependencies]
link-cplusplus = "1.0.9"

[build-dependencies]
bindgen = "0.69.4"
cmake = "0.1.50"

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
