[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pse"
version = "1.4.2"
authors = [
    { name = "Jack Wind", email = "jckwind11@gmail.com" },
    { name = "The Proxy Company", email = "contact@theproxy.company" }
]
description = "Proxy Structuring Engine: Stateful AI-generated output with a focus on creativity, speed, and structure."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }

dependencies = [
    "docstring-parser",
    "protobuf",
    "pse-core",
    "pydantic",
    "regex",
    "tokenizers",
    "transformers",
    "tqdm",
    "typing_extensions",
    "wheel",
    "lark>=1.2.2",
]

[project.optional-dependencies]
dev = [
    "coverage",
    "docstring-parser",
    "flake8",
    "instructor",
    "lm-format-enforcer",
    "mlx",
    "mlx-proxy",
    "openai",
    "outlines",
    "pse-core",
    "pytest",
    "ruff",
    "sentencepiece",
]

[project.urls]
homepage = "https://github.com/TheProxyCompany/proxy-structuring-engine"
documentation = "https://github.com/TheProxyCompany/proxy-structuring-engine#readme"
source = "https://github.com/TheProxyCompany/proxy-structuring-engine"

[tool.ruff.lint]
extend-select = [
    "B",    # flake8-bugbear
    "I",    # isort
    "PGH",  # pygrep-hooks
    "RUF",  # Ruff-specific
    "UP",   # pyupgrade
    "SLF",  # string-literal-format
    "F8",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.sdist]
include = [
    "LICENSE",
    "README.md",
    "pyproject.toml",
    "pse"
]

[tool.hatch.build.targets.wheel]
packages = ["pse"]
include = ["pse/**"]
optimize = true
ignore-vcs = true

[tool.hatch.envs.default]
python = "3.11"
env-vars = { PYTHONOPTIMIZE = "2" }

[tool.pytest.ini_options]
log_cli = false
log_cli_level = "INFO"
log_cli_format = "in %(filename)s:%(lineno)d [%(levelname)s] %(message)s"
log_cli_date_format = "%H:%M:%S"
