[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "qwgraph"
dependencies = ["numpy>=1.23.5", "pandas>=1.5.1", "matplotlib>=3.5.1", "networkx>=3.0", "tqdm>=4.64.1"]

[tool.maturin]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["pyo3/extension-module"]