[project]
name = "argenta"
version = "0.1.2"
description = "python library for creating cli apps"
authors = [
    {name = "kolo",email = "kolo.is.main@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
