[build-system]
requires = ["setuptools>=61.0", "wheel"]  # Build tools needed
build-backend = "setuptools.build_meta"

[project]
name = "ailibrary"
version = "0.1.3"
description = "AI Library REST API for any Python 3.8+ application."
requires-python = ">=3.8"
readme = "README.md"
authors = [
    {name = "Arani Chaudhuri", email = "arani@ailibrary.ai"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
license = {text = ""} #?
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["src"]  # Tell setuptools to look for packages in the 'src' folder
